// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! D.THINK.COMPOSITOR.1 — Recursive depth composition.
//!
//! The compositor searches for composed thoughts that achieve understanding.
//! MAX_DEPTH=6, TOP_N=5. Iterative deepening over the vocabulary.
//!
//! The vocabulary has three tiers:
//! 1. Base alphabet: irreducible algebraic generators (spatial + value)
//! 2. Observation-derived: AbsoluteTarget, CellChange from training data
//! 3. Genomic words: ComposedOperators promoted to depth-1 as Thought::Genomic
//!
//! The alphabet stays fixed. The words grow. Core Design Law 8.
//! Fewer letters, deeper words. DNA has 4 base pairs, infinite proteins.

use super::vocabulary::*;
use crate::perception;

pub fn thought_vocabulary(
    train_pairs: &[(Vec<i64>, Vec<i64>)],
    rows: usize, cols: usize,
) -> ThinkingResult {
    thought_vocabulary_with_genome(train_pairs, rows, cols, &[])
}

/// Compositor with genomic vocabulary expansion.
///
/// Composed operators from the genome enter at depth 1 alongside the base
/// alphabet. A depth-6 composition starting from a genomic operator is
/// effectively depth 9+ from the original alphabet. The children's words
/// become the parents of deeper sentences.
pub fn thought_vocabulary_with_genome(
    train_pairs: &[(Vec<i64>, Vec<i64>)],
    rows: usize, cols: usize,
    composed_operators: &[crate::engine::ComposedOperator],
) -> ThinkingResult {
    let vocab = base_vocabulary(rows, cols);

    let mut extended_vocab = vocab.clone();

    // ── Tier 2: Observation-derived thoughts ──
    // Add object-derived thoughts: read non-zero cells as objects with directionality
    // Extract seed from trajectory ordering of non-zero objects
    if let Some((first_in, _first_out)) = train_pairs.first() {
        let objects: Vec<(usize, usize, i64)> = (0..rows)
            .flat_map(|r| (0..cols).map(move |c| (r, c, first_in[r * cols + c])))
            .filter(|(_, _, v)| *v != 0)
            .collect();

        if !objects.is_empty() {
            // Check if objects lie on a diagonal (trajectory detection)
            let on_diagonal = objects.iter().all(|(r, c, _)| r == c)
                || objects.windows(2).all(|w| {
                    let dr = w[1].0 as i64 - w[0].0 as i64;
                    let dc = w[1].1 as i64 - w[0].1 as i64;
                    dr == dc  // diagonal trajectory
                });

            if on_diagonal || objects.len() >= 2 {
                // INTELLIGENCE: extract unique values with their diagonal positions
                let mut sorted_objects = objects.clone();
                sorted_objects.sort_by_key(|(r, c, _)| r + c);

                let mut unique_with_dpos: Vec<(i64, usize)> = Vec::new();
                for (r, c, v) in &sorted_objects {
                    unique_with_dpos.iter().find(|(ev, _)| *ev == *v).is_none()
                        .then(|| unique_with_dpos.push((*v, r + c)));
                }

                if !unique_with_dpos.is_empty() {
                    let p = unique_with_dpos.len();
                    // THE DERIVED ALGEBRAIC FACT:
                    // seed[diagonal_position % period] = value
                    // The diagonal residue class determines the seed ordering.
                    // Not scripted. Derived from object positions modulo period.
                    let mut seed = vec![0i64; p];
                    for (v, dpos) in &unique_with_dpos {
                        seed[dpos % p] = *v;
                    }

                    let targets: Vec<i64> = (0..rows * cols).map(|idx| {
                        let r = idx / cols;
                        let c = idx % cols;
                        seed[(r + c) % p]
                    }).collect();
                    extended_vocab.push(Thought::AbsoluteTarget(targets));
                }
            }

            // Also check staircase pattern (objects at (0,0),(1,1),(2,2)... but shifted per row)
            let on_staircase = objects.windows(2).all(|w| {
                let dr = w[1].0 as i64 - w[0].0 as i64;
                dr >= 0  // objects descend row-wise
            });

            if on_staircase && !on_diagonal {
                // Read values in row-first order as the seed
                let seed: Vec<i64> = objects.iter().map(|(_, _, v)| *v).collect();
                let mut unique_seed: Vec<i64> = Vec::new();
                for &v in &seed {
                    unique_seed.iter().find(|&&ev| ev == v).is_none()
                        .then(|| unique_seed.push(v));
                }

                if !unique_seed.is_empty() {
                    let p = unique_seed.len();
                    let targets: Vec<i64> = (0..rows * cols).map(|idx| {
                        let r = idx / cols;
                        let c = idx % cols;
                        unique_seed[(r + c) % p]
                    }).collect();
                    extended_vocab.push(Thought::AbsoluteTarget(targets));
                }
            }
        }
    }

    // Also add the per-cell change as a thought (from perception module)
    if let Some(rule) = perception::extract_rule(train_pairs) {
        let cell_changes: Vec<i64> = rule.iter().map(|q| {
            let n: i64 = q.numer().try_into().unwrap_or(0);
            let d: i64 = q.denom().try_into().unwrap_or(1);
            if d == 0 { 0 } else { n / d }
        }).collect();
        extended_vocab.push(Thought::CellChange(cell_changes));
    }

    // ── Tier 3: Genomic words — promoted to depth 1 ──
    // Each composed operator was earned through C(T) = 0 across training pairs.
    // They enter the compositor as first-class generators alongside Identity
    // and Rotate90. A depth-6 composition starting from a genomic operator
    // is effectively depth 9+ from the original alphabet.
    for comp_op in composed_operators {
        extended_vocab.push(Thought::Genomic {
            opcode: comp_op.opcode,
            parameter: comp_op.parameter,
            sigma: comp_op.sigma.clone(),
        });
    }

    let mut best = ThinkingResult {
        best_thought: Thought::Identity,
        distance: u64::MAX,
        understood: false,
        thoughts_evaluated: 0,
        depth: 0,
    };

    // Depth 1: single thoughts
    for thought in &extended_vocab {
        let mut total_dist: u64 = 0;
        for (inp, out) in train_pairs {
            let (dist, _) = thought_score(thought, inp, out, rows, cols);
            total_dist += dist;
        }
        best.thoughts_evaluated += 1;

        if total_dist < best.distance {
            best.distance = total_dist;
            best.best_thought = thought.clone();
            best.depth = 1;
        }
        if total_dist == 0 {
            best.understood = true;
            return best; // Perfect understanding — stop thinking
        }
    }

    // Recursive depth composition — holonomic path reconstruction.
    // Each depth takes the top N partial solutions from the previous depth
    // and composes each with the full vocabulary. The residual from depth D
    // is the input to depth D+1. This IS parallel transport across the manifold.
    //
    // Complexity: O(V * N) per depth level, not O(V^D).
    // With ~36 generators (reduced base + genomic words) at depth 6:
    // 6 × 36 × 5 = 1,080 evaluations. Far below the metabolic horizon.
    const TOP_N: usize = 5;
    const MAX_DEPTH: u32 = 6;

    // Score all single thoughts as depth-1 candidates
    let mut candidates: Vec<(u64, Thought)> = extended_vocab.iter().map(|t| {
        let d: u64 = train_pairs.iter().map(|(i, o)| thought_score(t, i, o, rows, cols).0).sum();
        (d, t.clone())
    }).collect();
    candidates.sort_by_key(|(d, _)| *d);
    candidates.truncate(TOP_N);

    // Iterative deepening: depth 2, 3, 4, 5, 6 up to MAX_DEPTH
    for depth in 2..=MAX_DEPTH {
        let mut next_candidates: Vec<(u64, Thought)> = Vec::new();

        // Compose each top candidate from previous depth with each vocab entry
        for (_, partial) in &candidates {
            for vocab_entry in &extended_vocab {
                let composed = Thought::Compose(
                    Box::new(partial.clone()),
                    Box::new(vocab_entry.clone()),
                );
                let total_dist: u64 = train_pairs.iter()
                    .map(|(inp, out)| thought_score(&composed, inp, out, rows, cols).0)
                    .sum();
                best.thoughts_evaluated += 1;

                // Track the best across all depths
                (total_dist < best.distance).then(|| {
                    best.distance = total_dist;
                    best.best_thought = composed.clone();
                    best.depth = depth;
                });

                // Understanding achieved — the sentence is complete
                (total_dist == 0).then(|| {
                    best.understood = true;
                });
                // Return immediately on understanding
                if best.understood { return best; }

                next_candidates.push((total_dist, composed));
            }
        }

        // Select top N for next depth — the residual carriers
        next_candidates.sort_by_key(|(d, _)| *d);
        next_candidates.truncate(TOP_N);

        // If no candidate improved over previous depth's best, the manifold
        // is exhausted at this vocabulary. No plateau breakthrough possible.
        // The species has read as far as its current words allow.
        let depth_best = next_candidates.first().map(|(d, _)| *d).unwrap_or(u64::MAX);
        candidates = next_candidates;

        // If the best at this depth is worse than overall best and we've
        // tried at least depth 5, the path is diverging — stop gracefully
        (depth >= 5 && depth_best >= best.distance && depth_best > 0).then(|| {
            // Diverging — further composition is adding noise, not signal
        });
        if depth >= 5 && depth_best >= best.distance && depth_best > 0 {
            break;
        }
    }

    best
}
