// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! Phase 2 Mesh Transport and Peer State (Layer 2).
//!
//! Implements the peer state model, sluice weighting, divergence proxy,
//! K-gate majority check, and wire format for receipt broadcast.
//!
//! Transport: synchronous TCP for Phase 2.1 (correctness-first).
//! ZeroMQ migration deferred to Phase 2.2.
//!
//! Register: T.SAMN.2 (entropy sluicing), CC.SAMN.3 (K-gate),
//!           D.CHAIN.ORBIT.1 (RCF identity), D.SAMN.2 (divergence).

pub mod transport;
pub mod broadcast;

use num_bigint::BigInt;
use num_rational::BigRational;
use num_traits::{One, Signed, Zero};

use crate::constants;
use crate::ledger::MeshReceipt;

type Q = BigRational;

fn qi(n: i64) -> Q {
    Q::from_integer(BigInt::from(n))
}

fn q(n: i64, d: i64) -> Q {
    Q::new(BigInt::from(n), BigInt::from(d))
}

// ─── Peer State ────────────────────────────────────────────────────────

/// State of a single mesh peer, derived from their latest MeshReceipt.
///
/// Register: D.SAMN.4 (mesh state aggregation).
#[derive(Debug, Clone)]
pub struct PeerState {
    /// Peer's entity ID.
    pub entity_id: u32,
    /// K-index from peer's latest receipt.
    pub k_latest: u64,
    /// RCF orbit identity from peer's latest receipt.
    pub rcf_identity: [u8; 32],
    /// T_k Q16.16 from peer's latest receipt.
    pub t_k_q1616: u32,
    /// Per-entity sigma_enc from peer's latest receipt.
    pub sigma_enc: u32,
    /// Our K-index when we last received a receipt from this peer.
    pub last_seen_k: u64,
    /// Discontinuity flag from peer's latest receipt.
    pub disc_status: u8,
}

impl PeerState {
    /// Build PeerState from a received MeshReceipt.
    pub fn from_receipt(receipt: &MeshReceipt, our_k: u64) -> Self {
        Self {
            entity_id: receipt.entity_id,
            k_latest: receipt.k_index,
            rcf_identity: receipt.rcf_identity,
            t_k_q1616: receipt.t_k_q1616,
            sigma_enc: receipt.sigma_enc,
            last_seen_k: our_k,
            disc_status: receipt.disc_flag,
        }
    }
}

// ─── Divergence Proxy ──────────────────────────────────────────────────

/// Γ_ij² proxy: RCF hash Hamming distance as rational approximation.
///
/// Two entities with identical state have identical rcf_identity (0 distance).
/// Two diverged entities have different bytes (positive distance).
/// Returns a rational in [0, 1] representing structural divergence.
///
/// This avoids transmitting full Δ matrices in the broadcast loop.
/// Full Δ transmission is only needed for state sync (separate RPC).
///
/// Register: D.SAMN.2 (divergence calculation proxy).
pub fn gamma_sq_proxy(our_rcf: &[u8; 32], peer_rcf: &[u8; 32]) -> Q {
    let hamming: u32 = our_rcf
        .iter()
        .zip(peer_rcf.iter())
        .map(|(a, b)| (a ^ b).count_ones())
        .sum();
    Q::new(BigInt::from(hamming), BigInt::from(256u32))
}

// ─── Xi' Gate (Coherence Alignment) ────────────────────────────────────

/// Xi' gate: coherence alignment proxy from receipt data.
///
/// Combines sigma_enc alignment (gradient direction proxy) with
/// K-index lag cost (temporal relevance decay).
///
/// Returns a value in [0, 1]. Caller checks if result > lambda.
///
/// Register: T.SAMN.6b (substrate morphism proxy).
pub fn xi_gate(our_sigma_enc: u32, our_k: u64, peer: &PeerState) -> Q {
    let sigma_i = Q::new(BigInt::from(our_sigma_enc as i64), BigInt::from(u32::MAX as i64));
    let sigma_j = Q::new(BigInt::from(peer.sigma_enc as i64), BigInt::from(u32::MAX as i64));

    // cos_align = 1 - |σ_i - σ_j| / max(σ_i, σ_j, ε)
    let diff = (&sigma_i - &sigma_j).abs();
    let max_s = if sigma_i >= sigma_j {
        sigma_i.clone()
    } else {
        sigma_j.clone()
    };
    let cos_align = if max_s.is_zero() {
        Q::zero() // Both zero: newly created/restarted peers — no alignment data
    } else {
        Q::one() - &diff / &max_s
    };

    // K-index lag cost: exp(-|k_gap|) via 20-term locked Taylor
    let k_gap = if peer.k_latest > our_k {
        peer.k_latest - our_k
    } else {
        our_k - peer.k_latest
    };
    let x = -qi(k_gap as i64);
    let mag_correction = constants::locked_rational_exp_mesh(&x);

    &cos_align * &mag_correction
}

// ─── Sluice Weight ω_ij ───────────────────────────────────────────────

/// Compute sluice weight ω_ij for a peer.
///
/// ω_ij = exp(-(α_P·P_j + α_Γ·Γ_ij² + α_K·K_S^{-1}) / τ_lag)
///
/// Phase 2.0: P_j (paradox magnitude) = 0 (no CTL yet).
/// Γ_ij² from gamma_sq_proxy (RCF Hamming distance).
/// K_S^{-1} from K-index lag.
///
/// Returns 0 if weight < ε_sluice (peer is sluice-gated).
///
/// Register: T.SAMN.2 (entropy sluicing), D.SAIOS.1.
pub fn sluice_weight(
    peer: &PeerState,
    our_k: u64,
    our_rcf: &[u8; 32],
    alpha_p: &Q,
    alpha_gamma: &Q,
    alpha_k: &Q,
    tau_lag: &Q,
    epsilon_sluice: &Q,
) -> Q {
    let p_j = Q::zero(); // Phase 2.0: no paradox magnitude

    let gamma = gamma_sq_proxy(our_rcf, &peer.rcf_identity);

    let k_lag = our_k.saturating_sub(peer.last_seen_k);
    let k_s_inv = if k_lag == 0 {
        Q::zero()
    } else {
        Q::new(BigInt::from(1), BigInt::from(k_lag))
    };

    let exponent = -(alpha_p * &p_j + alpha_gamma * &gamma + alpha_k * &k_s_inv) / tau_lag;

    let w = constants::locked_rational_exp_mesh(&exponent);
    if &w < epsilon_sluice {
        Q::zero()
    } else {
        w
    }
}

// ─── K-Gate Majority Check ─────────────────────────────────────────────

/// K-Gate: weighted majority vote to advance K.
///
/// K advances from k to k+1 iff Σ_maj = Σ_{i: LOCKED} ω_i > 0.5.
///
/// Single entity (empty peers): always advances (Phase 1 compatibility).
///
/// Register: CC.SAMN.3 (majority K-gate consensus).
pub fn k_gate_advance(
    peers: &[PeerState],
    our_k: u64,
    our_rcf: &[u8; 32],
    alpha_p: &Q,
    alpha_gamma: &Q,
    alpha_k: &Q,
    tau_lag: &Q,
    epsilon_sluice: &Q,
) -> bool {
    if peers.is_empty() {
        return true; // Single entity: always advance
    }

    let omega_sum: Q = peers
        .iter()
        .map(|p| {
            sluice_weight(p, our_k, our_rcf, alpha_p, alpha_gamma, alpha_k, tau_lag, epsilon_sluice)
        })
        .sum();

    omega_sum > q(1, 2)
}

// ─── Wire Format ───────────────────────────────────────────────────────

/// Wire format for MeshReceipt broadcast.
///
/// The receipt is serialized as a fixed-size frame for TCP transmission.
/// Schema version prefix allows future format evolution.
///
/// Format: [schema_version: u8][receipt_hash: 32][rcf_identity: 32]
///         [t_k_q1616: 4][entity_id: 4][k_index: 8][parent_hash: 16]
///         [disc_flag: 1][sigma_enc: 4][sluice_state: 1]
///         [gap_t_k_numer: 8][gap_t_k_denom: 8][t_k_numer: 8][t_k_denom: 8]
/// Total: 1 + 32 + 32 + 4 + 4 + 8 + 16 + 1 + 4 + 1 + 8 + 8 + 8 + 8 = 135 bytes
pub const WIRE_SIZE: usize = 135;

/// Serialize a MeshReceipt to wire format.
pub fn receipt_to_wire(r: &MeshReceipt) -> [u8; WIRE_SIZE] {
    let mut buf = [0u8; WIRE_SIZE];
    let mut off = 0;

    buf[off] = 0x03; // schema v3
    off += 1;
    buf[off..off + 32].copy_from_slice(&r.receipt_hash);
    off += 32;
    buf[off..off + 32].copy_from_slice(&r.rcf_identity);
    off += 32;
    buf[off..off + 4].copy_from_slice(&r.t_k_q1616.to_be_bytes());
    off += 4;
    buf[off..off + 4].copy_from_slice(&r.entity_id.to_be_bytes());
    off += 4;
    buf[off..off + 8].copy_from_slice(&r.k_index.to_be_bytes());
    off += 8;
    buf[off..off + 16].copy_from_slice(&r.parent_hash);
    off += 16;
    buf[off] = r.disc_flag;
    off += 1;
    buf[off..off + 4].copy_from_slice(&r.sigma_enc.to_be_bytes());
    off += 4;
    buf[off] = r.sluice_state;
    off += 1;
    buf[off..off + 8].copy_from_slice(&r.gap_t_k_numer.to_be_bytes());
    off += 8;
    buf[off..off + 8].copy_from_slice(&r.gap_t_k_denom.to_be_bytes());
    off += 8;
    buf[off..off + 8].copy_from_slice(&r.t_k_numer.to_be_bytes());
    off += 8;
    buf[off..off + 8].copy_from_slice(&r.t_k_denom.to_be_bytes());
    buf
}

/// Deserialize a MeshReceipt from wire format.
/// Returns None if schema version doesn't match.
pub fn receipt_from_wire(buf: &[u8; WIRE_SIZE]) -> Option<MeshReceipt> {
    if buf[0] != 0x03 {
        return None; // Wrong schema version
    }
    let mut off = 1;

    let mut receipt_hash = [0u8; 32];
    receipt_hash.copy_from_slice(&buf[off..off + 32]);
    off += 32;

    let mut rcf_identity = [0u8; 32];
    rcf_identity.copy_from_slice(&buf[off..off + 32]);
    off += 32;

    let t_k_q1616 = u32::from_be_bytes(buf[off..off + 4].try_into().unwrap());
    off += 4;
    let entity_id = u32::from_be_bytes(buf[off..off + 4].try_into().unwrap());
    off += 4;
    let k_index = u64::from_be_bytes(buf[off..off + 8].try_into().unwrap());
    off += 8;

    let mut parent_hash = [0u8; 16];
    parent_hash.copy_from_slice(&buf[off..off + 16]);
    off += 16;

    let disc_flag = buf[off];
    off += 1;
    let sigma_enc = u32::from_be_bytes(buf[off..off + 4].try_into().unwrap());
    off += 4;
    let sluice_state = buf[off];
    off += 1;
    let gap_t_k_numer = i64::from_be_bytes(buf[off..off + 8].try_into().unwrap());
    off += 8;
    let gap_t_k_denom = u64::from_be_bytes(buf[off..off + 8].try_into().unwrap());
    off += 8;
    let t_k_numer = i64::from_be_bytes(buf[off..off + 8].try_into().unwrap());
    off += 8;
    let t_k_denom = u64::from_be_bytes(buf[off..off + 8].try_into().unwrap());

    Some(MeshReceipt {
        rcf_identity,
        t_k_q1616,
        entity_id,
        k_index,
        parent_hash,
        disc_flag,
        receipt_hash,
        sigma_enc,
        sluice_state,
        gap_t_k_numer,
        gap_t_k_denom,
        t_k_numer,
        t_k_denom,
        timestamp_ns: 0, // Not transmitted — local only
        telemetry: crate::ledger::ChronoTelemetry::unattached(),
        thought: crate::ledger::ThoughtTelemetry::unattached(),
        dimensional: crate::ledger::DimensionalTelemetry::unattached(),
    })
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::constants::DISC_NORMAL;

    #[test]
    fn test_gamma_sq_proxy_identical() {
        let rcf = [0xAA; 32];
        let g = gamma_sq_proxy(&rcf, &rcf);
        assert_eq!(g, Q::zero(), "Identical RCF identities must have zero divergence");
    }

    #[test]
    fn test_gamma_sq_proxy_different() {
        let a = [0x00; 32];
        let b = [0xFF; 32];
        let g = gamma_sq_proxy(&a, &b);
        assert_eq!(g, Q::one(), "Maximally different must have divergence = 1");
    }

    #[test]
    fn test_gamma_sq_proxy_single_bit() {
        let a = [0x00; 32];
        let mut b = [0x00; 32];
        b[0] = 0x01; // 1 bit different
        let g = gamma_sq_proxy(&a, &b);
        assert_eq!(g, q(1, 256), "Single bit difference = 1/256");
    }

    #[test]
    fn test_xi_gate_zero_for_new_peer() {
        let peer = PeerState {
            entity_id: 2,
            k_latest: 0,
            rcf_identity: [0; 32],
            t_k_q1616: 0,
            sigma_enc: 0,
            last_seen_k: 0,
            disc_status: 0,
        };
        let result = xi_gate(0, 100, &peer);
        assert_eq!(result, Q::zero(), "Newly created/restarted peer with sigma_enc=0 must return 0");
    }

    #[test]
    fn test_xi_gate_positive_for_aligned_peer() {
        let peer = PeerState {
            entity_id: 2,
            k_latest: 100,
            rcf_identity: [0; 32],
            t_k_q1616: 1000,
            sigma_enc: 1000,
            last_seen_k: 100,
            disc_status: 0,
        };
        let result = xi_gate(1000, 100, &peer);
        assert!(result > Q::zero(), "Aligned peer must have positive xi_gate");
    }

    #[test]
    fn test_sluice_weight_zero_for_stale_peer() {
        let peer = PeerState {
            entity_id: 2,
            k_latest: 1,
            rcf_identity: [0xFF; 32], // maximally diverged
            t_k_q1616: 0,
            sigma_enc: 0,
            last_seen_k: 0, // 200 K-steps stale
            disc_status: 0,
        };
        let w = sluice_weight(
            &peer, 200, &[0x00; 32],
            &q(1, 1), &q(1, 1), &q(1, 1),
            &q(1, 100), &q(1, 1000),
        );
        assert_eq!(w, Q::zero(), "Maximally diverged + stale peer must be sluice-gated");
    }

    #[test]
    fn test_sluice_weight_positive_for_close_peer() {
        let our_rcf = [0x42; 32];
        let peer = PeerState {
            entity_id: 2,
            k_latest: 100,
            rcf_identity: [0x42; 32], // identical RCF
            t_k_q1616: 1000,
            sigma_enc: 500,
            last_seen_k: 100, // seen at current K — no lag
            disc_status: 0,
        };
        // With identical RCF (gamma=0) and no K-lag (k_s_inv=0),
        // exponent = 0, exp(0) = 1, which is > epsilon_sluice
        let w = sluice_weight(
            &peer, 100, &our_rcf,
            &q(1, 1), &q(1, 1), &q(1, 1),
            &q(1, 100), &q(1, 1000),
        );
        assert!(w > Q::zero(), "Close peer with identical RCF and no lag must have positive weight");
    }

    #[test]
    fn test_k_gate_advance_single_node() {
        assert!(
            k_gate_advance(
                &[], 100, &[0; 32],
                &q(1, 1), &q(1, 1), &q(1, 1),
                &q(1, 100), &q(1, 1000),
            ),
            "Single entity (no peers) must always advance"
        );
    }

    #[test]
    fn test_k_gate_advance_all_gated() {
        // All peers maximally diverged — all weights should be 0
        let peers: Vec<PeerState> = (0..10)
            .map(|i| PeerState {
                entity_id: i + 2,
                k_latest: 1,
                rcf_identity: [0xFF; 32],
                t_k_q1616: 0,
                sigma_enc: 0,
                last_seen_k: 0,
                disc_status: 0,
            })
            .collect();
        assert!(
            !k_gate_advance(
                &peers, 200, &[0x00; 32],
                &q(1, 1), &q(1, 1), &q(1, 1),
                &q(1, 100), &q(1, 1000),
            ),
            "All-gated peers must prevent K advance"
        );
    }

    #[test]
    fn test_wire_roundtrip() {
        let receipt = MeshReceipt {
            rcf_identity: [0x11; 32],
            t_k_q1616: 42000,
            entity_id: 7,
            k_index: 999,
            parent_hash: [0x22; 16],
            disc_flag: DISC_NORMAL,
            receipt_hash: [0x33; 32],
            sigma_enc: 12345,
            sluice_state: 0x01,
            gap_t_k_numer: 0,
            gap_t_k_denom: 1,
            t_k_numer: 3,
            t_k_denom: 7,
            timestamp_ns: 1234567890,
            telemetry: crate::ledger::ChronoTelemetry::unattached(),
            thought: crate::ledger::ThoughtTelemetry::unattached(),
            dimensional: crate::ledger::DimensionalTelemetry::unattached(),
        };

        let wire = receipt_to_wire(&receipt);
        assert_eq!(wire.len(), WIRE_SIZE);

        let decoded = receipt_from_wire(&wire).expect("decode must succeed");
        assert_eq!(decoded.rcf_identity, receipt.rcf_identity);
        assert_eq!(decoded.t_k_q1616, receipt.t_k_q1616);
        assert_eq!(decoded.entity_id, receipt.entity_id);
        assert_eq!(decoded.k_index, receipt.k_index);
        assert_eq!(decoded.parent_hash, receipt.parent_hash);
        assert_eq!(decoded.disc_flag, receipt.disc_flag);
        assert_eq!(decoded.receipt_hash, receipt.receipt_hash);
        assert_eq!(decoded.sigma_enc, receipt.sigma_enc);
        assert_eq!(decoded.sluice_state, receipt.sluice_state);
        assert_eq!(decoded.gap_t_k_numer, receipt.gap_t_k_numer);
        assert_eq!(decoded.gap_t_k_denom, receipt.gap_t_k_denom);
        assert_eq!(decoded.t_k_numer, receipt.t_k_numer);
        assert_eq!(decoded.t_k_denom, receipt.t_k_denom);
        // timestamp_ns is NOT transmitted
        assert_eq!(decoded.timestamp_ns, 0);
    }

    #[test]
    fn test_wire_wrong_schema_rejected() {
        let mut buf = [0u8; WIRE_SIZE];
        buf[0] = 0x01; // wrong schema
        assert!(receipt_from_wire(&buf).is_none());
    }
}
