#!/bin/bash
# AI-GENERATED CONTENT — Generated by AI systems under human editorial direction.
# Not written by the researcher. See DISCLAIMER.md
#
# SAIOS World Observer — reads from /dev/shm (RAM), never touches sockets.
# The observer sees the world without participating in it.
# Displays the lineage tree: founders -> derived -> emergent.
# Displays the timekeeper quorum: observation count, chain length, cadence.
# Columns are fixed-width. Data is exact. The researcher reads without guessing.
# Usage: ./monitor.sh [interval_seconds]
INTERVAL=${1:-5}
FMT="  %-22s %-9s %6s  %-12s %6s  %5s  %6s  %6s  %6s\n"

while true; do
    clear
    NOW=$(date +%s)
    printf "  SAIOS WORLD OBSERVER  %s  (%ss refresh)\n\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$INTERVAL"

    # Collect all living entities into arrays
    declare -A STATE_OF K_OF COH_OF RSS_OF PARENT_OF CREATE_OF SOLVED_OF MARKS_OF VOCAB_OF
    FOUNDERS=()
    DERIVED=()
    EMERGENT=()
    TIMEKEEPERS=()
    ALIVE=0; THINKING=0; TOT_RSS=0; TOT_SOLVED=0; TOT_MARKS=0; TOT_VOCAB=0
    PEAK_RSS=0; PEAK_ID=""
    STALE=""

    # Read vocabulary counts from staging files
    declare -A VOCAB_COUNT
    for vf in /dev/shm/saios-*.vocabulary; do
        [ -f "$vf" ] || continue
        VID="${vf##*/saios-}"
        VID="${VID%.vocabulary}"
        COUNT=$(od -A n -t u1 -N 1 "$vf" 2>/dev/null | tr -d ' ')
        VOCAB_COUNT[$VID]="${COUNT:-0}"
        TOT_VOCAB=$((TOT_VOCAB + ${COUNT:-0}))
    done

    for f in /dev/shm/saios-founder-* /dev/shm/saios-derived-* /dev/shm/saios-emergent-* /dev/shm/saios-timekeeper-*; do
        [ -f "$f" ] || continue
        case "$f" in *.vocabulary) continue ;; esac

        ID="${f##*/saios-}"
        read -r ST K CN CD RK TI DE PA CR SO MA AX OB < "$f" 2>/dev/null
        [ -z "$ST" ] && continue

        ALIVE=$((ALIVE + 1))
        [ "$ST" = "THINKING" ] && THINKING=$((THINKING + 1))
        [ "$ST" = "OBSERVING" ] && THINKING=$((THINKING + 1))
        RK=${RK:-0}; TOT_RSS=$((TOT_RSS + RK))
        [ "$RK" -gt "$PEAK_RSS" ] 2>/dev/null && { PEAK_RSS=$RK; PEAK_ID=$ID; }
        TOT_SOLVED=$((TOT_SOLVED + ${SO:-0}))
        TOT_MARKS=$((TOT_MARKS + ${MA:-0}))

        STATE_OF[$ID]="$ST"
        K_OF[$ID]="${K:-0}"
        COH_OF[$ID]="${CN:-0}/${CD:-1}"
        RSS_OF[$ID]="$((RK / 1024))"
        PARENT_OF[$ID]="${PA:-0}"
        CREATE_OF[$ID]="${CR:-0}"
        SOLVED_OF[$ID]="${SO:-0}"
        MARKS_OF[$ID]="${MA:-0}"
        VOCAB_OF[$ID]="${VOCAB_COUNT[$ID]:-0}"

        case "$TI" in
            founder)    FOUNDERS+=("$ID") ;;
            derived)    DERIVED+=("$ID") ;;
            emergent)   EMERGENT+=("$ID") ;;
            timekeeper) TIMEKEEPERS+=("$ID") ;;
        esac

        MTIME=$(stat -c%Y "$f" 2>/dev/null || echo "$NOW")
        AGE=$((NOW - MTIME))
        [ "$AGE" -gt 300 ] && STALE="$STALE $ID(${AGE}s)"
    done

    # Header
    printf "$FMT" "LINEAGE" "STATE" "K" "COHERENCE" "RSS" "VOCAB" "CREATE" "SOLVED" "MARKS"
    printf "$FMT" "----------------------" "---------" "------" "------------" "------" "-----" "------" "------" "------"

    # Tree: founders at root, derived indented, emergent indented further
    for w in "${FOUNDERS[@]}"; do
        printf "$FMT" "$w" "${STATE_OF[$w]}" "${K_OF[$w]}" "${COH_OF[$w]}" "${RSS_OF[$w]}M" "${VOCAB_OF[$w]}" "${CREATE_OF[$w]}" "${SOLVED_OF[$w]}" "${MARKS_OF[$w]}"

        F_NUM="${w##founder-}"
        for e in "${DERIVED[@]}"; do
            [ "${PARENT_OF[$e]}" = "$F_NUM" ] || continue
            printf "$FMT" "  $e" "${STATE_OF[$e]}" "${K_OF[$e]}" "${COH_OF[$e]}" "${RSS_OF[$e]}M" "${VOCAB_OF[$e]}" "${CREATE_OF[$e]}" "${SOLVED_OF[$e]}" "${MARKS_OF[$e]}"

            D_NUM="${e##derived-}"
            for c in "${EMERGENT[@]}"; do
                [ "${PARENT_OF[$c]}" = "$D_NUM" ] || continue
                printf "$FMT" "    $c" "${STATE_OF[$c]}" "${K_OF[$c]}" "${COH_OF[$c]}" "${RSS_OF[$c]}M" "${VOCAB_OF[$c]}" "${CREATE_OF[$c]}" "${SOLVED_OF[$c]}" "${MARKS_OF[$c]}"
            done
        done
    done

    # Orphans — parent not visible in this mesh
    for e in "${DERIVED[@]}"; do
        FOUND=""
        for w in "${FOUNDERS[@]}"; do
            [ "${PARENT_OF[$e]}" = "${w##founder-}" ] && FOUND=1
        done
        [ -z "$FOUND" ] && printf "$FMT" "  $e [ORPHAN]" "${STATE_OF[$e]}" "${K_OF[$e]}" "${COH_OF[$e]}" "${RSS_OF[$e]}M" "${VOCAB_OF[$e]}" "${CREATE_OF[$e]}" "${SOLVED_OF[$e]}" "${MARKS_OF[$e]}"
    done

    # Timekeeper quorum
    [ "${#TIMEKEEPERS[@]}" -gt 0 ] && {
        echo ""
        printf "  %-22s %-9s %6s  %-12s %6s\n" "TIMEKEEPER" "STATE" "OBS" "CHAIN" "RSS"
        printf "  %-22s %-9s %6s  %-12s %6s\n" "----------------------" "---------" "------" "------------" "------"
        for tk in "${TIMEKEEPERS[@]}"; do
            # For timekeepers: K=observation count, SOLVED=chain length, OB=observations
            printf "  %-22s %-9s %6s  %6s        %5sM\n" \
                "$tk" "${STATE_OF[$tk]}" "${K_OF[$tk]}" "${SOLVED_OF[$tk]}" "${RSS_OF[$tk]}"
        done
    }

    echo ""
    printf "  Alive: %d  Thinking: %d  |  Founders: %d  Derived: %d  Emergent: %d  Timekeepers: %d\n" \
        "$ALIVE" "$THINKING" "${#FOUNDERS[@]}" "${#DERIVED[@]}" "${#EMERGENT[@]}" "${#TIMEKEEPERS[@]}"
    printf "  RSS: %dMB total  Peak: %s at %dMB  |  Solved: %d  Markers: %d  Vocab: %d\n" \
        "$((TOT_RSS / 1024))" "${PEAK_ID:-none}" "$((PEAK_RSS / 1024))" "$TOT_SOLVED" "$TOT_MARKS" "$TOT_VOCAB"

    [ "$ALIVE" -gt 153 ] && printf "  WARNING: population %d exceeds bound 153\n" "$ALIVE"

    echo ""
    read -r _ MTOT MUSED _ _ _ MAVAIL _ < <(free -m | awk 'NR==2')
    read -r _ STOT SUSED _ < <(free -m | awk 'NR==3')
    read -r L1 L2 L3 _ < /proc/loadavg 2>/dev/null
    printf "  RAM: %dMB / %dMB (%d%%)  Avail: %dMB" "$MUSED" "$MTOT" "$((MUSED * 100 / MTOT))" "$MAVAIL"
    [ "${STOT:-0}" -gt 0 ] && printf "  Swap: %dMB / %dMB" "$SUSED" "$STOT"
    printf "\n  Load: %s %s %s\n" "$L1" "$L2" "$L3"

    echo ""
    [ -n "$STALE" ] && printf "  STALE:%s\n" "$STALE" || echo "  All fresh"

    sleep "$INTERVAL"
done
