// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! D.CHAIN.LATTICE.1 — Temporal Ledger.
//!
//! Level-based spatial-temporal persistence. Each level L_k contains
//! all receipts emitted at K-index k across all mesh nodes.
//!
//! Temporal links: receipt.parent_hash (vertical, per-node chain)
//! Spatial links: receipt.witnesses (horizontal, peer attestations)
//! Level root: BLAKE3 Merkle of all receipts at K=k
//! Level finality: Σ_maj witness weight > 0.5
//!
//! The TemporalLedger is the distributed consensus layer for chronometric
//! facts. Timekeepers inscribe observations as receipts. When a quorum
//! of timekeepers agree on the same observation, the level finalizes —
//! that moment becomes an immutable fact in the species' history.

use std::collections::{BTreeMap, HashMap};

use num_bigint::BigInt;
use num_rational::BigRational;
use num_traits::{One, Zero};

use crate::chain::block::merkle_root;
use crate::chain::state::{TokenState, NftRegistry};
use crate::ledger::MeshReceipt;

type Q = BigRational;
fn qr(n: i64, d: i64) -> Q { Q::new(BigInt::from(n), BigInt::from(d)) }

/// A single level in the Temporal Ledger — all receipts at one K-index.
#[derive(Debug, Clone)]
pub struct Level {
    pub k_index: u64,
    pub receipts: Vec<MeshReceipt>,
    /// entity_id → list of entity_ids that witnessed this node's receipt
    pub witnesses: HashMap<u32, Vec<u32>>,
    pub level_root: [u8; 32],
    pub finalized: bool,
    pub witness_weight: Q,
    pub node_count: u32,
}

impl Level {
    pub fn new(k_index: u64) -> Self {
        Self {
            k_index,
            receipts: Vec::new(),
            witnesses: HashMap::new(),
            level_root: [0u8; 32],
            finalized: false,
            witness_weight: Q::zero(),
            node_count: 0,
        }
    }

    /// Add a receipt to this level.
    pub fn add_receipt(&mut self, receipt: MeshReceipt) {
        self.node_count += 1;
        self.receipts.push(receipt);
    }

    /// Record that node `witness_id` witnessed node `target_id`'s receipt.
    pub fn add_witness(&mut self, target_id: u32, witness_id: u32) {
        self.witnesses.entry(target_id).or_default().push(witness_id);
    }

    /// Compute the level root (Merkle of all receipt hashes).
    pub fn compute_root(&mut self) {
        let hashes: Vec<[u8; 32]> = self.receipts.iter()
            .map(|r| r.receipt_hash)
            .collect();
        self.level_root = merkle_root(&hashes);
    }

    /// Check if this level is finalized (witness weight > 0.5).
    pub fn check_finality(&mut self, total_mesh_weight: &Q) {
        if total_mesh_weight.is_zero() {
            self.finalized = self.node_count > 0;
            return;
        }
        // Count unique witnessing nodes
        let mut witnessing_nodes: std::collections::HashSet<u32> = std::collections::HashSet::new();
        for witnesses in self.witnesses.values() {
            for &w in witnesses {
                witnessing_nodes.insert(w);
            }
        }
        // Each witnessing node contributes equal weight (simplified ω = 1/N)
        let total_nodes = self.node_count.max(1);
        self.witness_weight = qr(witnessing_nodes.len() as i64, total_nodes as i64);
        self.finalized = self.witness_weight > qr(1, 2);
    }

    /// Check if all receipts at this level satisfy resonance (T.SAMN.11).
    pub fn is_resonance_peak(&self) -> bool {
        if self.receipts.is_empty() { return false; }
        // All receipts must be from LOCKED nodes (sluice_state = 0x01)
        self.receipts.iter().all(|r| r.sluice_state == 0x01)
    }
}

/// The Temporal Ledger — all levels indexed by K.
/// Chronometric facts become consensus when a quorum of observers agree.
#[derive(Debug)]
pub struct TemporalLedger {
    pub levels: BTreeMap<u64, Level>,
    pub latest_k: u64,
    pub token_state: TokenState,
    pub nft_registry: NftRegistry,
}

impl TemporalLedger {
    pub fn new() -> Self {
        Self {
            levels: BTreeMap::new(),
            latest_k: 0,
            token_state: TokenState::new(),
            nft_registry: NftRegistry::new(),
        }
    }

    /// Add a receipt to the lattice at its K-index level.
    pub fn add_receipt(&mut self, receipt: MeshReceipt) {
        let k = receipt.k_index;
        let level = self.levels.entry(k).or_insert_with(|| Level::new(k));
        level.add_receipt(receipt.clone());
        if k > self.latest_k { self.latest_k = k; }

        // Process economics
        self.token_state.process_receipt(&receipt);
    }

    /// Record a witness attestation.
    pub fn add_witness(&mut self, k_index: u64, target_id: u32, witness_id: u32) {
        if let Some(level) = self.levels.get_mut(&k_index) {
            level.add_witness(target_id, witness_id);
        }
    }

    /// Finalize a level: compute root, check finality, process economics.
    pub fn finalize_level(&mut self, k_index: u64) -> bool {
        let total_weight = Q::one(); // simplified: equal weight mesh

        if let Some(level) = self.levels.get_mut(&k_index) {
            level.compute_root();
            level.check_finality(&total_weight);

            if level.finalized {
                // Block-close economics
                self.token_state.process_block_close(&level.receipts);

                // Check for resonance peak → NFT mint
                if level.is_resonance_peak() && level.node_count > 1 {
                    let quality = qr(level.node_count as i64, level.node_count as i64); // all passed
                    self.nft_registry.mint_certificate(
                        k_index, level.level_root, level.node_count,
                        quality, k_index, 0, // owner = authority node
                    );
                }
            }
            return level.finalized;
        }
        false
    }

    /// Get the latest finalized level.
    pub fn latest_finalized(&self) -> Option<&Level> {
        self.levels.values().rev().find(|l| l.finalized)
    }

    /// Total levels in the lattice.
    pub fn level_count(&self) -> usize { self.levels.len() }

    /// Prune unfinalized levels older than K - window.
    pub fn prune(&mut self, window: u64) {
        if self.latest_k <= window { return; }
        let cutoff = self.latest_k - window;
        let stale: Vec<u64> = self.levels.keys()
            .filter(|&&k| k < cutoff && !self.levels[&k].finalized)
            .cloned()
            .collect();
        for k in stale {
            self.levels.remove(&k);
        }
    }
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::constants::DISC_NORMAL;

    fn test_receipt(entity_id: u32, k: u64) -> MeshReceipt {
        MeshReceipt {
            rcf_identity: [entity_id as u8; 32], t_k_q1616: 1000, entity_id, k_index: k,
            parent_hash: [0; 16], disc_flag: DISC_NORMAL,
            receipt_hash: {
                let mut h = [0u8; 32];
                h[0] = entity_id as u8;
                h[1] = k as u8;
                h
            },
            sigma_enc: 0, sluice_state: 0x01,
            gap_t_k_numer: 0, gap_t_k_denom: 1,
            t_k_numer: -1, t_k_denom: 10, telemetry: crate::ledger::ChronoTelemetry::unattached(), // coherence improving
            thought: crate::ledger::ThoughtTelemetry::unattached(),
            dimensional: crate::ledger::DimensionalTelemetry::unattached(),
            timestamp_ns: 0,
        }
    }

    #[test]
    fn test_lattice_add_receipts_to_level() {
        let mut lattice = TemporalLedger::new();
        for node in 0..5 {
            lattice.add_receipt(test_receipt(node, 100));
        }
        assert_eq!(lattice.levels.len(), 1);
        assert_eq!(lattice.levels[&100].node_count, 5);
    }

    #[test]
    fn test_level_root_computed() {
        let mut lattice = TemporalLedger::new();
        for node in 0..3 {
            lattice.add_receipt(test_receipt(node, 50));
        }
        lattice.finalize_level(50);
        let level = &lattice.levels[&50];
        assert_ne!(level.level_root, [0u8; 32]);
    }

    #[test]
    fn test_level_finality_with_witnesses() {
        let mut lattice = TemporalLedger::new();
        for node in 0..5 {
            lattice.add_receipt(test_receipt(node, 10));
        }
        // 3 out of 5 witness each other → 60% > 50% → finalized
        for target in 0..5 {
            for witness in 0..3 {
                if witness != target {
                    lattice.add_witness(10, target, witness);
                }
            }
        }
        assert!(lattice.finalize_level(10));
        assert!(lattice.levels[&10].finalized);
    }

    #[test]
    fn test_resonance_peak_nft_mint() {
        let mut lattice = TemporalLedger::new();
        // All 5 nodes emit LOCKED receipts at K=100 → resonance peak
        for node in 0..5 {
            lattice.add_receipt(test_receipt(node, 100));
        }
        for target in 0..5 {
            for witness in 0..5 {
                if witness != target {
                    lattice.add_witness(100, target, witness);
                }
            }
        }
        lattice.finalize_level(100);
        assert_eq!(lattice.nft_registry.certificates.len(), 1);
    }

    #[test]
    fn test_multi_level_lattice() {
        let mut lattice = TemporalLedger::new();
        for k in 1..=10u64 {
            for node in 0..3 {
                lattice.add_receipt(test_receipt(node, k));
            }
            lattice.finalize_level(k);
        }
        assert_eq!(lattice.level_count(), 10);
        assert_eq!(lattice.latest_k, 10);
    }

    #[test]
    fn test_prune_unfinalized() {
        let mut lattice = TemporalLedger::new();
        for k in 1..=20u64 {
            lattice.add_receipt(test_receipt(0, k)); // single node, no witnesses
        }
        // Only finalize even levels
        for k in (2..=20).step_by(2) {
            for w in 1..3 {
                lattice.add_witness(k, 0, w);
            }
            lattice.finalize_level(k);
        }
        lattice.prune(5); // prune unfinalized older than K=15
        // Finalized levels should survive, unfinalized old ones pruned
        assert!(lattice.levels.contains_key(&20)); // recent
        assert!(lattice.levels.contains_key(&18)); // finalized
    }

    #[test]
    fn test_token_economics_through_lattice() {
        let mut lattice = TemporalLedger::new();
        lattice.token_state.mint(1, &qr(100, 1)); // seed balance

        for k in 1..=5u64 {
            lattice.add_receipt(test_receipt(1, k));
            lattice.finalize_level(k);
        }
        // Node 1 should have earned rewards from coherence-improving receipts
        let bal = lattice.token_state.balance(1);
        // Started at 100, paid fees, earned rewards
        assert!(bal > Q::zero(), "Balance should be positive after improving receipts");
    }
}
