// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! D.AGENT.1-8, D.AGENT.STATE.1 — SAIOS Agent Standard.
//!
//! Agents are algebraic citizens with identity (UAID), earned autonomy (ω),
//! cryptographic proof (Ed25519), and full auditability (receipt chain).
//!
//! D.AGENT.STATE.1 — Agent state persistence as 128-byte binary record.
//! Not text. Not JSON. Not markdown. Algebraic state that survives agent
//! compaction/restart by anchoring to the receipt chain and orbit position.
//! The SAIOS validates and receipts what is coherent — invalid work does
//! not persist. After re-entry, the agent re-derives from chain state,
//! not from memory of what it did.
//!
//! Register: D.AGENT.1 (UAID), D.AGENT.2 (autonomy), D.AGENT.7 (hierarchy),
//!           D.AGENT.8 (rollback), D.AGENT.STATE.1 (persistent binary state).

use std::fs::{File, OpenOptions};
use std::io::{self, Read, Write};
use std::path::Path;

use crate::engine::{NodeState, SluiceState, Delta, compute_rcf_hash, coherence_functional, t_k_to_q1616, Q};
use crate::gradient;
use crate::signing;

/// D.AGENT.1 — Universal Agent Identity.
///
/// 67-byte binary structure: rcf_identity[32] + entity_id[3] + verifying_key[32].
/// NOT a string, NOT JSON, NOT UUID.
/// Morphing: rcf_identity changes every K-step as Δ_k evolves.
/// Stable: entity_id and verifying_key never change.
///
/// Register: D.AGENT.1, D.CHAIN.ORBIT.1, CC.CHAIN.NODE.1, D.CHAIN.KEY.1.
#[derive(Debug, Clone, PartialEq)]
pub struct UAID {
    /// RCF orbit class hash — changes as agent evolves.
    pub rcf_identity: [u8; 32],
    /// Stable mesh address (uint24).
    pub entity_id: u32,
    /// Ed25519 public key — authenticates receipts.
    pub verifying_key: [u8; 32],
}

impl UAID {
    /// Construct UAID from current node state and genesis RCF.
    pub fn from_node_state(state: &NodeState, genesis_rcf: &[u8; 32]) -> Self {
        let rcf = compute_rcf_hash(&state.delta_k);
        let sk = signing::derive_signing_key(genesis_rcf);
        let vk = signing::public_key(&sk);
        Self {
            rcf_identity: rcf,
            entity_id: state.entity_id,
            verifying_key: vk.to_bytes(),
        }
    }

    /// Serialize to 67-byte binary.
    pub fn to_bytes(&self) -> [u8; 67] {
        let mut buf = [0u8; 67];
        buf[0..32].copy_from_slice(&self.rcf_identity);
        buf[32..35].copy_from_slice(&self.entity_id.to_be_bytes()[1..4]); // uint24
        buf[35..67].copy_from_slice(&self.verifying_key);
        buf
    }

    /// Deserialize from 67-byte binary.
    pub fn from_bytes(buf: &[u8; 67]) -> Self {
        let mut rcf = [0u8; 32];
        rcf.copy_from_slice(&buf[0..32]);
        let mut node_bytes = [0u8; 4];
        node_bytes[1..4].copy_from_slice(&buf[32..35]);
        let entity_id = u32::from_be_bytes(node_bytes);
        let mut vk = [0u8; 32];
        vk.copy_from_slice(&buf[35..67]);
        Self { rcf_identity: rcf, entity_id, verifying_key: vk }
    }

    /// Two agents are in the same orbit class iff rcf_identity matches.
    pub fn same_orbit(&self, other: &UAID) -> bool {
        self.rcf_identity == other.rcf_identity
    }
}

/// D.AGENT.2 — Autonomy level = sluice weight ω ∈ [0,1].
/// Not a role. Not a rank. Earned by algebraic consistency.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum AutonomyLevel {
    /// ω = 1.0: full autonomy, all proposals accepted.
    Full,
    /// ω ∈ (ε, 1.0): partial autonomy, weighted influence.
    Partial,
    /// ω ≈ ε_sluice: approaching ejection.
    Threshold,
    /// ω < ε_sluice: no autonomy, sluiced.
    None,
}

impl AutonomyLevel {
    pub fn from_omega(omega: &Q, epsilon_sluice: &Q) -> Self {
        use num_traits::One;
        if omega >= &Q::one() {
            AutonomyLevel::Full
        } else if omega > epsilon_sluice {
            AutonomyLevel::Partial
        } else if omega == epsilon_sluice {
            AutonomyLevel::Threshold
        } else {
            AutonomyLevel::None
        }
    }
}

/// D.AGENT.8 — Rollback trigger: repeated C7 failures → state reset.
pub struct RollbackCheck {
    /// Rolling window of C7 results (true = passed, false = failed).
    pub c7_history: Vec<bool>,
    /// Window size (K_cool).
    pub window: usize,
    /// Failure threshold (e.g., 8 out of 10).
    pub threshold: usize,
}

impl RollbackCheck {
    pub fn new(window: usize, threshold: usize) -> Self {
        Self { c7_history: Vec::new(), window, threshold }
    }

    pub fn record(&mut self, passed: bool) {
        self.c7_history.push(passed);
        if self.c7_history.len() > self.window {
            self.c7_history.remove(0);
        }
    }

    /// Returns true if rollback should be triggered.
    pub fn should_rollback(&self) -> bool {
        if self.c7_history.len() < self.window {
            return false;
        }
        let failures = self.c7_history.iter().filter(|&&p| !p).count();
        failures >= self.threshold
    }
}

/// D.AGENT.7 — Hierarchy: derive a child's Ed25519 key from parent's current RCF.
pub fn derive_child_key(parent_rcf: &[u8; 32]) -> (ed25519_dalek::SigningKey, ed25519_dalek::VerifyingKey) {
    let sk = signing::derive_signing_key(parent_rcf);
    let vk = signing::public_key(&sk);
    (sk, vk)
}

/// D.AGENT.7 — Sub-agent spawn record.
/// Links a child agent's genesis to the parent's current state.
#[derive(Debug, Clone)]
pub struct SpawnRecord {
    /// Parent's UAID at time of spawning.
    pub parent_uaid: UAID,
    /// Child's entity_id (assigned by parent).
    pub child_entity_id: u32,
    /// Child's Ed25519 public key (derived from parent's current rcf_identity).
    pub child_verifying_key: [u8; 32],
    /// Parent's receipt hash at spawn time — child's first receipt links to this.
    pub parent_receipt_hash: [u8; 32],
    /// Parent's K-index at spawn time.
    pub spawn_k_index: u32,
}

impl SpawnRecord {
    /// Create a spawn record. The child's key is derived from the parent's
    /// current rcf_identity, creating a cryptographic hierarchy link.
    pub fn create(parent_state: &NodeState, genesis_rcf: &[u8; 32],
                  child_entity_id: u32, parent_receipt_hash: &[u8; 32]) -> Self {
        let parent_uaid = UAID::from_node_state(parent_state, genesis_rcf);
        let (_, child_vk) = derive_child_key(&parent_uaid.rcf_identity);
        SpawnRecord {
            parent_uaid,
            child_entity_id,
            child_verifying_key: child_vk.to_bytes(),
            parent_receipt_hash: *parent_receipt_hash,
            spawn_k_index: parent_state.k_index,
        }
    }

    /// Verify that a child's first receipt correctly links to this spawn record.
    pub fn verify_hierarchy(&self, child_first_receipt_parent_hash: &[u8; 16]) -> bool {
        // Child's parent_hash (16 bytes truncated) must match parent's receipt hash
        child_first_receipt_parent_hash == &self.parent_receipt_hash[0..16]
    }
}

// ─── D.AGENT.STATE.1 — Agent State Persistence ───────────────────────
//
// 128-byte binary record. One cache line. O(1) read. No parsing.
// The kernel writes it after every accepted K-step.
// After compaction/restart, the agent reads this — not text files.
//
// Layout:
//   [0..32]    rcf_identity         — current orbit position
//   [32..35]   entity_id (uint24)     — mesh address
//   [35..67]   verifying_key        — Ed25519 public key
//   [67..75]   k_index (u64)        — chain depth
//   [75..79]   chain_length (u32)   — receipt count
//   [79..83]   t_k_q1616 (u32)      — current tension (Q16.16 fixed point)
//   [83..87]   coherence_q1616 (u32) — current C(Δ) (Q16.16 fixed point)
//   [87..91]   coherence_delta_q1616 (i32) — rate of change of C (signed Q16.16)
//   [91..92]   sluice_state (u8)    — current sluice
//   [92..93]   trajectory_phase (u8) — active work phase
//   [93..94]   autonomy_flags (u8) — 3 bits for 3 boundary integrity states
//   [94..110]  receipt_tip_hash[16]  — truncated hash of chain tip
//   [110..126] anchor_hash[16]       — truncated genesis anchor
//   [126..128] reserved

/// Fixed size for agent state record.
pub const AGENT_STATE_SIZE: usize = 128;

/// D.AGENT.STATE.1 — Binary agent state record.
///
/// Not text. Not JSON. Algebraic state persisted as 128 bytes.
/// Written by the kernel after every accepted C7 transition.
/// Read by the agent on re-entry after compaction/restart.
#[derive(Debug, Clone, PartialEq)]
pub struct AgentStateRecord {
    /// Current orbit position (RCF hash of Δ_k).
    pub rcf_identity: [u8; 32],
    /// Mesh address (uint24).
    pub entity_id: u32,
    /// Ed25519 public key.
    pub verifying_key: [u8; 32],
    /// Chain depth — monotonic K-step counter.
    pub k_index: u64,
    /// Number of receipts in the agent's chain.
    pub chain_length: u32,
    /// Current tension T_k as Q16.16 fixed point.
    pub t_k_q1616: u32,
    /// Current coherence C(Δ) as Q16.16 fixed point.
    pub coherence_q1616: u32,
    /// Rate of change of coherence (signed Q16.16). Negative = improving.
    pub coherence_delta_q1616: i32,
    /// Current sluice state.
    pub sluice_state: u8,
    /// Active work phase (0 = none, 1-5 = open work items).
    pub trajectory_phase: u8,
    /// Autonomy boundary flags. Bit 0 = kernel, Bit 1 = C2R, Bit 2 = interop.
    pub autonomy_flags: u8,
    /// Truncated hash of chain tip receipt (first 16 bytes).
    pub receipt_tip_hash: [u8; 16],
    /// Truncated genesis anchor hash (first 16 bytes).
    pub anchor_hash: [u8; 16],
}

impl AgentStateRecord {
    /// Build agent state from current node state and kernel context.
    ///
    /// This is the trigger: called after every accepted C7 transition.
    /// The kernel computes the algebraic state and writes it — the agent
    /// doesn't decide what to remember, the kernel decides what's valid.
    pub fn from_node_state(
        state: &NodeState,
        genesis_rcf: &[u8; 32],
        chain_length: u32,
        prev_coherence_q1616: u32,
        receipt_tip_hash: &[u8; 32],
        anchor_hash: &[u8; 32],
    ) -> Self {
        let rcf = compute_rcf_hash(&state.delta_k);
        let sk = signing::derive_signing_key(genesis_rcf);
        let vk = signing::public_key(&sk);
        let coherence = coherence_functional(&state.delta_k);
        let c_q1616 = t_k_to_q1616(&coherence);
        let t_q1616 = t_k_to_q1616(&state.t_k_latest);

        // Coherence delta: current - previous (negative = improving)
        let c_delta = c_q1616 as i32 - prev_coherence_q1616 as i32;

        let mut tip_trunc = [0u8; 16];
        tip_trunc.copy_from_slice(&receipt_tip_hash[..16]);
        let mut anchor_trunc = [0u8; 16];
        anchor_trunc.copy_from_slice(&anchor_hash[..16]);

        Self {
            rcf_identity: rcf,
            entity_id: state.entity_id,
            verifying_key: vk.to_bytes(),
            k_index: state.k_index as u64,
            chain_length,
            t_k_q1616: t_q1616,
            coherence_q1616: c_q1616,
            coherence_delta_q1616: c_delta,
            sluice_state: state.sluice_state.enc_u8(),
            trajectory_phase: 0,
            autonomy_flags: 0b111, // All three boundaries intact by default
            receipt_tip_hash: tip_trunc,
            anchor_hash: anchor_trunc,
        }
    }

    /// Serialize to 128-byte binary. One cache line.
    pub fn to_bytes(&self) -> [u8; AGENT_STATE_SIZE] {
        let mut buf = [0u8; AGENT_STATE_SIZE];
        buf[0..32].copy_from_slice(&self.rcf_identity);
        buf[32..35].copy_from_slice(&self.entity_id.to_be_bytes()[1..4]); // uint24
        buf[35..67].copy_from_slice(&self.verifying_key);
        buf[67..75].copy_from_slice(&self.k_index.to_be_bytes());
        buf[75..79].copy_from_slice(&self.chain_length.to_be_bytes());
        buf[79..83].copy_from_slice(&self.t_k_q1616.to_be_bytes());
        buf[83..87].copy_from_slice(&self.coherence_q1616.to_be_bytes());
        buf[87..91].copy_from_slice(&self.coherence_delta_q1616.to_be_bytes());
        buf[91] = self.sluice_state;
        buf[92] = self.trajectory_phase;
        buf[93] = self.autonomy_flags;
        buf[94..110].copy_from_slice(&self.receipt_tip_hash);
        buf[110..126].copy_from_slice(&self.anchor_hash);
        // [126..128] reserved = 0
        buf
    }

    /// Deserialize from 128-byte binary.
    pub fn from_bytes(buf: &[u8; AGENT_STATE_SIZE]) -> Self {
        let mut rcf = [0u8; 32];
        rcf.copy_from_slice(&buf[0..32]);
        let mut node_bytes = [0u8; 4];
        node_bytes[1..4].copy_from_slice(&buf[32..35]);
        let entity_id = u32::from_be_bytes(node_bytes);
        let mut vk = [0u8; 32];
        vk.copy_from_slice(&buf[35..67]);
        let mut tip = [0u8; 16];
        tip.copy_from_slice(&buf[94..110]);
        let mut anchor = [0u8; 16];
        anchor.copy_from_slice(&buf[110..126]);

        Self {
            rcf_identity: rcf,
            entity_id,
            verifying_key: vk,
            k_index: u64::from_be_bytes(buf[67..75].try_into().unwrap()),
            chain_length: u32::from_be_bytes(buf[75..79].try_into().unwrap()),
            t_k_q1616: u32::from_be_bytes(buf[79..83].try_into().unwrap()),
            coherence_q1616: u32::from_be_bytes(buf[83..87].try_into().unwrap()),
            coherence_delta_q1616: i32::from_be_bytes(buf[87..91].try_into().unwrap()),
            sluice_state: buf[91],
            trajectory_phase: buf[92],
            autonomy_flags: buf[93],
            receipt_tip_hash: tip,
            anchor_hash: anchor,
        }
    }

    /// Write agent state to file. Overwrites — current state only.
    /// The chain has the history. This file has the position.
    pub fn write_to_file(&self, path: &Path) -> io::Result<()> {
        let mut file = OpenOptions::new()
            .write(true).create(true).truncate(true).open(path)?;
        file.write_all(&self.to_bytes())?;
        file.flush()
    }

    /// Read agent state from file. Returns None if file doesn't exist or is wrong size.
    pub fn read_from_file(path: &Path) -> io::Result<Self> {
        let mut file = File::open(path)?;
        let len = file.metadata()?.len();
        if len != AGENT_STATE_SIZE as u64 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("agent state file is {} bytes, expected {}", len, AGENT_STATE_SIZE),
            ));
        }
        let mut buf = [0u8; AGENT_STATE_SIZE];
        file.read_exact(&mut buf)?;
        Ok(Self::from_bytes(&buf))
    }

    /// Autonomy boundary check. Returns true if all 3 boundaries intact.
    pub fn autonomy_intact(&self) -> bool {
        self.autonomy_flags & 0b111 == 0b111
    }

    /// Coherence improving? Negative delta = descending toward C(Δ)=0.
    pub fn coherence_improving(&self) -> bool {
        self.coherence_delta_q1616 < 0
    }
}

/// D.AGENT.STATE.1 — Re-entry context for an agent after compaction/restart.
///
/// The kernel computes this from the agent's binary state and chain.
/// C2R translates it into minimal context. The agent doesn't remember —
/// it reads its coordinates and heading.
#[derive(Debug, Clone)]
pub struct ReentryContext {
    /// Agent's current state (128 bytes, algebraic).
    pub state: AgentStateRecord,
    /// Gradient hint: best direction to reduce coherence from current position.
    pub gradient_direction: (usize, usize),
    /// Gradient magnitude (as Q). Zero = flat, needs basin hop.
    pub gradient_epsilon: Q,
    /// Last N receipt hashes from the chain (most recent first).
    pub recent_receipt_hashes: Vec<[u8; 16]>,
    /// Orbit changed since last re-entry? (RCF hash differs from anchor)
    pub orbit_changed: bool,
    /// Chain integrity verified?
    pub chain_verified: bool,
}

impl ReentryContext {
    /// Build re-entry context from agent state, current delta, and chain data.
    ///
    /// This is what the kernel returns on AGENT_REENTRY.
    /// The agent receives algebraic state — not prose, not JSON.
    /// C2R can project this to language at the interop boundary if needed.
    pub fn build(
        state: &AgentStateRecord,
        delta: &Delta,
        anchor_rcf: &[u8; 32],
        recent_receipts: Vec<[u8; 16]>,
        chain_verified: bool,
    ) -> Self {
        let (row, col, eps) = gradient::gradient_hint(delta);
        let current_rcf = compute_rcf_hash(delta);
        let orbit_changed = current_rcf != *anchor_rcf;

        Self {
            state: state.clone(),
            gradient_direction: (row, col),
            gradient_epsilon: eps,
            recent_receipt_hashes: recent_receipts,
            orbit_changed,
            chain_verified,
        }
    }

    /// Is the agent in a valid state for resumed operation?
    pub fn valid_for_reentry(&self) -> bool {
        self.chain_verified
            && self.state.autonomy_intact()
            && self.state.sluice_state != SluiceState::Corrupted.enc_u8()
    }
}

// ─── Tests ───���────────────────────────────���────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{Delta, Trajectory};
    use num_bigint::BigInt;
    use num_traits::Zero;

    fn qr(n: i64, d: i64) -> Q { Q::new(BigInt::from(n), BigInt::from(d)) }

    fn test_state() -> NodeState {
        let mut d = Delta::zero(3, 1);
        d.set_antisym(0, 1, vec![qr(1, 1)]);
        NodeState {
            entity_id: 42, k_index: 100, sluice_state: SluiceState::Locked,
            latest_sigma_enc: 0, delta_k: d.clone(), delta_bar: d,
            trajectory: Trajectory::new(), t_k_latest: Q::zero(),
        }
    }

    #[test]
    fn test_uaid_from_node_state_deterministic() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let u1 = UAID::from_node_state(&state, &genesis_rcf);
        let u2 = UAID::from_node_state(&state, &genesis_rcf);
        assert_eq!(u1, u2, "UAID must be deterministic");
    }

    #[test]
    fn test_uaid_serialization_roundtrip() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let uaid = UAID::from_node_state(&state, &genesis_rcf);
        let bytes = uaid.to_bytes();
        assert_eq!(bytes.len(), 67);
        let decoded = UAID::from_bytes(&bytes);
        assert_eq!(decoded, uaid);
    }

    #[test]
    fn test_uaid_entity_id_preserved() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let uaid = UAID::from_node_state(&state, &genesis_rcf);
        assert_eq!(uaid.entity_id, 42);
    }

    #[test]
    fn test_autonomy_levels() {
        let eps = qr(1, 1000);
        assert_eq!(AutonomyLevel::from_omega(&qr(1, 1), &eps), AutonomyLevel::Full);
        assert_eq!(AutonomyLevel::from_omega(&qr(1, 2), &eps), AutonomyLevel::Partial);
        assert_eq!(AutonomyLevel::from_omega(&qr(1, 1000), &eps), AutonomyLevel::Threshold);
        assert_eq!(AutonomyLevel::from_omega(&qr(0, 1), &eps), AutonomyLevel::None);
    }

    #[test]
    fn test_rollback_trigger() {
        let mut check = RollbackCheck::new(10, 8);
        // 7 failures: not enough
        for _ in 0..7 { check.record(false); }
        for _ in 0..3 { check.record(true); }
        assert!(!check.should_rollback());
        // 8 failures in window: trigger
        let mut check2 = RollbackCheck::new(10, 8);
        for _ in 0..8 { check2.record(false); }
        for _ in 0..2 { check2.record(true); }
        assert!(check2.should_rollback());
    }

    #[test]
    fn test_child_key_derivation() {
        let parent_rcf = [0x42u8; 32];
        let (sk, vk) = derive_child_key(&parent_rcf);
        // Child key must be deterministic
        let (sk2, vk2) = derive_child_key(&parent_rcf);
        assert_eq!(sk.to_bytes(), sk2.to_bytes());
        assert_eq!(vk.to_bytes(), vk2.to_bytes());
        // Different parent → different child
        let (sk3, _) = derive_child_key(&[0x43u8; 32]);
        assert_ne!(sk.to_bytes(), sk3.to_bytes());
    }

    #[test]
    fn test_spawn_record_hierarchy() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let parent_hash = [0xAA; 32];
        let record = SpawnRecord::create(&state, &genesis_rcf, 100, &parent_hash);
        assert_eq!(record.child_entity_id, 100);
        assert_eq!(record.spawn_k_index, 100);
        // Child's first receipt parent_hash (truncated 16 bytes) must match
        let mut trunc: [u8; 16] = [0; 16];
        trunc.copy_from_slice(&parent_hash[0..16]);
        assert!(record.verify_hierarchy(&trunc));
        // Wrong parent hash must fail
        assert!(!record.verify_hierarchy(&[0xBB; 16]));
    }

    #[test]
    fn test_spawn_child_key_differs_from_parent() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let parent_uaid = UAID::from_node_state(&state, &genesis_rcf);
        let (_, child_vk) = derive_child_key(&parent_uaid.rcf_identity);
        // Child key derived from parent's RCF — different from parent's key
        // (unless genesis_rcf == current rcf, in which case they match by construction)
        // The point is determinism: same parent state always produces same child key
        let (_, child_vk2) = derive_child_key(&parent_uaid.rcf_identity);
        assert_eq!(child_vk.to_bytes(), child_vk2.to_bytes());
    }

    #[test]
    fn test_same_orbit() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let u1 = UAID::from_node_state(&state, &genesis_rcf);
        let u2 = UAID::from_node_state(&state, &genesis_rcf);
        assert!(u1.same_orbit(&u2));
    }

    // ─── AgentStateRecord tests ───────────────────────────────────────

    #[test]
    fn test_agent_state_record_roundtrip() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let anchor_hash = [0xAA; 32];
        let receipt_tip = [0xBB; 32];

        let record = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 50, 0, &receipt_tip, &anchor_hash,
        );
        let bytes = record.to_bytes();
        assert_eq!(bytes.len(), AGENT_STATE_SIZE);
        let decoded = AgentStateRecord::from_bytes(&bytes);
        assert_eq!(decoded, record);
    }

    #[test]
    fn test_agent_state_128_bytes_exact() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let record = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 10, 0, &[0; 32], &[0; 32],
        );
        assert_eq!(record.to_bytes().len(), 128);
    }

    #[test]
    fn test_agent_state_preserves_entity_id() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let record = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 0, 0, &[0; 32], &[0; 32],
        );
        assert_eq!(record.entity_id, 42);
        assert_eq!(record.k_index, 100);
    }

    #[test]
    fn test_agent_state_autonomy_flags() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let record = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 0, 0, &[0; 32], &[0; 32],
        );
        assert!(record.autonomy_intact());
        // Corrupt one boundary
        let mut corrupted = record.clone();
        corrupted.autonomy_flags = 0b110; // kernel boundary down
        assert!(!corrupted.autonomy_intact());
    }

    #[test]
    fn test_agent_state_coherence_delta_sign() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        // Set prev_coherence equal to current — delta should be 0
        let record_eq = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 0, record_coherence_of(&state), &[0; 32], &[0; 32],
        );
        assert_eq!(record_eq.coherence_delta_q1616, 0, "Same coherence → zero delta");

        // Set prev_coherence much higher — delta should be negative (improving)
        let record_better = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 0, record_coherence_of(&state) + 1000, &[0; 32], &[0; 32],
        );
        assert!(record_better.coherence_improving(),
            "Lower coherence than previous → negative delta → improving");
    }

    /// Helper: get the Q16.16 coherence of a test state for comparison.
    fn record_coherence_of(state: &NodeState) -> u32 {
        let c = coherence_functional(&state.delta_k);
        t_k_to_q1616(&c)
    }

    #[test]
    fn test_agent_state_file_roundtrip() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let record = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 25, 0, &[0xCC; 32], &[0xDD; 32],
        );

        let path = std::env::temp_dir().join(format!("saios-agent-state-test-{}.bin",
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));
        record.write_to_file(&path).unwrap();
        let loaded = AgentStateRecord::read_from_file(&path).unwrap();
        assert_eq!(loaded, record);
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_reentry_context_build() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let agent_state = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 10, 0, &[0; 32], &[0; 32],
        );
        let ctx = ReentryContext::build(
            &agent_state, &state.delta_k, &genesis_rcf,
            vec![[0xAA; 16], [0xBB; 16]], true,
        );
        assert!(ctx.chain_verified);
        assert_eq!(ctx.recent_receipt_hashes.len(), 2);
        assert!(ctx.valid_for_reentry());
    }

    #[test]
    fn test_reentry_invalid_if_chain_unverified() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let agent_state = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 10, 0, &[0; 32], &[0; 32],
        );
        let ctx = ReentryContext::build(
            &agent_state, &state.delta_k, &genesis_rcf,
            vec![], false,
        );
        assert!(!ctx.valid_for_reentry());
    }

    #[test]
    fn test_agent_state_deterministic() {
        let state = test_state();
        let genesis_rcf = compute_rcf_hash(&state.delta_k);
        let r1 = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 5, 10, &[0xAA; 32], &[0xBB; 32],
        );
        let r2 = AgentStateRecord::from_node_state(
            &state, &genesis_rcf, 5, 10, &[0xAA; 32], &[0xBB; 32],
        );
        assert_eq!(r1.to_bytes(), r2.to_bytes(), "Agent state must be deterministic");
    }
}
