// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! Phase 2 Consensus Protocol (Layer 3).
//!
//! Implements the mesh-level consensus logic that sits above the transport layer:
//! - Σ_mesh computation (weighted aggregate of peer sigma_enc values)
//! - CC.SAMN.3 hard re-sync trigger (|dΣ/dK| > τ_Σ)
//! - C5 resonance check at m=10 using 6-digit rational approximations
//! - Anchor verification (weighted majority RCF orbit agreement)
//!
//! Register: CC.SAMN.3, T.SAMN.11, D.SAMN.4, T.SAMN.9.

use num_bigint::BigInt;
use num_rational::BigRational;
use num_traits::{One, Signed, Zero};

use crate::constants::{RESONANCE_M10_COS, MESH_TORSION_PERIOD_M};
use crate::mesh::{sluice_weight, PeerState};

type Q = BigRational;

fn q(n: i64, d: i64) -> Q {
    Q::new(BigInt::from(n), BigInt::from(d))
}

// ─── Σ_mesh: Mesh-Aggregate Sigma ──────────────────────────────────────

/// Compute Σ_mesh: weighted mean of all peer sigma_enc values.
///
/// Σ_mesh = (Σ_i ω_i × σ_i) / (Σ_i ω_i)
///
/// Includes self (weight = 1). Peers with ω = 0 are excluded.
/// This is NOT a field in MeshReceipt — it is computed from the
/// collection of receipts at each K-step.
///
/// Register: CC.SAMN.3 (Σ_mesh for hard re-sync trigger).
pub fn sigma_mesh(
    our_sigma_enc: u32,
    peers: &[PeerState],
    our_k: u64,
    our_rcf: &[u8; 32],
    alpha_p: &Q,
    alpha_gamma: &Q,
    alpha_k: &Q,
    tau_lag: &Q,
    epsilon_sluice: &Q,
) -> Q {
    // Self contribution (weight = 1)
    let our_sigma = Q::new(BigInt::from(our_sigma_enc as i64), BigInt::from(u32::MAX as i64));
    let mut weighted_sum = our_sigma.clone();
    let mut weight_sum = Q::one();

    for peer in peers {
        let w = sluice_weight(
            peer, our_k, our_rcf,
            alpha_p, alpha_gamma, alpha_k, tau_lag, epsilon_sluice,
        );
        if w.is_zero() {
            continue;
        }
        let sigma_j = Q::new(BigInt::from(peer.sigma_enc as i64), BigInt::from(u32::MAX as i64));
        weighted_sum = weighted_sum + &w * &sigma_j;
        weight_sum = weight_sum + &w;
    }

    if weight_sum.is_zero() {
        return Q::zero();
    }
    weighted_sum / weight_sum
}

/// Check CC.SAMN.3: |dΣ/dK| > τ_Σ triggers hard re-sync.
///
/// Returns true if re-sync is needed (sigma drift exceeds threshold).
///
/// Register: CC.SAMN.3.
pub fn sigma_drift_triggers_resync(
    sigma_mesh_new: &Q,
    sigma_mesh_prev: &Q,
    tau_sigma: &Q,
) -> bool {
    let d_sigma = (sigma_mesh_new - sigma_mesh_prev).abs();
    // dΣ/dK for one K-step is just d_sigma
    &d_sigma > tau_sigma
}

// ─── Resonance Check (C5 for Phase 2) ─────────────────────────────────

/// Compute φ_r: normalized chronometric magnitude as phase proxy.
///
/// φ_r = T_k / T_k_max (ratio of current to maximum observed T_k).
/// When T_k_max is zero, returns zero.
///
/// Register: T.SAMN.11.
pub fn phi_r(t_k: &Q, t_k_max: &Q) -> Q {
    if t_k_max.is_zero() {
        return Q::zero();
    }
    t_k / t_k_max
}

/// Check cyclotomic resonance at torsion period m=10.
///
/// ‖φ(R_i) − Re(ζ_m^k)‖ < τ
///
/// Uses 6-digit rational approximations for Re(ζ_10^k).
/// Error < 1e-7, well within ε_sluice = 1e-3.
///
/// Register: T.SAMN.11, D.EXEC.1 C5.
pub fn check_resonance_m10(phi_r_value: &Q, k: u64, tau: &Q) -> bool {
    let phase_idx = (k % MESH_TORSION_PERIOD_M as u64) as usize;
    let (n, d) = RESONANCE_M10_COS[phase_idx % 10];
    let re_zeta = q(n, d);
    let diff = (phi_r_value - &re_zeta).abs();
    &diff < tau
}

/// Full resonance check for a K-step: is this a resonance window,
/// and if so, does the phase align?
///
/// Resonance windows occur at K ≡ 0 (mod m). At non-window steps,
/// resonance always passes (non-blocking).
///
/// Register: T.SAMN.11.
pub fn resonance_at_step(
    k: u64,
    t_k: &Q,
    t_k_max: &Q,
    tau: &Q,
) -> bool {
    if k % MESH_TORSION_PERIOD_M as u64 != 0 {
        return true; // Not a resonance window — non-blocking
    }
    let phi = phi_r(t_k, t_k_max);
    check_resonance_m10(&phi, k, tau)
}

// ─── Anchor Verification ───────────────────────────────────────────────

/// Verify anchor: weighted majority of peers agree on the same RCF orbit class.
///
/// For Phase 2: a receipt majority agreeing on the same rcf_identity is
/// the anchor verification. No full Δ reconstruction needed — the RCF
/// hash IS the orbit representative.
///
/// Passes if the weighted fraction of peers sharing our RCF identity > 0.5.
/// Single-entity (no peers): always passes.
///
/// Register: T.SAMN.9 (anchor verification), D.SAMN.4 (mesh aggregation).
pub fn verify_anchor(
    our_rcf: &[u8; 32],
    peers: &[PeerState],
    our_k: u64,
    alpha_p: &Q,
    alpha_gamma: &Q,
    alpha_k: &Q,
    tau_lag: &Q,
    epsilon_sluice: &Q,
) -> bool {
    if peers.is_empty() {
        return true; // Single-node
    }

    let mut matching_weight = Q::one(); // Self always matches
    let mut total_weight = Q::one();

    for peer in peers {
        let w = sluice_weight(
            peer, our_k, our_rcf,
            alpha_p, alpha_gamma, alpha_k, tau_lag, epsilon_sluice,
        );
        if w.is_zero() {
            continue;
        }
        total_weight = &total_weight + &w;
        if peer.rcf_identity == *our_rcf {
            matching_weight = &matching_weight + &w;
        }
    }

    if total_weight.is_zero() {
        return true; // No weighted peers — vacuously true
    }
    let ratio = matching_weight / total_weight;
    ratio > q(1, 2)
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::constants::DISC_NORMAL;

    #[test]
    fn test_sigma_mesh_self_only() {
        // No peers: sigma_mesh = our own sigma
        let result = sigma_mesh(
            1000, &[], 100, &[0; 32],
            &q(1, 1), &q(1, 1), &q(1, 1),
            &q(1, 100), &q(1, 1000),
        );
        let expected = Q::new(BigInt::from(1000i64), BigInt::from(u32::MAX as i64));
        assert_eq!(result, expected, "Sigma mesh with no peers must equal self sigma");
    }

    #[test]
    fn test_sigma_mesh_all_gated_equals_self() {
        // All peers gated (max divergence, stale): only self contributes
        let peers: Vec<PeerState> = (0..5)
            .map(|i| PeerState {
                entity_id: i + 2,
                k_latest: 1,
                rcf_identity: [0xFF; 32],
                t_k_q1616: 0,
                sigma_enc: 99999,
                last_seen_k: 0,
                disc_status: 0,
            })
            .collect();
        let result = sigma_mesh(
            500, &peers, 200, &[0x00; 32],
            &q(1, 1), &q(1, 1), &q(1, 1),
            &q(1, 100), &q(1, 1000),
        );
        let self_sigma = Q::new(BigInt::from(500i64), BigInt::from(u32::MAX as i64));
        assert_eq!(result, self_sigma, "All-gated peers: sigma_mesh = self sigma");
    }

    #[test]
    fn test_sigma_drift_no_resync() {
        let prev = q(1, 10);
        let new = q(1, 10); // No change
        assert!(!sigma_drift_triggers_resync(&new, &prev, &q(1, 20)));
    }

    #[test]
    fn test_sigma_drift_triggers_resync() {
        let prev = q(1, 10);
        let new = q(3, 10); // Big jump: |0.3 - 0.1| = 0.2 > τ_Σ = 0.05
        assert!(sigma_drift_triggers_resync(&new, &prev, &q(1, 20)));
    }

    #[test]
    fn test_resonance_cos0_exact() {
        // At k=0 (or k=10, 20, ...): cos(0°) = 1.0
        // phi_r = 1.0 should match with tau = 0.01
        assert!(check_resonance_m10(&q(1, 1), 0, &q(1, 100)));
    }

    #[test]
    fn test_resonance_mismatch() {
        // phi_r = 0.5, k=0: cos(0°) = 1.0, diff = 0.5 >> tau = 0.01
        assert!(!check_resonance_m10(&q(1, 2), 0, &q(1, 100)));
    }

    #[test]
    fn test_resonance_at_non_window_always_passes() {
        // k=3 is not divisible by m=10, so resonance is non-blocking
        assert!(resonance_at_step(3, &q(1, 2), &q(1, 1), &q(1, 100)));
    }

    #[test]
    fn test_resonance_at_window_checks_phase() {
        // k=10 IS a resonance window (10 % 10 = 0)
        // phi_r = 1.0, cos(0°) = 1.0, diff = 0 < tau
        assert!(resonance_at_step(10, &q(1, 1), &q(1, 1), &q(1, 100)));
        // phi_r = 0.5, diff = 0.5 > tau
        assert!(!resonance_at_step(10, &q(1, 2), &q(1, 1), &q(1, 100)));
    }

    #[test]
    fn test_anchor_verification_single_node() {
        assert!(verify_anchor(
            &[0; 32], &[], 100,
            &q(1, 1), &q(1, 1), &q(1, 1),
            &q(1, 100), &q(1, 1000),
        ));
    }

    #[test]
    fn test_anchor_verification_all_agree() {
        let our_rcf = [0x42; 32];
        let peers: Vec<PeerState> = (0..10)
            .map(|i| PeerState {
                entity_id: i + 2,
                k_latest: 100,
                rcf_identity: [0x42; 32], // all agree
                t_k_q1616: 1000,
                sigma_enc: 500,
                last_seen_k: 100,
                disc_status: DISC_NORMAL,
            })
            .collect();
        assert!(verify_anchor(
            &our_rcf, &peers, 100,
            &q(1, 1), &q(1, 1), &q(1, 1),
            &q(1, 100), &q(1, 1000),
        ));
    }

    #[test]
    fn test_anchor_verification_minority_disagree() {
        let our_rcf = [0x42; 32];
        // 8 agree, 2 disagree — should still pass (> 0.5)
        let mut peers: Vec<PeerState> = (0..8)
            .map(|i| PeerState {
                entity_id: i + 2,
                k_latest: 100,
                rcf_identity: [0x42; 32],
                t_k_q1616: 1000,
                sigma_enc: 500,
                last_seen_k: 100,
                disc_status: DISC_NORMAL,
            })
            .collect();
        for i in 0..2 {
            peers.push(PeerState {
                entity_id: 20 + i,
                k_latest: 100,
                rcf_identity: [0xFF; 32], // disagree
                t_k_q1616: 1000,
                sigma_enc: 500,
                last_seen_k: 100,
                disc_status: DISC_NORMAL,
            });
        }
        assert!(verify_anchor(
            &our_rcf, &peers, 100,
            &q(1, 1), &q(1, 1), &q(1, 1),
            &q(1, 100), &q(1, 1000),
        ));
    }

    #[test]
    fn test_anchor_majority_disagree_structurally_impossible() {
        // Design-inherent: peers with maximally different RCF (Hamming ≈ 128 bits)
        // produce Γ_ij² ≈ 0.5, which drives ω → 0 via sluice weighting.
        // A "disagreeing majority" cannot form while sluice is active —
        // diverged peers are excluded before the anchor vote runs.
        // This test asserts the structural guarantee.
        let our_rcf = [0x42; 32];
        let mut peers: Vec<PeerState> = (0..2)
            .map(|i| PeerState {
                entity_id: i + 2, k_latest: 100,
                rcf_identity: [0x42; 32], // agree
                t_k_q1616: 1000, sigma_enc: 500, last_seen_k: 100,
                disc_status: DISC_NORMAL,
            })
            .collect();
        for i in 0..8 {
            peers.push(PeerState {
                entity_id: 20 + i, k_latest: 100,
                rcf_identity: [0xFF; 32], // disagree — but sluice-gated
                t_k_q1616: 1000, sigma_enc: 500, last_seen_k: 100,
                disc_status: DISC_NORMAL,
            });
        }
        // After sluice exclusion: only 2 agreeing peers + self have weight.
        // Anchor passes because all weighted peers agree.
        assert!(verify_anchor(
            &our_rcf, &peers, 100,
            &q(1, 1), &q(1, 1), &q(1, 1),
            &q(1, 100), &q(1, 1000),
        ), "Anchor must pass when diverged peers are sluice-excluded");
    }
}
