// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! SAIOS Phase 1 Golden Constants — Boot Fixtures and Containment Parameters.
//!
//! These constants define the deterministic environment for Phase 1 kernel
//! execution. They are compiled into the binary and are immutable for the
//! lifetime of a Phase 1 deployment.
//!
//! ## Blocker 2: Boot Fixtures
//! - `DELTA_ANCHOR_HASH`: 32-byte origin hash for B2 anchor handshake.
//! - `TORSION_PERIOD_M`: Resonance confirmation period for B5/C5.
//!
//! ## Blocker 3: Transcendental Containment
//! - `TAYLOR_EXP_COEFFICIENTS`: Locked 12-term rational Taylor expansion
//!   for exp(x), stored as (numerator, denominator) pairs.
//! - `TAYLOR_DEGREE`: Degree bound (11) guaranteeing error < ε_sluice/10.
//!
//! Register: D.CHAIN.1, D.EXEC.1 B2/B5, IMPL.GATE.1.

use num_bigint::BigInt;
use num_rational::BigRational;
use tiny_keccak::{Hasher, Keccak};

pub type Q = BigRational;

// ─── Blocker 2: Boot Fixtures ──────────────────────────────────────────

/// Genesis anchor tag. The DELTA_ANCHOR_HASH is the Keccak-256 of this
/// domain-separated constant, providing a deterministic "Block 0" for
/// the SAIOS authority chain.
///
/// Register: D.CHAIN.1 (origin receipt), D.EXEC.1 B2.
pub const DELTA_ANCHOR_TAG: &[u8] = b"SAIOS_ORIGIN_ANCHOR_2026_V001";

/// Compute the 32-byte origin anchor hash.
///
/// This is the Keccak-256 of the domain-separated anchor tag,
/// providing a deterministic zero-state hash for B2 handshake.
/// Every Phase 1 entity boots against this identical anchor.
pub fn delta_anchor_hash() -> [u8; 32] {
    let mut k = Keccak::v256();
    let mut out = [0u8; 32];
    // Domain separation: "SAIOS-BOOT-B2-v1" || anchor tag
    k.update(b"SAIOS-BOOT-B2-v1");
    k.update(DELTA_ANCHOR_TAG);
    k.finalize(&mut out);
    out
}

/// Torsion period m: the resonance confirmation frequency.
///
/// Every m K-steps, the entity must pass a C5 resonance check to confirm
/// cyclotomic phase alignment. m=1024 balances verification frequency
/// against computational overhead for Phase 1 single-entity deployment.
///
/// Register: D.EXEC.1 B5, T.SAMN.11.
pub const TORSION_PERIOD_M: u32 = 1024;

/// Phase 1 boot sequence step identifiers.
///
/// B1: Substrate audit (encoding integrity)
/// B2: Anchor handshake (verify origin hash)
/// B3: Mesh sync (Phase 1 no-op — single node)
/// B4: Environment/config load
/// B5: Resonance confirmation (torsion period m)
/// B6: K=1 proof cycle (first valid K-step + receipt)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BootStep {
    /// B1: Verify substrate encoding integrity for all initial state.
    B1SubstrateAudit,
    /// B2: Verify DELTA_ANCHOR_HASH matches compiled origin constant.
    B2AnchorHandshake,
    /// B3: Mesh sync — no-op for Phase 1 single node.
    B3MeshSync,
    /// B4: Load environment and phase config.
    B4EnvironmentLoad,
    /// B5: Confirm resonance at torsion period m.
    B5ResonanceConfirmation,
    /// B6: Execute first K-step (K=1) and emit origin receipt.
    B6GenesisProofCycle,
}

/// Result of a single boot step.
#[derive(Debug, Clone)]
pub struct BootStepResult {
    pub step: BootStep,
    pub passed: bool,
    pub detail: String,
}

/// Complete boot report: status of each B1-B6 step.
#[derive(Debug, Clone)]
pub struct BootReport {
    pub steps: Vec<BootStepResult>,
    pub all_passed: bool,
    pub anchor_hash: [u8; 32],
    pub torsion_period: u32,
}

// ─── Blocker 3: Transcendental Containment ─────────────────────────────

/// Number of terms in the locked Taylor expansion for exp(x).
///
/// 12 terms (degree 0 through 11) provides:
/// - For |x| ≤ 1: error < 1/479,001,600 ≈ 2.09e-9
/// - For |x| ≤ 2: error < 2^12/479,001,600 ≈ 8.55e-6
///
/// Since ε_sluice = 1/1000, the error bound 2.09e-9 < ε_sluice/10 = 1e-4
/// by a factor of ~48,000. This is register-compliant per IMPL.GATE.1.
///
/// Register: IMPL.GATE.1.
pub const TAYLOR_DEGREE: usize = 12;

/// Locked rational Taylor coefficients for exp(x).
///
/// c_n = 1/n! stored as (numerator, denominator) pairs.
/// These are exact: no rounding, no approximation in the coefficients
/// themselves. The approximation is only in truncating the series.
///
/// The first 12 coefficients are frozen per Phase 1 IMPL.GATE.1.
/// Terms 12-19 are a non-breaking extension for Phase 2 mesh weighting,
/// where larger exponents (peer K-index gaps) require more terms for
/// convergence. All coefficients are c_n = 1/n! — mathematically determined.
///
/// Register: IMPL.GATE.1 (terms 0-11), D.EXEC.1 (terms 12-19 for mesh).
pub const TAYLOR_EXP_COEFFICIENTS: [(i64, i64); 20] = [
    (1,                    1),  // 1/0!  = 1
    (1,                    1),  // 1/1!  = 1
    (1,                    2),  // 1/2!  = 1/2
    (1,                    6),  // 1/3!  = 1/6
    (1,                   24),  // 1/4!  = 1/24
    (1,                  120),  // 1/5!  = 1/120
    (1,                  720),  // 1/6!  = 1/720
    (1,                 5040),  // 1/7!  = 1/5040
    (1,                40320),  // 1/8!  = 1/40320
    (1,               362880),  // 1/9!  = 1/362880
    (1,              3628800),  // 1/10! = 1/3628800
    (1,             39916800),  // 1/11! = 1/39916800
    // Phase 2 extension (terms 12-19):
    (1,            479001600),  // 1/12! = 1/479001600
    (1,           6227020800),  // 1/13! = 1/6227020800
    (1,          87178291200),  // 1/14! = 1/87178291200
    (1,        1307674368000),  // 1/15! = 1/1307674368000
    (1,       20922789888000),  // 1/16! = 1/20922789888000
    (1,      355687428096000),  // 1/17! = 1/355687428096000
    (1,     6402373705728000),  // 1/18! = 1/6402373705728000
    (1,   121645100408832000),  // 1/19! = 1/121645100408832000
];

/// Phase 1 term count (locked per IMPL.GATE.1).
pub const TAYLOR_PHASE1_TERMS: usize = 12;

/// Phase 2 term count (extended for mesh weighting convergence).
pub const TAYLOR_PHASE2_TERMS: usize = 20;

/// Error bound for the 20-term Taylor expansion of exp(x) at |x| ≤ 1.
///
/// |R_20(x)| ≤ |x|^20 / 20! = 1/2,432,902,008,176,640,000 for |x| ≤ 1.
pub const TAYLOR_ERROR_BOUND_DENOM: i64 = 479_001_600; // 12! (Phase 1 bound preserved)

/// Compute exp(x) using the locked rational Taylor expansion.
///
/// `terms` specifies how many coefficients to use (max 20).
/// Phase 1: use TAYLOR_PHASE1_TERMS (12).
/// Phase 2 mesh: use TAYLOR_PHASE2_TERMS (20) for larger exponents.
///
/// All arithmetic is exact rational. The result is clamped to [0, 1]
/// for weight applications (ω_i are probabilities).
///
/// Register: IMPL.GATE.1, D.MFA.WEIGHT, D.5.1-DIM.
pub fn locked_rational_exp_n(x: &Q, terms: usize) -> Q {
    let n = terms.min(TAYLOR_EXP_COEFFICIENTS.len());
    let mut result = Q::new(BigInt::from(0), BigInt::from(1));
    let mut x_power = Q::new(BigInt::from(1), BigInt::from(1));

    for &(num, den) in &TAYLOR_EXP_COEFFICIENTS[..n] {
        let coeff = Q::new(BigInt::from(num), BigInt::from(den));
        result = result + &x_power * &coeff;
        x_power = x_power * x;
    }

    let zero = Q::new(BigInt::from(0), BigInt::from(1));
    let one = Q::new(BigInt::from(1), BigInt::from(1));
    if result < zero {
        zero
    } else if result > one {
        one
    } else {
        result
    }
}

/// Phase 1 convenience wrapper: 12-term Taylor expansion.
/// Register: IMPL.GATE.1.
pub fn locked_rational_exp(x: &Q) -> Q {
    locked_rational_exp_n(x, TAYLOR_PHASE1_TERMS)
}

/// Phase 2 mesh weighting: 20-term Taylor expansion for larger exponents.
pub fn locked_rational_exp_mesh(x: &Q) -> Q {
    locked_rational_exp_n(x, TAYLOR_PHASE2_TERMS)
}

/// Verify that the Taylor error bound satisfies the containment gate.
///
/// Returns true iff 1/12! < ε_sluice / 10, confirming that the 12-term
/// expansion is sufficient for register compliance.
///
/// Register: IMPL.GATE.1.
pub fn verify_containment_gate(epsilon_sluice: &Q) -> bool {
    let error_bound = Q::new(BigInt::from(1), BigInt::from(TAYLOR_ERROR_BOUND_DENOM));
    let threshold = epsilon_sluice / &Q::new(BigInt::from(10), BigInt::from(1));
    error_bound < threshold
}

// ─── Phase 2: Resonance Constants ──────────────────────────────────────

/// Default mesh operating torsion period (Phase 2).
/// N=101 nodes, N-1=100, default m=10 (decagonal, 36° spacing).
/// Register: T.SAMN.11.
pub const MESH_TORSION_PERIOD_M: u32 = 10;

/// Mesh entity count (Phase 2). N=101 is prime; N-1=100 has 9 divisors
/// each of which is a valid torsion period.
/// Register: Phase 2 PreFlight.
pub const MESH_NODE_COUNT: u32 = 101;

/// Re(ζ_10^k) = cos(2πk/10) as 6-digit rational approximations.
///
/// cos(36°) = (1+√5)/4 ≈ 0.809017 (irrational, rational bound to < 1e-7)
/// cos(72°) = (√5-1)/4 ≈ 0.309017 (irrational, rational bound to < 1e-7)
///
/// Format: (numerator, denominator) for k = 0..9.
/// Error < 1e-7 for all entries, well within ε_sluice = 1e-3.
///
/// Register: T.SAMN.11, D.EXEC.1 C5.
pub const RESONANCE_M10_COS: [(i64, i64); 10] = [
    ( 1000000, 1000000),  // k=0: cos(0°)   = 1.000000
    (  809017, 1000000),  // k=1: cos(36°)  ≈ 0.809017
    (  309017, 1000000),  // k=2: cos(72°)  ≈ 0.309017
    ( -309017, 1000000),  // k=3: cos(108°) ≈ -0.309017
    ( -809017, 1000000),  // k=4: cos(144°) ≈ -0.809017
    (-1000000, 1000000),  // k=5: cos(180°) = -1.000000
    ( -809017, 1000000),  // k=6: cos(216°) ≈ -0.809017
    ( -309017, 1000000),  // k=7: cos(252°) ≈ -0.309017
    (  309017, 1000000),  // k=8: cos(288°) ≈ 0.309017
    (  809017, 1000000),  // k=9: cos(324°) ≈ 0.809017
];

/// Discontinuity flag values for D.CHAIN.1-ENC-v3.
/// Register: F.SAMN.3-CONT.
pub const DISC_NORMAL: u8 = 0x00;
pub const DISC_RESTART: u8 = 0x01;
pub const DISC_ISOLATED: u8 = 0x02;
pub const DISC_CORRUPTED: u8 = 0x03;

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn q(n: i64, d: i64) -> Q {
        Q::new(BigInt::from(n), BigInt::from(d))
    }

    #[test]
    fn test_delta_anchor_hash_deterministic() {
        let h1 = delta_anchor_hash();
        let h2 = delta_anchor_hash();
        assert_eq!(h1, h2);
        // Must not be all zeros
        assert!(h1.iter().any(|&b| b != 0));
    }

    #[test]
    fn test_delta_anchor_hash_domain_separated() {
        // Direct hash of tag without domain separation must differ
        let mut k = Keccak::v256();
        let mut direct = [0u8; 32];
        k.update(DELTA_ANCHOR_TAG);
        k.finalize(&mut direct);
        assert_ne!(delta_anchor_hash(), direct);
    }

    #[test]
    fn test_torsion_period_positive() {
        assert!(TORSION_PERIOD_M > 0);
        // Must be a power of 2 for efficient modular arithmetic
        assert!(TORSION_PERIOD_M.is_power_of_two());
    }

    #[test]
    fn test_taylor_coefficients_correct() {
        // Verify each coefficient is 1/n! (use i128 to avoid overflow at 19!)
        let mut factorial: i128 = 1;
        for (n, &(num, den)) in TAYLOR_EXP_COEFFICIENTS.iter().enumerate() {
            if n > 0 {
                factorial *= n as i128;
            }
            assert_eq!(num, 1, "numerator must be 1 for term {n}");
            assert_eq!(den as i128, factorial, "denominator must be {n}! = {factorial}");
        }
    }

    #[test]
    fn test_locked_rational_exp_at_zero() {
        // exp(0) = 1 exactly
        let result = locked_rational_exp(&q(0, 1));
        assert_eq!(result, q(1, 1));
    }

    #[test]
    fn test_locked_rational_exp_at_one_clamped() {
        // exp(1) ≈ 2.718... but clamped to [0,1] for weight use.
        // Verify it clamps to exactly 1.
        let result = locked_rational_exp(&q(1, 1));
        assert_eq!(result, q(1, 1), "exp(1) should clamp to 1 for weight use");
    }

    #[test]
    fn test_locked_rational_exp_unclamped_accuracy() {
        // Verify the raw Taylor sum (before clamping) is accurate.
        // Compute Σ 1/n! for n=0..11 manually.
        let mut sum = q(0, 1);
        let mut factorial = q(1, 1);
        for n in 0..12i64 {
            if n > 0 {
                factorial = &factorial * &q(n, 1);
            }
            sum = sum + q(1, 1) / &factorial;
        }
        // Should be between 2.718 and 2.719
        assert!(sum > q(2718, 1000), "raw Taylor sum for exp(1) should be > 2.718");
        assert!(sum < q(2719, 1000), "raw Taylor sum for exp(1) should be < 2.719");
    }

    #[test]
    fn test_locked_rational_exp_negative_clamped() {
        // exp(-10) is very small but positive
        let result = locked_rational_exp(&q(-10, 1));
        assert!(result >= q(0, 1), "exp(x) must be >= 0 after clamping");
    }

    #[test]
    fn test_locked_rational_exp_weight_decay() {
        // For weight computation: exp(-x) should decrease as x increases
        let w1 = locked_rational_exp(&q(-1, 10));  // exp(-0.1)
        let w2 = locked_rational_exp(&q(-5, 10));  // exp(-0.5)
        let w3 = locked_rational_exp(&q(-1, 1));   // exp(-1)
        assert!(w1 > w2, "exp(-0.1) > exp(-0.5)");
        assert!(w2 > w3, "exp(-0.5) > exp(-1)");
    }

    #[test]
    fn test_containment_gate_passes() {
        // With ε_sluice = 1/1000, verify 1/12! < ε_sluice/10
        let epsilon_sluice = q(1, 1000);
        assert!(
            verify_containment_gate(&epsilon_sluice),
            "12-term Taylor error bound must be < ε_sluice/10"
        );
    }

    #[test]
    fn test_containment_gate_margin() {
        // The error bound 1/479001600 should be much less than 1/10000
        let error = q(1, TAYLOR_ERROR_BOUND_DENOM);
        let threshold = q(1, 10000); // ε_sluice/10
        let ratio = &threshold / &error;
        // Ratio should be > 40000 (huge margin)
        assert!(ratio > q(40000, 1), "containment margin must be > 40000x");
    }

    #[test]
    fn test_locked_exp_matches_dynamic_exp() {
        // Verify locked_rational_exp matches the formula Σ x^n/n!
        let x = q(-3, 7); // arbitrary test value
        let locked = locked_rational_exp(&x);

        // Manual computation
        let mut result = q(0, 1);
        let mut x_pow = q(1, 1);
        let mut factorial = q(1, 1);
        for n in 0..12i64 {
            if n > 0 {
                factorial = &factorial * &q(n, 1);
            }
            result = result + &x_pow / &factorial;
            x_pow = &x_pow * &x;
        }
        assert_eq!(locked, result, "locked exp must match manual computation");
    }

    #[test]
    fn test_20_term_exp_more_precise_for_large_x() {
        // For x = -5, 20 terms should give a more accurate (smaller) result
        // than 12 terms, since the series needs more terms to converge
        let x = q(-5, 1);
        let exp12 = locked_rational_exp_n(&x, 12);
        let exp20 = locked_rational_exp_mesh(&x);
        // Both should be >= 0 (clamped)
        assert!(exp12 >= q(0, 1));
        assert!(exp20 >= q(0, 1));
        // exp(-5) ≈ 0.0067 — 20 terms should be closer to this
        // 12 terms for x=-5 may undershoot and clamp to 0
        // 20 terms should give a positive result
        assert!(exp20 > q(0, 1), "20-term exp(-5) should be positive, not clamped to 0");
    }

    #[test]
    fn test_resonance_m10_symmetry() {
        // cos(k) = cos(m-k) for k=1..4 (index (10-k) % 10)
        for k in 1..5 {
            let (n1, d1) = RESONANCE_M10_COS[k];
            let (n2, d2) = RESONANCE_M10_COS[10 - k];
            assert_eq!((n1, d1), (n2, d2),
                "Resonance symmetry: cos(k={k}) must equal cos(k={})", 10 - k);
        }
    }

    #[test]
    fn test_resonance_m10_cos_0_and_180() {
        // cos(0°) = 1 exactly, cos(180°) = -1 exactly
        let (n0, d0) = RESONANCE_M10_COS[0];
        assert_eq!(q(n0, d0), q(1, 1), "cos(0°) must be exactly 1");
        let (n5, d5) = RESONANCE_M10_COS[5];
        assert_eq!(q(n5, d5), q(-1, 1), "cos(180°) must be exactly -1");
    }

    #[test]
    fn test_resonance_m10_antisymmetry() {
        // cos(k) = -cos(k+5) for k=0..4
        for k in 0..5 {
            let (n1, d1) = RESONANCE_M10_COS[k];
            let (n2, d2) = RESONANCE_M10_COS[k + 5];
            assert_eq!(q(n1, d1), -q(n2, d2),
                "cos(k={k}) must equal -cos(k={})", k + 5);
        }
    }
}
