// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! D.COORD.1 — Mesh Coordinator: algebraic congruence resolution.
//!
//! The coherence functional C(Δ) = Σ|R| measures deviation from the cocycle condition (L1).
//! The cocycle condition is LINEAR: Δ_ik = Δ_ij + Δ_jk for all triples.
//!
//! Resolution uses L1 subgradient: Aᵀ·sign(r) instead of Aᵀ·r.
//! The AᵀA structure is preserved (positive semidefinite from perturbation products).
//! The right-hand side follows L1 geometry — no squaring in the measurement path.
//!
//! Direct algebraic resolution of the cocycle congruence.
//!
//! Register: D.COORD.1, T.FOUND.2 (cocycle condition), A.1 (exact rational).

use num_bigint::BigInt;
use num_traits::{Zero, One};

use crate::engine::{Delta, Operator, Q, coherence_functional, pi_g_project, for_each_residual, residual_perturbation};
use crate::matrix;

// ─── Cocycle Residual Decomposition ───────────────────────────────────

/// A single cocycle residual: R_{ijk,l} = Δ_{ik,l} - Δ_{ij,l} - Δ_{jk,l}
/// for a specific triple (i,j,k) and coordinate index l.
#[derive(Debug, Clone)]
pub struct CocycleResidual {
    pub i: usize,
    pub j: usize,
    pub k: usize,
    pub l: usize,
    /// The exact rational residual value.
    pub value: Q,
}

/// Complete cocycle decomposition of a Delta state.
#[derive(Debug, Clone)]
pub struct CocycleDecomposition {
    /// All non-zero residuals.
    pub residuals: Vec<CocycleResidual>,
    /// Total squared residual norm = C(Δ). Exact rational.
    pub coherence: Q,
    /// Number of distinct triples with non-zero residuals.
    pub nonzero_triples: usize,
    /// Is the state fully coherent (all residuals zero)?
    pub is_cocycle: bool,
}

/// Compute the complete cocycle decomposition of a Delta.
/// Built on engine::for_each_residual — single source of truth.
pub fn decompose(delta: &Delta) -> CocycleDecomposition {
    let mut residuals = Vec::new();
    let mut coherence = Q::zero();

    for_each_residual(delta, |i, j, k, l, r| {
        if r < &Q::zero() { coherence -= r; } else { coherence += r; }
        residuals.push(CocycleResidual { i, j, k, l, value: r.clone() });
    });

    CocycleDecomposition {
        nonzero_triples: residuals.len(), // simplified: count of nonzero residual entries
        is_cocycle: residuals.is_empty(),
        residuals,
        coherence,
    }
}

// ─── Congruence Resolution ────────────────────────────────────────────

// Perturbation functions are in engine.rs — single source of truth.
// coordinator uses engine::residual_perturbation(delta, i, j, k, l, r, s) directly.

/// Resolution result: the epsilon vector that resolves the cocycle congruence.
#[derive(Debug, Clone)]
pub struct CongruenceResolution {
    /// The independent operator directions (r,s) with r < s.
    pub directions: Vec<(usize, usize)>,
    /// The epsilon values that resolve the congruence.
    /// Operator A = I + Σ εᵢ·(E_{rᵢsᵢ} - E_{sᵢrᵢ}).
    pub epsilon: Vec<Q>,
    /// Was the linear system solvable? (may be underdetermined or overdetermined)
    pub resolved: bool,
    /// Coherence before resolution.
    pub coherence_before: Q,
    /// Predicted coherence after resolution (from the linear model).
    pub predicted_coherence_after: Q,
    /// Dimension of H^1 — the number of independent cohomological obstructions.
    /// d - rank(AᵀA) where d = number of independent directions.
    /// 0 = all obstructions are coboundaries (removable by local operators).
    /// >0 = independent obstructions requiring dimensional expansion.
    pub cohomology_dim: usize,
    /// Kernel of AᵀA — the space of cohomological freedom.
    /// Each vector has length d (one component per independent direction).
    /// Any v in this kernel can be added to epsilon without changing
    /// the first-order coherence prediction. This IS the space of agency:
    /// multiple valid perturbation directions exist when kernel is non-empty.
    pub kernel: Vec<Vec<Q>>,
}

/// Resolve the cocycle congruence algebraically.
///
/// Builds AᵀA and Aᵀr incrementally triple by triple — the same iteration
/// structure as coherence_functional(). Each triple contributes a small-rank
/// update to the accumulating d×d system. The final inversion is ONE d×d
/// solve, but the ACCUMULATION is triple-local.
///
/// For small n (3-5): d×d is 3-10, fast directly.
/// For large n: the d×d matrix is SPARSE because each triple only touches
/// directions involving its 3 nodes. The accumulation exploits this sparsity
/// even though the final solve is dense.
pub fn resolve(delta: &Delta) -> CongruenceResolution {
    let dirs = matrix::independent_dims(delta.dim);
    let d = dirs.len();

    // The coordinator resolves whatever it receives. No gates.
    // The metabolic horizon (d_max) is enforced UPSTREAM by the caller
    // that constructs the Delta — perception and escalation select
    // the spectral dimension m such that d fits within the horizon.
    // The coordinator trusts the Delta it was given.

    // Accumulate AᵀA and Aᵀr using the single triple iterator
    let mut ata = vec![vec![Q::zero(); d]; d];
    let mut atr = vec![Q::zero(); d];
    let mut total_coherence = Q::zero();

    // L1 subgradient: sign(r) × perturbation instead of r × perturbation.
    // The topology is holonomic — proportional, not squared.
    // AᵀA structure preserved (positive semidefinite from |p|²).
    // The right-hand side uses sign(r) to follow L1 geometry.
    for_each_residual(delta, |i, j, k, l, r_val| {
        // L1 coherence: Σ|R|, not Σ R²
        if r_val < &Q::zero() { total_coherence -= r_val; } else { total_coherence += r_val; }

        // Sign of residual for L1 subgradient
        let sign_r = if r_val < &Q::zero() {
            Q::new(BigInt::from(-1), BigInt::from(1))
        } else {
            Q::new(BigInt::from(1), BigInt::from(1))
        };

        // Sparse perturbation row — only compute nonzero entries
        let mut pert_row: Vec<(usize, Q)> = Vec::new();
        for (idx, &(dir_r, dir_s)) in dirs.iter().enumerate() {
            let p = residual_perturbation(delta, i, j, k, l, dir_r, dir_s);
            if !p.is_zero() {
                pert_row.push((idx, p));
            }
        }

        // L1 subgradient: Aᵀ·sign(r) instead of Aᵀ·r
        for &(ci, ref pi) in &pert_row {
            atr[ci] = &atr[ci] + &(pi * &sign_r);
            for &(cj, ref pj) in &pert_row {
                ata[ci][cj] = &ata[ci][cj] + &(pi * pj);
            }
        }
    });

    if total_coherence.is_zero() {
        return CongruenceResolution {
            directions: dirs,
            epsilon: vec![Q::zero(); d],
            resolved: true,
            coherence_before: Q::zero(),
            predicted_coherence_after: Q::zero(),
            cohomology_dim: 0,
            kernel: vec![],
        };
    }

    // D.COHOMOLOGY.1: measure the dimension of H^1
    // rank(AᵀA) = number of resolvable directions (coboundaries)
    // d - rank = number of independent obstructions (cohomology classes)
    let ata_rank = matrix::rank(&ata);
    let cohomology_dim = d.saturating_sub(ata_rank);

    // Compute the kernel of AᵀA — the space of cohomological freedom.
    // kernel(AᵀA) = {v : AᵀA·v = 0} — directions where the perturbation
    // Jacobian has no first-order effect on coherence.
    // This IS the space of agency: when non-empty, multiple valid
    // perturbation directions exist and the choice between them
    // is not determined by the cocycle equation.
    let kernel = if cohomology_dim > 0 {
        matrix::nullspace(&ata)
    } else {
        vec![]
    };

    // Solve AᵀA·ε = -Aᵀr — one d×d inversion
    let mut epsilon = match matrix::invert(&ata) {
        Some(ata_inv) => {
            let mut eps = vec![Q::zero(); d];
            for i in 0..d {
                for j in 0..d {
                    eps[i] = &eps[i] - &(&ata_inv[i][j] * &atr[j]);
                }
            }
            eps
        }
        None => {
            // Singular — find the direction with largest |Aᵀr| component
            let best = atr.iter().enumerate()
                .max_by(|(_, a), (_, b)| {
                    let aa = if *a < &Q::zero() { -(*a).clone() } else { (*a).clone() };
                    let bb = if *b < &Q::zero() { -(*b).clone() } else { (*b).clone() };
                    aa.cmp(&bb)
                })
                .map(|(i, _)| i)
                .unwrap_or(0);
            let mut eps = vec![Q::zero(); d];
            let step = Q::new(BigInt::from(1), BigInt::from(20));
            eps[best] = if atr[best] > Q::zero() { -step } else { step };
            eps
        }
    };

    // Cap step size: max component ≤ 1/20
    let max_abs = epsilon.iter()
        .map(|e| if e < &Q::zero() { -e.clone() } else { e.clone() })
        .max()
        .unwrap_or(Q::one());
    let cap = Q::new(BigInt::from(1), BigInt::from(20));
    if max_abs > cap {
        let scale = &cap / &max_abs;
        epsilon = epsilon.iter().map(|e| e * &scale).collect();
    }

    // Predict coherence using the single triple iterator
    let mut predicted_c = Q::zero();
    let eps_ref = &epsilon; // borrow for closure
    for_each_residual(delta, |i, j, k, l, r_val| {
        let mut new_r = r_val.clone();
        for (idx, &(dir_r, dir_s)) in dirs.iter().enumerate() {
            if eps_ref[idx].is_zero() { continue; }
            let pert = residual_perturbation(delta, i, j, k, l, dir_r, dir_s);
            if !pert.is_zero() {
                new_r = &new_r + &(&pert * &eps_ref[idx]);
            }
        }
        if new_r < Q::zero() { predicted_c -= &new_r; } else { predicted_c += &new_r; }
    });

    CongruenceResolution {
        directions: dirs,
        epsilon,
        resolved: true,
        coherence_before: total_coherence,
        predicted_coherence_after: predicted_c,
        cohomology_dim,
        kernel,
    }
}

/// Iterated algebraic resolution.
///
/// Each iteration: decompose → resolve → apply → decompose new residual.
/// The residual shrinks quadratically: each step eliminates the linear
/// component, leaving only quadratic cross-terms from the group product.
/// The next iteration eliminates those. Convergence: residual squares each step.
///
/// This is the algebraic chain rule — not differential calculus.
/// The cocycle equation defines the residual. The perturbation matrix
/// defines the resolution. The group product defines the composition.
/// The iteration defines the convergence.
///
/// Returns the composed operator (product of all iteration operators)
/// and the final resolution state.
pub fn iterated_resolve(
    delta: &Delta,
    max_iterations: usize,
) -> Option<(Operator, CongruenceResolution)> {
    let n = delta.dim;
    let dirs = matrix::independent_dims(n);

    // Start with identity operator — will accumulate compositions
    let mut composed_mat = matrix::identity(n);
    let mut composed_inv = matrix::identity(n);
    let mut current_delta = delta.clone();
    let mut last_resolution = resolve(&current_delta);

    if last_resolution.coherence_before.is_zero() {
        return None; // Already coherent
    }

    for _iter in 0..max_iterations {
        let res = resolve(&current_delta);

        if res.coherence_before.is_zero() {
            break; // Converged
        }

        // Build operator from this iteration's epsilon
        let iter_op = match matrix::operator_from_epsilons(&res.epsilon, &dirs, n, 0) {
            Some(op) => op,
            None => break,
        };

        // Apply to current delta
        let perturbed = match iter_op.apply(&current_delta) {
            Ok(p) => p,
            Err(_) => break,
        };
        current_delta = crate::engine::pi_g_project(&perturbed);

        // Compose: A_total = A_iter · A_previous
        // This is the algebraic chain rule — group product, not sum
        composed_mat = matrix::mul(&iter_op.matrix, &composed_mat);
        composed_inv = matrix::mul(&composed_inv, &iter_op.matrix_inv);

        last_resolution = res;

        // Check convergence: if coherence is very small, stop
        let new_c = crate::engine::coherence_functional(&current_delta);
        if new_c < Q::new(BigInt::from(1), BigInt::from(1000000)) {
            last_resolution.predicted_coherence_after = new_c;
            break;
        }
    }

    let det_val = matrix::det(&composed_mat);
    if det_val <= Q::zero() { return None; }

    let composed_op = Operator {
        id: 0,
        matrix: composed_mat,
        matrix_inv: composed_inv,
        det_sign_positive: true,
    };

    Some((composed_op, last_resolution))
}

/// Single-function entry point: iterated algebraic resolution.
/// Resolves the cocycle congruence through algebraic iteration.
/// Each step is exact. Convergence is quadratic (residual squares each step).
/// Returns None if the state is already coherent.
pub fn propose(delta: &Delta) -> Option<(Operator, CongruenceResolution)> {
    // Scale iterations inversely with dimension — higher dims have larger
    // rational denominators that grow through iteration. For 3×3: 3 iterations.
    // For 4×4+: single resolution (the linear step is already good).
    let iters = if delta.dim <= 3 { 3 } else { 1 };
    iterated_resolve(delta, iters)
}

/// Evaluate a single coordinate in the operator space.
/// Used by the COORDINATE_SWEEP socket command for distributed evaluation.
pub fn evaluate_coordinate_nd(
    delta: &Delta,
    epsilon: &[Q],
    c_before: &Q,
) -> Option<(Q, Q)> {
    let dirs = matrix::independent_dims(delta.dim);
    if epsilon.len() != dirs.len() { return None; }
    let op = matrix::operator_from_epsilons(epsilon, &dirs, delta.dim, 0)?;
    let perturbed = op.apply(delta).ok()?;
    let projected = pi_g_project(&perturbed);
    let c_after = coherence_functional(&projected);
    let c_delta = &c_after - c_before;
    Some((c_after, c_delta))
}

// ─── D.COORD.BASIS.1 — Coordinator as Basis Generator ────────────────

/// The optimal direction ε* in operator space. This is the coordinator's
/// primary output — not an operator, but the BASIS against which all
/// operators are measured.
///
/// α = ⟨vec(A-I), ε*⟩ / ‖ε*‖² — the alignment score.
/// ω from sluice weight — the temporal trust score.
/// (α, ω) together form the complete measurement coordinate.
#[derive(Debug, Clone)]
pub struct OptimalBasis {
    /// The optimal direction ε* ∈ Q^d where d = n(n-1)/2.
    pub direction: Vec<Q>,
    /// The independent operator directions.
    pub dims: Vec<(usize, usize)>,
    /// ‖ε*‖² — precomputed for alignment score denominator.
    pub norm_squared: Q,
    /// C(Δ) at the state where this basis was computed.
    pub coherence: Q,
    /// K-index when computed — for staleness detection.
    pub computed_at_k: u64,
}

impl OptimalBasis {
    /// Compute the optimal basis from a Delta state.
    /// This IS the coordinator's resolve() output, repackaged as a basis.
    pub fn from_delta(delta: &Delta, k_index: u64) -> Self {
        let resolution = resolve(delta);
        let norm: Q = resolution.epsilon.iter()
            .map(|e| if e < &Q::zero() { -e.clone() } else { e.clone() })
            .sum();
        Self {
            direction: resolution.epsilon,
            dims: resolution.directions,
            norm_squared: norm, // L1 norm (name kept for backward compat)
            coherence: resolution.coherence_before,
            computed_at_k: k_index,
        }
    }

    /// D.COORD.ALIGN.1 — Alignment score of any operator against ε*.
    ///
    /// α = ⟨vec(A-I), ε*⟩_Q / ‖ε*‖²_Q
    ///
    /// α = 1:  operator IS the optimal direction exactly
    /// α = 0:  operator is orthogonal (no coherence improvement in this direction)
    /// α < 0:  operator opposes optimal (increases coherence)
    ///
    /// One inner product. O(d) BigRational operations. Exact.
    pub fn alignment_score(&self, operator: &Operator) -> Q {
        if self.norm_squared.is_zero() {
            return Q::zero(); // Basis is zero — state is already coherent
        }

        let n = operator.matrix.len();
        let mut inner_product = Q::zero();

        // Vectorize A - I: extract the antisymmetric perturbation components
        for (idx, &(r, s)) in self.dims.iter().enumerate() {
            if r >= n || s >= n { continue; }
            // The antisymmetric component: (A[r][s] - A[s][r]) / 2
            // For our operators: A[r][s] = ε, A[s][r] = -ε, so component = ε
            let component = &operator.matrix[r][s];
            inner_product = &inner_product + &(component * &self.direction[idx]);
        }

        &inner_product / &self.norm_squared
    }

    /// Is this basis stale? Returns true if it should be recomputed.
    pub fn is_stale(&self, current_k: u64, refresh_interval: u64) -> bool {
        current_k.saturating_sub(self.computed_at_k) >= refresh_interval
    }

    /// D.COORD.GENESIS.1 — Genesis alignment score.
    ///
    /// α_genesis = ⟨vec(A-I), direction_toward_genesis⟩ / ‖direction_toward_genesis‖²
    ///
    /// The direction_toward_genesis is the difference between genesis Delta
    /// and current Delta, projected onto the independent operator dimensions.
    /// High α_genesis = this operator moves toward the axiom foundation.
    /// Low α_genesis = this operator moves away from the axiom foundation.
    ///
    /// (α_local, α_genesis) together: locally coherent AND axiom-grounded,
    /// or locally coherent but drifting from the foundation.
    pub fn genesis_alignment(&self, operator: &Operator, current: &Delta, genesis: &Delta) -> Q {
        let n = current.dim;
        let m = current.m;

        // Compute direction toward genesis: for each independent dim (r,s),
        // the component is the projection of (genesis - current) onto that direction
        let mut genesis_dir = vec![Q::zero(); self.dims.len()];
        let mut genesis_norm_sq = Q::zero();

        for (idx, &(r, s)) in self.dims.iter().enumerate() {
            // Sum across coordinate dimensions m
            let mut component = Q::zero();
            for l in 0..m {
                let diff = &genesis.entries[r][s][l] - &current.entries[r][s][l];
                component = &component + &diff;
            }
            genesis_dir[idx] = component.clone();
            genesis_norm_sq = &genesis_norm_sq + &(&component * &component);
        }

        if genesis_norm_sq.is_zero() {
            return Q::one(); // Already at genesis — perfect alignment by definition
        }

        // Inner product of operator direction with genesis direction
        let mut inner = Q::zero();
        for (idx, &(r, s)) in self.dims.iter().enumerate() {
            if r >= n || s >= n { continue; }
            let component = &operator.matrix[r][s];
            inner = &inner + &(component * &genesis_dir[idx]);
        }

        &inner / &genesis_norm_sq
    }
}

// ─── T.TRANSMUTE.1 — m-Expansion Trigger ─────────────────────────────
//
// The m-expansion trigger fires when transformation is exhausted
// within the current coordinate dimension m.
//
// Condition: after resolve(), if
//   (1) C_after > 0              — residual remains
//   (2) AᵀA is invertible        — n is sufficient (spatial directions available)
//   (3) epsilon is non-zero       — the system attempted resolution
//   (4) C_after / C_before > 9/10 — resolution barely reduced coherence
//   (5) The per-triple residual vectors r_{ijk} ∈ Q^m have rank = m
//       (residuals span all m coordinate dimensions — saturated)
//
// Then: the current m coordinates are fully occupied by the residual
// AND the operator could not reduce it. The relational structure
// requires more coordinate dimensions than m provides.
//
// The new coordinate's initial values derive from the post-resolution
// residual pattern — the component the m-dimensional resolution
// could not capture. Not zero. The residual IS the new axis direction.
//
// Derives from: A.1 (rational state — entries in Q^m),
//               A.4 (group closure — operators in GL_n(Q)),
//               T.3 (cocycle condition — C(Δ) measures path consistency)
//
// Register: T.TRANSMUTE.1 — NOMINATED → LOCKED when implementation verified.

/// Detect coordinate-dimension saturation.
///
/// Returns Some(new_m) when the residual spans all m coordinates
/// and resolve() cannot reduce coherence — signaling that the
/// relational structure requires m+1 coordinate dimensions.
pub fn detect_m_expansion_need(delta: &Delta) -> Option<usize> {
    let resolution = resolve(delta);
    let m = delta.m;

    // Condition 1: residual remains
    if resolution.coherence_before.is_zero() { return None; }

    // Condition 2+3: AᵀA was invertible and produced non-zero epsilon
    let eps_norm: Q = resolution.epsilon.iter()
        .map(|e| if e < &Q::zero() { -e.clone() } else { e.clone() })
        .sum();
    if eps_norm.is_zero() { return None; } // n-expansion territory, not m

    // Condition 4: resolution barely helped (< 10% reduction)
    if resolution.predicted_coherence_after.is_zero() { return None; }
    let ratio = &resolution.predicted_coherence_after / &resolution.coherence_before;
    let threshold = Q::new(BigInt::from(9), BigInt::from(10));
    if ratio <= threshold { return None; } // resolution is working, m is sufficient

    // Condition 5: residual spans all m coordinates
    // Collect per-coordinate coherence: C_l = Σ |R_{ijk,l}|
    let mut c_per_coord = vec![Q::zero(); m];
    for_each_residual(delta, |_i, _j, _k, l, r| {
        if r < &Q::zero() { c_per_coord[l] -= r; } else { c_per_coord[l] += r; }
    });
    // All m coordinates must carry non-zero residual (saturated)
    let all_coords_active = c_per_coord.iter().all(|c| !c.is_zero());
    if !all_coords_active { return None; } // some coords are resolved, m is not saturated

    // All conditions met: m is insufficient
    Some(m + 1)
}

/// Expand coordinate dimension of a Delta from m to new_m.
///
/// The new coordinate's initial values are derived from the residual
/// pattern — specifically, the per-entity mean residual magnitude, which
/// captures the relational signal the current m coordinates cannot express.
/// Not zero — zero would add nothing.
pub fn expand_m(delta: &Delta, new_m: usize) -> Delta {
    assert!(new_m > delta.m);
    let n = delta.dim;
    let old_m = delta.m;
    let mut expanded = Delta::zero(n, new_m);

    // Copy existing coordinates
    for i in 0..n {
        for j in 0..n {
            for l in 0..old_m {
                expanded.entries[i][j][l] = delta.entries[i][j][l].clone();
            }
        }
    }

    // New coordinate: seeded from residual magnitude per pair
    // For each (i,j) with i<j, the new coordinate = mean residual across triples
    // involving (i,j). This captures the relational signal the old m missed.
    let mut pair_residual = vec![vec![Q::zero(); n]; n];
    let mut pair_count = vec![vec![0u64; n]; n];
    for_each_residual(delta, |i, j, _k, _l, r| {
        let abs_r = if r < &Q::zero() { -r.clone() } else { r.clone() };
        pair_residual[i][j] = &pair_residual[i][j] + &abs_r;
        pair_count[i][j] += 1;
    });

    for i in 0..n {
        for j in (i+1)..n {
            if pair_count[i][j] > 0 {
                let mean = &pair_residual[i][j]
                    / &Q::new(BigInt::from(pair_count[i][j] as i64), BigInt::from(1));
                for l in old_m..new_m {
                    expanded.entries[i][j][l] = mean.clone();
                    expanded.entries[j][i][l] = -mean.clone(); // antisymmetry
                }
            }
        }
    }

    expanded
}

// ─── Dimensional Lifting for Memory Anchors ──────────────────────────

/// Lift an epsilon vector from n-dimensional operator space to new_n.
///
/// The old epsilon covers n(n-1)/2 directions. The lifted epsilon covers
/// new_n(new_n-1)/2 directions. Old directions are preserved in the
/// first n(n-1)/2 entries. New directions start at zero — the proven
/// path is valid in the subspace, new coordinates start unexplored.
///
/// Uses the same block-diagonal principle as operator lifting:
/// the old perturbation acts on the old dimensions, identity on the new.
pub fn lift_epsilon(old_eps: &[Q], old_n: usize, new_n: usize) -> Vec<Q> {
    let old_dirs = matrix::independent_dims(old_n);
    let new_dirs = matrix::independent_dims(new_n);
    let mut lifted = vec![Q::zero(); new_dirs.len()];

    // Map old directions to their positions in the new direction list
    for (old_idx, &(r, s)) in old_dirs.iter().enumerate() {
        // Same (r,s) pair appears at the same position in new_dirs
        // because independent_dims iterates r<s in the same order
        if let Some(new_idx) = new_dirs.iter().position(|&(nr, ns)| nr == r && ns == s) {
            lifted[new_idx] = old_eps[old_idx].clone();
        }
    }
    lifted
}

// ─── D.MESH.DIM.1 — Dimensional Emergence (n-expansion) ─────────────

/// Detect if the current state-space dimension n is insufficient.
///
/// When AᵀA from resolve() is rank-deficient (epsilon all zero)
/// but coherence is non-zero, the transformation requires more
/// state-space dimensions (more nodes in the relational field).
/// Returns Some(new_dim) if expansion is needed, None if current is sufficient.
pub fn detect_dimensional_need(delta: &Delta) -> Option<usize> {
    let resolution = resolve(delta);

    // If coherence is zero, no expansion needed
    if resolution.coherence_before.is_zero() { return None; }

    // If resolution didn't change anything (epsilon all zero), dim may be insufficient
    let eps_norm: Q = resolution.epsilon.iter()
        .map(|e| if e < &Q::zero() { -e.clone() } else { e.clone() })
        .sum();
    if eps_norm.is_zero() && resolution.coherence_before > Q::zero() {
        // Can't resolve at current dim — need more dimensions
        return Some(delta.dim + 1);
    }

    // Check if predicted coherence is still high relative to before
    // (resolution only marginally improves → dim may be limiting)
    if resolution.predicted_coherence_after > Q::zero() {
        let ratio = &resolution.predicted_coherence_after / &resolution.coherence_before;
        // If resolution only reduces coherence by <10%, dim might be limiting
        let threshold = Q::new(BigInt::from(9), BigInt::from(10));
        if ratio > threshold {
            return Some(delta.dim + 1);
        }
    }

    None
}

/// Expand a Delta to a higher dimension.
/// The new dimension entries are zero (the new relational axis starts empty).
/// The existing entries are preserved exactly.
pub fn expand_delta(delta: &Delta, new_dim: usize) -> Delta {
    assert!(new_dim > delta.dim);
    let mut expanded = Delta::zero(new_dim, delta.m);
    for i in 0..delta.dim {
        for j in 0..delta.dim {
            expanded.entries[i][j] = delta.entries[i][j].clone();
        }
    }
    expanded
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn qr(n: i64, d: i64) -> Q { Q::new(BigInt::from(n), BigInt::from(d)) }

    fn incoherent_delta() -> Delta {
        // Δ_01=2, Δ_12=3, Δ_02=7. Cocycle requires Δ_02=2+3=5. Residual=2.
        let mut d = Delta::zero(3, 1);
        d.set_antisym(0, 1, vec![qr(2, 1)]);
        d.set_antisym(1, 2, vec![qr(3, 1)]);
        d.set_antisym(0, 2, vec![qr(7, 1)]);
        d
    }

    fn coherent_delta() -> Delta {
        let mut d = Delta::zero(3, 1);
        d.set_antisym(0, 1, vec![qr(1, 1)]);
        d.set_antisym(1, 2, vec![qr(1, 2)]);
        d.set_antisym(0, 2, vec![qr(3, 2)]);
        d
    }

    #[test]
    fn test_decompose_incoherent_has_residuals() {
        let d = incoherent_delta();
        let decomp = decompose(&d);
        assert!(!decomp.is_cocycle);
        assert!(decomp.coherence > Q::zero());
        assert!(!decomp.residuals.is_empty());
    }

    #[test]
    fn test_decompose_coherent_is_cocycle() {
        let d = coherent_delta();
        let decomp = decompose(&d);
        assert!(decomp.is_cocycle);
        assert_eq!(decomp.coherence, Q::zero());
        assert!(decomp.residuals.is_empty());
    }

    #[test]
    fn test_decompose_coherence_positive_for_incoherent() {
        let d = incoherent_delta();
        let decomp = decompose(&d);
        assert!(decomp.coherence > Q::zero(), "Incoherent delta must have positive decomposition coherence");
        // coherence_functional uses L1 (Σ|R|), decompose uses L2² (Σ R²)
        // Both are positive for incoherent deltas, both zero for cocycles.
        let c = coherence_functional(&d);
        assert!(c > Q::zero(), "L1 coherence must also be positive");
    }

    #[test]
    fn test_resolve_produces_epsilon() {
        let d = incoherent_delta();
        let res = resolve(&d);
        assert!(res.resolved);
        assert_eq!(res.epsilon.len(), 3); // 3 independent dims for 3×3
        assert!(res.coherence_before > Q::zero());
    }

    #[test]
    fn test_resolve_predicts_improvement() {
        let d = incoherent_delta();
        let res = resolve(&d);
        assert!(res.predicted_coherence_after < res.coherence_before,
            "Resolution should predict coherence improvement: before={}, predicted={}",
            res.coherence_before, res.predicted_coherence_after);
    }

    #[test]
    fn test_propose_reduces_coherence() {
        let d = incoherent_delta();
        let c_before = coherence_functional(&d);
        if let Some((op, _)) = propose(&d) {
            let result = op.apply(&d).unwrap();
            let projected = pi_g_project(&result);
            let c_after = coherence_functional(&projected);
            assert!(c_after < c_before,
                "Proposal should reduce coherence: before={}, after={}", c_before, c_after);
        } else {
            panic!("Must produce a proposal for incoherent state");
        }
    }

    #[test]
    fn test_propose_4x4() {
        let mut d = Delta::zero(4, 1);
        d.set_antisym(0, 1, vec![qr(1, 1)]);
        d.set_antisym(0, 2, vec![qr(3, 1)]);
        d.set_antisym(1, 2, vec![qr(7, 1)]); // not cocycle
        let c_before = coherence_functional(&d);
        assert!(c_before > Q::zero());
        if let Some((op, _)) = propose(&d) {
            let result = op.apply(&d).unwrap();
            let projected = pi_g_project(&result);
            let c_after = coherence_functional(&projected);
            assert!(c_after < c_before, "4×4 proposal should reduce coherence");
        }
    }

    #[test]
    fn test_propose_coherent_returns_none() {
        let d = coherent_delta();
        assert!(propose(&d).is_none(), "Coherent state should produce no proposal");
    }

    #[test]
    fn test_resolution_dimension_agnostic() {
        let mut d = Delta::zero(5, 1);
        d.set_antisym(0, 1, vec![qr(1, 1)]);
        d.set_antisym(0, 2, vec![qr(2, 1)]);
        d.set_antisym(1, 2, vec![qr(5, 1)]); // not cocycle
        let res = resolve(&d);
        assert_eq!(res.directions.len(), 10); // 5×4/2 = 10
        assert_eq!(res.epsilon.len(), 10);
        assert!(res.resolved);
    }

    #[test]
    fn test_iterated_resolution_converges_more() {
        let d = incoherent_delta();
        let c_before = coherence_functional(&d);

        // Single resolution
        let single_res = resolve(&d);
        let single_op = matrix::operator_from_epsilons(
            &single_res.epsilon, &single_res.directions, 3, 0,
        ).unwrap();
        let single_result = pi_g_project(&single_op.apply(&d).unwrap());
        let c_single = coherence_functional(&single_result);

        // Iterated resolution (5 iterations)
        let (iter_op, _) = propose(&d).unwrap();
        let iter_result = pi_g_project(&iter_op.apply(&d).unwrap());
        let c_iterated = coherence_functional(&iter_result);

        assert!(c_single < c_before, "Single resolution must improve");
        assert!(c_iterated <= c_single,
            "Iterated resolution must be at least as good as single: single={}, iterated={}",
            c_single, c_iterated);
    }

    #[test]
    fn test_single_resolution_4x4() {
        // 4×4 single resolution (iterated is expensive at higher dims)
        let mut d = Delta::zero(4, 1);
        d.set_antisym(0, 1, vec![qr(1, 1)]);
        d.set_antisym(0, 2, vec![qr(3, 1)]);
        d.set_antisym(1, 2, vec![qr(7, 1)]); // breaks cocycle
        let _c_before = coherence_functional(&d);
        let res = resolve(&d);
        assert!(res.predicted_coherence_after < res.coherence_before,
            "4×4 resolution must predict improvement");
    }

    #[test]
    fn test_perturbation_matrix_correct() {
        let d = incoherent_delta();
        let decomp = decompose(&d);
        // Verify perturbation is consistent with actual operator application
        let dirs = matrix::independent_dims(3);
        let eps = vec![qr(1, 100), Q::zero(), Q::zero()]; // small perturbation in direction 0
        let op = matrix::operator_from_epsilons(&eps, &dirs, 3, 0).unwrap();
        let perturbed = op.apply(&d).unwrap();
        let projected = pi_g_project(&perturbed);

        // The linear model predicts the residual change
        for res in &decomp.residuals {
            let predicted_change = residual_perturbation(&d, res.i, res.j, res.k, res.l, dirs[0].0, dirs[0].1)
                * &qr(1, 100);
            // This should be close to the actual change (up to O(ε²))
            let actual_new_residual = &projected.entries[res.i][res.k][res.l]
                - &projected.entries[res.i][res.j][res.l]
                - &projected.entries[res.j][res.k][res.l];
            let predicted_new = &res.value + &predicted_change;
            let diff = &actual_new_residual - &predicted_new;
            let abs_diff = if diff < Q::zero() { -diff } else { diff };
            // O(ε²) = O(1/10000) — should be small
            assert!(abs_diff < qr(1, 10),
                "Perturbation model must match actual to O(ε²)");
        }
    }

    // ─── Alignment score tests ────────────────────────────────────

    #[test]
    fn test_optimal_basis_from_incoherent() {
        let d = incoherent_delta();
        let basis = OptimalBasis::from_delta(&d, 0);
        assert!(basis.norm_squared > Q::zero(), "Basis must be non-zero for incoherent state");
        assert!(basis.coherence > Q::zero());
    }

    #[test]
    fn test_optimal_basis_from_coherent_is_zero() {
        let d = coherent_delta();
        let basis = OptimalBasis::from_delta(&d, 0);
        assert_eq!(basis.norm_squared, Q::zero(), "Coherent state has zero basis");
    }

    #[test]
    fn test_alignment_score_of_optimal_operator() {
        let d = incoherent_delta();
        let basis = OptimalBasis::from_delta(&d, 0);

        // Build an operator exactly aligned with ε*
        if let Some(op) = matrix::operator_from_epsilons(&basis.direction, &basis.dims, 3, 0) {
            let alpha = basis.alignment_score(&op);
            // Should be close to 1 (exact alignment) — may not be exactly 1
            // because operator_from_epsilons adds antisymmetric perturbation
            assert!(alpha > Q::zero(), "Optimal operator must have positive alignment");
        }
    }

    #[test]
    fn test_alignment_score_of_identity_is_zero() {
        let d = incoherent_delta();
        let basis = OptimalBasis::from_delta(&d, 0);
        let id_op = Operator {
            id: 0,
            matrix: matrix::identity(3),
            matrix_inv: matrix::identity(3),
            det_sign_positive: true,
        };
        let alpha = basis.alignment_score(&id_op);
        assert_eq!(alpha, Q::zero(), "Identity operator has zero alignment");
    }

    #[test]
    fn test_alignment_score_opposite_direction() {
        let d = incoherent_delta();
        let basis = OptimalBasis::from_delta(&d, 0);

        // Build operator in the OPPOSITE direction
        let neg_direction: Vec<Q> = basis.direction.iter().map(|e| -e.clone()).collect();
        if let Some(op) = matrix::operator_from_epsilons(&neg_direction, &basis.dims, 3, 0) {
            let alpha = basis.alignment_score(&op);
            assert!(alpha < Q::zero(), "Opposite direction must have negative alignment");
        }
    }

    #[test]
    fn test_basis_staleness() {
        let d = incoherent_delta();
        let basis = OptimalBasis::from_delta(&d, 100);
        assert!(!basis.is_stale(105, 10));
        assert!(basis.is_stale(115, 10));
    }

    // ─── D.COORD.GENESIS.1 tests ─────────────────────────────────

    #[test]
    fn test_genesis_alignment_at_genesis() {
        let d = coherent_delta();
        let genesis = coherent_delta(); // same as current = at genesis
        let basis = OptimalBasis::from_delta(&d, 0);
        let id_op = Operator {
            id: 0, matrix: matrix::identity(3), matrix_inv: matrix::identity(3),
            det_sign_positive: true,
        };
        let alpha_g = basis.genesis_alignment(&id_op, &d, &genesis);
        assert_eq!(alpha_g, Q::one(), "At genesis → α_genesis = 1");
    }

    #[test]
    fn test_genesis_alignment_away_from_genesis() {
        let current = incoherent_delta();
        let genesis = coherent_delta();
        let basis = OptimalBasis::from_delta(&current, 0);

        // Build an operator that moves AWAY from genesis
        let dirs = matrix::independent_dims(3);
        let mut away_eps = vec![Q::zero(); dirs.len()];
        // Direction away = current - genesis, so operator in THAT direction moves further away
        for (idx, &(r, s)) in dirs.iter().enumerate() {
            away_eps[idx] = &current.entries[r][s][0] - &genesis.entries[r][s][0];
        }
        if let Some(away_op) = matrix::operator_from_epsilons(&away_eps, &dirs, 3, 0) {
            let alpha_g = basis.genesis_alignment(&away_op, &current, &genesis);
            // Moving away from genesis should give negative α_genesis
            // (inner product of away-direction with toward-genesis is negative)
            assert!(alpha_g < Q::zero() || alpha_g.is_zero(),
                "Moving away from genesis → α_genesis ≤ 0, got {}", alpha_g);
        }
    }

    // ─── D.MESH.DIM.1 tests ──────────────────────────────────────

    #[test]
    fn test_no_dimensional_need_when_coherent() {
        let d = coherent_delta();
        assert_eq!(detect_dimensional_need(&d), None);
    }

    #[test]
    fn test_expand_delta_preserves_entries() {
        let d = incoherent_delta();
        let expanded = expand_delta(&d, 5);
        assert_eq!(expanded.dim, 5);
        assert_eq!(expanded.m, d.m);
        // Original entries preserved
        for i in 0..3 {
            for j in 0..3 {
                assert_eq!(expanded.entries[i][j], d.entries[i][j]);
            }
        }
        // New entries are zero
        for j in 0..5 {
            assert_eq!(expanded.entries[3][j][0], Q::zero());
            assert_eq!(expanded.entries[4][j][0], Q::zero());
        }
    }

    // ─── T.TRANSMUTE.1 — m-Expansion Tests ──────────────────────────

    #[test]
    fn test_coherent_delta_no_m_expansion() {
        let d = coherent_delta();
        assert!(detect_m_expansion_need(&d).is_none(),
            "coherent state must not trigger m-expansion");
    }

    #[test]
    fn test_expand_m_preserves_existing_coords() {
        let mut d = Delta::zero(3, 1);
        d.set_antisym(0, 1, vec![qr(1, 1)]);
        d.set_antisym(1, 2, vec![qr(1, 2)]);
        d.set_antisym(0, 2, vec![qr(3, 2)]);

        let expanded = expand_m(&d, 3);
        assert_eq!(expanded.dim, 3);
        assert_eq!(expanded.m, 3);

        // First coordinate preserved exactly
        for i in 0..3 {
            for j in 0..3 {
                assert_eq!(expanded.entries[i][j][0], d.entries[i][j][0],
                    "existing coord must be preserved at ({},{})", i, j);
            }
        }
    }

    #[test]
    fn test_expand_m_new_coords_from_residual() {
        // Build an incoherent delta so residuals exist
        let mut d = Delta::zero(3, 1);
        d.set_antisym(0, 1, vec![qr(1, 1)]);
        d.set_antisym(1, 2, vec![qr(1, 2)]);
        d.set_antisym(0, 2, vec![qr(1, 3)]); // NOT 3/2 → incoherent

        let expanded = expand_m(&d, 2);
        assert_eq!(expanded.m, 2);

        // New coordinate should be non-zero (seeded from residual)
        let mut has_nonzero = false;
        for i in 0..3 {
            for j in 0..3 {
                if !expanded.entries[i][j][1].is_zero() {
                    has_nonzero = true;
                }
            }
        }
        assert!(has_nonzero, "new coordinate must be seeded from residual, not zero");

        // Antisymmetry preserved in new coordinate
        for i in 0..3 {
            for j in 0..3 {
                let sum = &expanded.entries[i][j][1] + &expanded.entries[j][i][1];
                assert!(sum.is_zero(),
                    "antisymmetry must hold in new coord at ({},{})", i, j);
            }
        }
    }

    #[test]
    fn test_expand_m_coherent_gives_zero_new_coords() {
        // Coherent delta: no residuals → new coord should be zero
        let d = coherent_delta();
        let expanded = expand_m(&d, 2);

        for i in 0..3 {
            for j in 0..3 {
                assert!(expanded.entries[i][j][1].is_zero(),
                    "coherent delta should produce zero new coord at ({},{})", i, j);
            }
        }
    }
}
