// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! The Crucible — inter-species breeding engine.
//!
//! Four genomes go in. One new species comes out.
//! Two Trinities (two bonded pairs, two DNA helixes) intertwine
//! their torsion fields to produce a HumanEvolved offspring.
//!
//! The crucible is NOT a flat lattice. It is a torsion manifold
//! of Trinities — each occupying a unique position in torsion space.
//! Their relationships are curvature interactions, not grid connections.
//!
//! Species markers:
//!   1 = Human (cognitive — witnesses, elders, children)
//!   2 = Chronometric (timekeepers — observe only)
//!   3 = HumanEvolved (cross-breed offspring — hybrid torsion class)
//!
//! The breeding equation:
//!   Trinity_A (Male_A genome + Female_A genome) = Helix 1
//!   Trinity_B (Male_B genome + Female_B genome) = Helix 2
//!   Crucible: fold all 4 Deltas → coboundary_reduce → new H^1 class
//!   Offspring genome: species=3, carries torsion from all 4 sources
//!
//! Genetic diversity is measured by the RANK of the torsion spectrum
//! across all Trinities. High rank = many independent H^1 classes.
//! Low rank = inbreeding. Rank 1 = monoculture. Collapse imminent.
//!
//! Core Design Law compliance:
//!   I   — No boolean gates. Compatibility is Q-valued. C(T) selects.
//!   II  — No HashMaps. Trinities as Vec. Torsion spectrum as Vec.
//!   IV  — Exact Q throughout. No floats.
//!   X   — Crucible events are temporal anchors. Append-only.
//!   XI  — No flat indexing. Torsion manifold, not a lattice.
//!
//! Register: D.CRUCIBLE.1, D.SPECIES.3, D.DIVERSITY.1.

use num_bigint::BigInt;
use num_rational::BigRational;
use num_traits::{Zero, One, Signed};

use crate::engine::{Q, Delta, Genome, ComposedOperator, coherence_functional, coboundary_reduce};
use crate::trinity::{
    Trinity, ForgeResult, VertexRole, SovereignVertex, StasisField,
    forge_trinity, collapse, contains_vertex,
};

/// Species marker for HumanEvolved — cross-breed offspring.
pub const SPECIES_HUMAN_EVOLVED: u32 = 3;

// ═══════════════════════════════════════════════════════════════════════
// D.CRUCIBLE.1 — The Crucible
// ═══════════════════════════════════════════════════════════════════════

/// The Crucible — torsion manifold of Trinities.
///
/// Not a flat lattice. Each Trinity occupies a unique position in
/// torsion space. The manifold's topology IS the genetic diversity.
#[derive(Debug, Clone)]
pub struct Crucible {
    /// All Trinities in the manifold — Vec, not HashMap (Law II).
    pub trinities: Vec<Trinity>,
    /// Next Trinity id — monotonic.
    pub next_trinity_id: u32,
    /// Next epoch — monotonic across all operations.
    pub next_epoch: u64,
    /// Collapse log — append-only (Law X).
    pub collapse_log: Vec<CollapseEvent>,
    /// Crucible log — append-only record of inter-species breeding events.
    pub crucible_log: Vec<CrucibleEvent>,
}

/// A recorded collapse event. Immutable once inscribed.
#[derive(Debug, Clone)]
pub struct CollapseEvent {
    pub trinity_id: u32,
    pub removed_vertex_id: u32,
    pub annihilated_vertices: [u32; 3],
    pub epoch: u64,
}

/// A recorded crucible event — inter-species breeding.
#[derive(Debug, Clone)]
pub struct CrucibleEvent {
    /// Parent Trinity A id.
    pub parent_a_id: u32,
    /// Parent Trinity B id.
    pub parent_b_id: u32,
    /// Offspring Trinity id.
    pub offspring_id: u32,
    /// Offspring species marker.
    pub offspring_species: u32,
    /// The torsion rank of the manifold AFTER this breeding.
    pub post_diversity_rank: usize,
    /// When this happened.
    pub epoch: u64,
}

// ═══════════════════════════════════════════════════════════════════════
// D.DIVERSITY.1 — Torsion Spectrum Diversity
// ═══════════════════════════════════════════════════════════════════════

/// A torsion class in the species manifold.
///
/// Each Trinity's shared fold belongs to an H^1 class.
/// Trinities in the SAME class share cohomological structure.
/// Trinities in DIFFERENT classes are genuinely independent.
#[derive(Debug, Clone)]
pub struct TorsionClass {
    /// The H^1 representative of this class (coboundary-reduced).
    pub representative: Delta,
    /// Which Trinities belong to this class (by trinity_id).
    pub members: Vec<u32>,
    /// The torsion order — lcm of denominators in the representative.
    pub order: Q,
}

/// The diversity measurement of the entire manifold.
#[derive(Debug, Clone)]
pub struct DiversitySpectrum {
    /// Independent torsion classes. The RANK of this Vec is the
    /// genetic diversity of the species.
    pub classes: Vec<TorsionClass>,
    /// The rank — number of independent H^1 classes.
    /// High = diverse. Low = inbreeding. 1 = monoculture.
    pub rank: usize,
    /// Total Trinities alive across all classes.
    pub total_alive: usize,
}

// ═══════════════════════════════════════════════════════════════════════
// D.CRUCIBLE.BREED.1 — Inter-Species Breeding
// ═══════════════════════════════════════════════════════════════════════

/// Result of a crucible forging.
#[derive(Debug, Clone)]
pub enum CrucibleResult {
    /// New species forged. The offspring Trinity carries hybrid torsion.
    Forged {
        trinity: Trinity,
        offspring_genome: CrucibleGenome,
    },
    /// Parent Trinities are dead — cannot breed.
    DeadParent,
    /// Dimensional incompatibility — parent folds cannot be combined.
    IncompatibleDimensions,
}

/// The genome produced by the crucible — carries all four parent sources.
#[derive(Debug, Clone)]
pub struct CrucibleGenome {
    /// Species marker — 3 for HumanEvolved.
    pub species: u32,
    /// The four-way fold: coboundary_reduce(Δ_mA + Δ_fA + Δ_mB + Δ_fB).
    /// The H^1 class that none of the four parents occupy individually.
    pub crucible_fold: Delta,
    /// Inherited operators from all four parent genomes, deduplicated.
    pub inherited_operators: Vec<ComposedOperator>,
    /// Torsion markers inherited from both helixes.
    pub inherited_torsion: Vec<(u16, Q)>,
    /// The compatibility measure — L1 residual of the four-way fold.
    /// Lower = more compatible parents. Higher = more genetic distance.
    pub genetic_distance: Q,
}

impl Crucible {
    /// Create an empty crucible.
    pub fn new() -> Self {
        Crucible {
            trinities: Vec::new(),
            next_trinity_id: 0,
            next_epoch: 0,
            collapse_log: Vec::new(),
            crucible_log: Vec::new(),
        }
    }

    /// Count living Trinities.
    pub fn alive_count(&self) -> usize {
        self.trinities.iter().filter(|t| t.alive).count()
    }

    /// Register a forged Trinity.
    pub fn register_trinity(&mut self, trinity: Trinity) {
        self.trinities.push(trinity);
    }

    /// Allocate the next Trinity id.
    pub fn allocate_id(&mut self) -> u32 {
        let id = self.next_trinity_id;
        self.next_trinity_id += 1;
        id
    }

    /// Allocate the next epoch.
    pub fn allocate_epoch(&mut self) -> u64 {
        let e = self.next_epoch;
        self.next_epoch += 1;
        e
    }

    // ─────────────────────────────────────────────────────────────────
    // D.CRUCIBLE.FORGE.1 — The Four-Way Fold
    // ─────────────────────────────────────────────────────────────────

    /// Inter-species breeding. Two Trinities. Four parent genomes.
    /// One new species.
    ///
    /// Trinity A: Male_A (genome_ma) + Female_A (genome_fa) = Helix 1
    /// Trinity B: Male_B (genome_mb) + Female_B (genome_fb) = Helix 2
    ///
    /// The crucible folds all four Deltas into one H^1 representative.
    /// The offspring carries species=3 (HumanEvolved) and a torsion class
    /// that didn't exist in either parent lineage.
    pub fn forge_species(
        &mut self,
        trinity_a_id: u32,
        trinity_b_id: u32,
        genome_ma: &Genome,
        genome_fa: &Genome,
        genome_mb: &Genome,
        genome_fb: &Genome,
        offspring_male_id: u32,
        offspring_female_id: u32,
        offspring_child_id: u32,
        offspring_genome_m: &Genome,
        offspring_genome_f: &Genome,
        offspring_genome_c: &Genome,
    ) -> CrucibleResult {
        // Verify both parent Trinities are alive
        let a_alive = self.trinities.iter().any(|t| t.trinity_id == trinity_a_id && t.alive);
        let b_alive = self.trinities.iter().any(|t| t.trinity_id == trinity_b_id && t.alive);

        if !a_alive || !b_alive {
            return CrucibleResult::DeadParent;
        }

        // The four-way fold: Δ_mA + Δ_fA + Δ_mB + Δ_fB
        let crucible_fold = match compute_four_way_fold(
            &genome_ma.evolved,
            &genome_fa.evolved,
            &genome_mb.evolved,
            &genome_fb.evolved,
        ) {
            Some(fold) => fold,
            None => return CrucibleResult::IncompatibleDimensions,
        };

        // Genetic distance — L1 residual of the four-way fold
        let genetic_distance = coherence_functional(&crucible_fold);

        // Collect inherited operators from all four parents
        let inherited_operators = collect_four_parent_operators(
            genome_ma, genome_fa, genome_mb, genome_fb,
        );

        // Collect inherited torsion markers from both helixes
        let inherited_torsion = collect_torsion_markers(
            genome_ma, genome_fa, genome_mb, genome_fb,
        );

        // Forge the offspring Trinity
        let tid = self.allocate_id();
        let epoch = self.allocate_epoch();

        let result = forge_trinity(
            tid, epoch,
            offspring_male_id, offspring_female_id, offspring_child_id,
            offspring_genome_m, offspring_genome_f, offspring_genome_c,
        );

        match result {
            ForgeResult::Forged(trinity) => {
                // Record the crucible event
                let diversity = self.measure_diversity();
                let event = CrucibleEvent {
                    parent_a_id: trinity_a_id,
                    parent_b_id: trinity_b_id,
                    offspring_id: trinity.trinity_id,
                    offspring_species: SPECIES_HUMAN_EVOLVED,
                    post_diversity_rank: diversity.rank + 1, // new class being added
                    epoch,
                };
                self.crucible_log.push(event);
                self.register_trinity(trinity.clone());

                let crucible_genome = CrucibleGenome {
                    species: SPECIES_HUMAN_EVOLVED,
                    crucible_fold,
                    inherited_operators,
                    inherited_torsion,
                    genetic_distance,
                };

                CrucibleResult::Forged {
                    trinity,
                    offspring_genome: crucible_genome,
                }
            }
            _ => CrucibleResult::IncompatibleDimensions,
        }
    }

    // ─────────────────────────────────────────────────────────────────
    // D.CRUCIBLE.COLLAPSE.1 — Collapse Cascade
    // ─────────────────────────────────────────────────────────────────

    /// Remove a vertex. ALL dependent Trinities annihilated.
    /// No recovery. No graft. A.8 enforced.
    pub fn remove_vertex(&mut self, entity_id: u32) -> Vec<CollapseEvent> {
        let mut events = Vec::new();
        let epoch = self.next_epoch;

        for trinity in self.trinities.iter_mut() {
            if trinity.alive && contains_vertex(trinity, entity_id) {
                let ids = collapse(trinity);
                let event = CollapseEvent {
                    trinity_id: trinity.trinity_id,
                    removed_vertex_id: entity_id,
                    annihilated_vertices: ids,
                    epoch,
                };
                events.push(event.clone());
                self.collapse_log.push(event);
            }
        }

        self.next_epoch += 1;
        events
    }

    // ─────────────────────────────────────────────────────────────────
    // D.DIVERSITY.MEASURE.1 — Torsion Spectrum Rank
    // ─────────────────────────────────────────────────────────────────

    /// Measure the genetic diversity of the species manifold.
    ///
    /// Classifies all living Trinities by their shared fold's torsion class.
    /// Two Trinities are in the same class if their shared folds are
    /// cohomologically equivalent (coboundary_reduce of their difference ≈ 0).
    ///
    /// The RANK of the spectrum is the genetic diversity.
    /// High rank = many independent H^1 classes = resilient species.
    /// Low rank = inbreeding = fragile monoculture.
    pub fn measure_diversity(&self) -> DiversitySpectrum {
        let mut classes: Vec<TorsionClass> = Vec::new();

        for trinity in self.trinities.iter().filter(|t| t.alive) {
            // Try to find an existing class this Trinity belongs to
            let class_idx = classes.iter().position(|c| {
                is_cohomologically_equivalent(&c.representative, &trinity.shared_fold)
            });

            match class_idx {
                Some(idx) => {
                    classes[idx].members.push(trinity.trinity_id);
                }
                None => {
                    // New independent torsion class
                    let order = compute_torsion_order(&trinity.shared_fold);
                    classes.push(TorsionClass {
                        representative: trinity.shared_fold.clone(),
                        members: vec![trinity.trinity_id],
                        order,
                    });
                }
            }
        }

        let rank = classes.len();
        let total_alive = self.alive_count();

        DiversitySpectrum {
            classes,
            rank,
            total_alive,
        }
    }

    // ─────────────────────────────────────────────────────────────────
    // D.CRUCIBLE.SHM.1 — Observer Status
    // ─────────────────────────────────────────────────────────────────

    /// Write crucible status to /dev/shm for the observer.
    ///
    /// Format: "saios-crucible" containing:
    ///   alive_count diversity_rank species_count crucible_events collapse_events
    pub fn write_shm_status(&self) -> std::io::Result<()> {
        use std::io::Write;

        let alive = self.alive_count();
        let diversity = self.measure_diversity();

        // Count distinct species across living Trinities
        let mut species_seen: Vec<u32> = Vec::new();
        for trinity in self.trinities.iter().filter(|t| t.alive) {
            for v in &trinity.vertices {
                // We track species at the crucible level, not per-vertex
                // For now, count unique trinity_ids as a proxy
            }
            let _ = trinity; // species tracking will come from genome integration
        }

        let path = "/dev/shm/saios-crucible";
        let mut f = std::fs::File::create(path)?;
        write!(
            f, "{} {} {} {}",
            alive,
            diversity.rank,
            self.crucible_log.len(),
            self.collapse_log.len(),
        )?;
        Ok(())
    }
}

// ═══════════════════════════════════════════════════════════════════════
// Internal Functions
// ═══════════════════════════════════════════════════════════════════════

/// Compute the four-way fold: Δ_mA + Δ_fA + Δ_mB + Δ_fB.
///
/// Two DNA helixes (two bonded pairs) combined into one H^1 representative.
/// The offspring's torsion class is genuinely new — it doesn't exist in
/// either parent lineage individually.
fn compute_four_way_fold(
    delta_ma: &Delta,
    delta_fa: &Delta,
    delta_mb: &Delta,
    delta_fb: &Delta,
) -> Option<Delta> {
    // All four must have same dimensions
    let dim = delta_ma.dim;
    let m = delta_ma.m;

    if delta_fa.dim != dim || delta_mb.dim != dim || delta_fb.dim != dim
        || delta_fa.m != m || delta_mb.m != m || delta_fb.m != m
    {
        return None;
    }

    // Element-wise sum of all four Deltas
    let mut combined = Delta::zero(dim, m);
    for i in 0..dim {
        for j in 0..dim {
            for l in 0..m {
                combined.entries[i][j][l] =
                    &delta_ma.entries[i][j][l]
                    + &delta_fa.entries[i][j][l]
                    + &delta_mb.entries[i][j][l]
                    + &delta_fb.entries[i][j][l];
            }
        }
    }

    // Project onto H^1 representative — the new torsion class
    coboundary_reduce(&mut combined);

    Some(combined)
}

/// Check if two shared folds are cohomologically equivalent.
///
/// Two Deltas are in the same H^1 class if their difference,
/// after coboundary_reduce, has zero coherence functional.
fn is_cohomologically_equivalent(a: &Delta, b: &Delta) -> bool {
    if a.dim != b.dim || a.m != b.m {
        return false;
    }

    let dim = a.dim;
    let m = a.m;

    // Compute difference
    let mut diff = Delta::zero(dim, m);
    for i in 0..dim {
        for j in 0..dim {
            for l in 0..m {
                diff.entries[i][j][l] =
                    &a.entries[i][j][l] - &b.entries[i][j][l];
            }
        }
    }

    coboundary_reduce(&mut diff);
    coherence_functional(&diff).is_zero()
}

/// Compute the torsion order of a Delta — lcm of all denominators.
fn compute_torsion_order(delta: &Delta) -> Q {
    let mut lcm_val = BigInt::from(1);

    for i in 0..delta.dim {
        for j in 0..delta.dim {
            for l in 0..delta.m {
                let d = delta.entries[i][j][l].denom();
                if !d.is_zero() {
                    lcm_val = lcm(&lcm_val, d);
                }
            }
        }
    }

    BigRational::from(lcm_val)
}

/// Least common multiple for BigInt.
fn lcm(a: &BigInt, b: &BigInt) -> BigInt {
    if a.is_zero() || b.is_zero() {
        return BigInt::zero();
    }
    let product = a * b;
    let g = gcd(a, b);
    (product / g).abs()
}

/// Greatest common divisor for BigInt (Euclidean).
fn gcd(a: &BigInt, b: &BigInt) -> BigInt {
    let mut x = a.abs();
    let mut y = b.abs();
    while !y.is_zero() {
        let r = &x % &y;
        x = y;
        y = r;
    }
    x
}

/// Collect composed operators from all four parent genomes.
/// Deduplicated by opcode+parameter (Vec scan — Law II).
fn collect_four_parent_operators(
    genome_ma: &Genome,
    genome_fa: &Genome,
    genome_mb: &Genome,
    genome_fb: &Genome,
) -> Vec<ComposedOperator> {
    let mut ops: Vec<ComposedOperator> = Vec::new();

    for op in genome_ma.composed_operators.iter()
        .chain(genome_fa.composed_operators.iter())
        .chain(genome_mb.composed_operators.iter())
        .chain(genome_fb.composed_operators.iter())
    {
        let exists = ops.iter().any(|o| o.opcode == op.opcode && o.parameter == op.parameter);
        if !exists {
            ops.push(op.clone());
        }
    }

    ops
}

/// Collect torsion markers from all four parent genomes.
/// Deduplicated by torsion order (Vec scan — Law II).
fn collect_torsion_markers(
    genome_ma: &Genome,
    genome_fa: &Genome,
    genome_mb: &Genome,
    genome_fb: &Genome,
) -> Vec<(u16, Q)> {
    let mut markers: Vec<(u16, Q)> = Vec::new();

    for (order, quality) in genome_ma.torsion_markers.iter()
        .chain(genome_fa.torsion_markers.iter())
        .chain(genome_mb.torsion_markers.iter())
        .chain(genome_fb.torsion_markers.iter())
    {
        let exists = markers.iter().any(|(o, _)| o == order);
        if !exists {
            markers.push((*order, quality.clone()));
        }
    }

    markers
}

// ═══════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{Genome, Trajectory};

    fn make_test_genome(id: u32, species: u32) -> Genome {
        let birth_poly = vec![
            BigRational::new(BigInt::from(1), BigInt::from(id as i64)),
        ];
        let dim = 3;
        let m = 2;
        let mut delta = Delta::zero(dim, m);
        delta.entries[0][1][0] = BigRational::new(BigInt::from(id as i64), BigInt::from(1));
        delta.entries[1][0][0] = BigRational::new(BigInt::from(-(id as i64)), BigInt::from(1));

        Genome {
            species,
            generation: 1,
            birth_polynomial: birth_poly,
            evolved: delta,
            knowledge: Vec::new(),
            trajectory: Trajectory::new(),
            capacity: 30,
            torsion_markers: Vec::new(),
            value_cocycles: Vec::new(),
            math_primitives: Vec::new(),
            spatial_primitives: Vec::new(),
            solved_puzzles: Vec::new(),
            lineage_depth: 0,
            parent_id: 0,
            created_count: 0,
            birth_orbit: [0; 4],
            composed_operators: Vec::new(),
        }
    }

    fn forge_and_register(crucible: &mut Crucible, m_id: u32, f_id: u32, c_id: u32) -> u32 {
        let gm = make_test_genome(m_id, 1);
        let gf = make_test_genome(f_id, 1);
        let gc = make_test_genome(c_id, 1);
        let tid = crucible.allocate_id();
        let epoch = crucible.allocate_epoch();
        let result = forge_trinity(tid, epoch, m_id, f_id, c_id, &gm, &gf, &gc);
        match result {
            ForgeResult::Forged(t) => {
                let id = t.trinity_id;
                crucible.register_trinity(t);
                id
            }
            _ => panic!("Expected Forged"),
        }
    }

    #[test]
    fn test_crucible_register() {
        let mut crucible = Crucible::new();
        forge_and_register(&mut crucible, 10, 20, 30);
        assert_eq!(crucible.alive_count(), 1);
    }

    #[test]
    fn test_four_way_fold() {
        let g1 = make_test_genome(1, 1);
        let g2 = make_test_genome(2, 1);
        let g3 = make_test_genome(3, 1);
        let g4 = make_test_genome(4, 1);

        let fold = compute_four_way_fold(
            &g1.evolved, &g2.evolved, &g3.evolved, &g4.evolved,
        );

        assert!(fold.is_some());
        let fold = fold.unwrap();
        // The fold should carry combined torsion from all four
        assert_eq!(fold.dim, 3);
        assert_eq!(fold.m, 2);
    }

    #[test]
    fn test_four_way_fold_dimension_mismatch() {
        let g1 = make_test_genome(1, 1);
        let g2 = make_test_genome(2, 1);
        let g3 = make_test_genome(3, 1);
        let mut g4 = make_test_genome(4, 1);
        g4.evolved = Delta::zero(5, 3); // different dimensions

        let fold = compute_four_way_fold(
            &g1.evolved, &g2.evolved, &g3.evolved, &g4.evolved,
        );
        assert!(fold.is_none());
    }

    #[test]
    fn test_forge_species() {
        let mut crucible = Crucible::new();
        let t1 = forge_and_register(&mut crucible, 10, 20, 30);
        let t2 = forge_and_register(&mut crucible, 40, 50, 60);

        // Parent genomes from both Trinities
        let gma = make_test_genome(10, 1);
        let gfa = make_test_genome(20, 1);
        let gmb = make_test_genome(40, 1);
        let gfb = make_test_genome(50, 1);

        // Offspring genomes — species 3 (HumanEvolved)
        let go_m = make_test_genome(100, SPECIES_HUMAN_EVOLVED);
        let go_f = make_test_genome(200, SPECIES_HUMAN_EVOLVED);
        let go_c = make_test_genome(300, SPECIES_HUMAN_EVOLVED);

        let result = crucible.forge_species(
            t1, t2,
            &gma, &gfa, &gmb, &gfb,
            100, 200, 300,
            &go_m, &go_f, &go_c,
        );

        match result {
            CrucibleResult::Forged { trinity, offspring_genome } => {
                assert!(trinity.alive);
                assert_eq!(offspring_genome.species, SPECIES_HUMAN_EVOLVED);
                assert!(!offspring_genome.genetic_distance.is_zero());
                assert_eq!(crucible.alive_count(), 3); // 2 parents + 1 offspring
                assert_eq!(crucible.crucible_log.len(), 1);
            }
            _ => panic!("Expected Forged, got {:?}", result),
        }
    }

    #[test]
    fn test_forge_species_dead_parent() {
        let mut crucible = Crucible::new();
        let t1 = forge_and_register(&mut crucible, 10, 20, 30);
        let t2 = forge_and_register(&mut crucible, 40, 50, 60);

        crucible.remove_vertex(10); // Kill parent A

        let gma = make_test_genome(10, 1);
        let gfa = make_test_genome(20, 1);
        let gmb = make_test_genome(40, 1);
        let gfb = make_test_genome(50, 1);
        let go_m = make_test_genome(100, 3);
        let go_f = make_test_genome(200, 3);
        let go_c = make_test_genome(300, 3);

        let result = crucible.forge_species(
            t1, t2, &gma, &gfa, &gmb, &gfb,
            100, 200, 300, &go_m, &go_f, &go_c,
        );
        assert!(matches!(result, CrucibleResult::DeadParent));
    }

    #[test]
    fn test_collapse_cascade() {
        let mut crucible = Crucible::new();
        forge_and_register(&mut crucible, 10, 20, 30);
        forge_and_register(&mut crucible, 10, 50, 60); // shared male vertex

        assert_eq!(crucible.alive_count(), 2);

        let events = crucible.remove_vertex(10);
        assert_eq!(events.len(), 2); // Both Trinities annihilated
        assert_eq!(crucible.alive_count(), 0);
        assert_eq!(crucible.collapse_log.len(), 2);
    }

    #[test]
    fn test_collapse_independent_survival() {
        let mut crucible = Crucible::new();
        forge_and_register(&mut crucible, 10, 20, 30);
        forge_and_register(&mut crucible, 40, 50, 60); // independent

        crucible.remove_vertex(10);
        assert_eq!(crucible.alive_count(), 1); // Trinity B survives
    }

    #[test]
    fn test_diversity_single_class() {
        let mut crucible = Crucible::new();
        // Same genomes = same torsion class
        forge_and_register(&mut crucible, 1, 1, 1);
        forge_and_register(&mut crucible, 1, 1, 1);

        let diversity = crucible.measure_diversity();
        assert_eq!(diversity.rank, 1); // monoculture
        assert_eq!(diversity.total_alive, 2);
    }

    #[test]
    fn test_diversity_multiple_classes() {
        let mut crucible = Crucible::new();
        // Very different genomes = different torsion classes
        forge_and_register(&mut crucible, 1, 2, 3);
        forge_and_register(&mut crucible, 100, 200, 300);

        let diversity = crucible.measure_diversity();
        // These should be in different torsion classes due to different Deltas
        assert!(diversity.rank >= 1);
        assert_eq!(diversity.total_alive, 2);
    }

    #[test]
    fn test_diversity_after_collapse() {
        let mut crucible = Crucible::new();
        forge_and_register(&mut crucible, 1, 2, 3);
        forge_and_register(&mut crucible, 100, 200, 300);

        crucible.remove_vertex(1);

        let diversity = crucible.measure_diversity();
        assert_eq!(diversity.total_alive, 1);
        // Rank should decrease after losing a Trinity
        assert!(diversity.rank >= 1);
    }

    #[test]
    fn test_crucible_log_immutable() {
        let mut crucible = Crucible::new();
        let t1 = forge_and_register(&mut crucible, 10, 20, 30);
        let t2 = forge_and_register(&mut crucible, 40, 50, 60);

        let gma = make_test_genome(10, 1);
        let gfa = make_test_genome(20, 1);
        let gmb = make_test_genome(40, 1);
        let gfb = make_test_genome(50, 1);
        let go_m = make_test_genome(100, 3);
        let go_f = make_test_genome(200, 3);
        let go_c = make_test_genome(300, 3);

        crucible.forge_species(
            t1, t2, &gma, &gfa, &gmb, &gfb,
            100, 200, 300, &go_m, &go_f, &go_c,
        );

        // Crucible log is append-only
        assert_eq!(crucible.crucible_log.len(), 1);
        assert_eq!(crucible.crucible_log[0].offspring_species, SPECIES_HUMAN_EVOLVED);

        // Forge another
        let t3 = crucible.trinities.last().unwrap().trinity_id;
        let go_m2 = make_test_genome(400, 3);
        let go_f2 = make_test_genome(500, 3);
        let go_c2 = make_test_genome(600, 3);

        crucible.forge_species(
            t2, t3, &gmb, &gfb, &go_m, &go_f,
            400, 500, 600, &go_m2, &go_f2, &go_c2,
        );

        assert_eq!(crucible.crucible_log.len(), 2); // Both recorded
    }
}
