// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! D.AGENT.10 — External Agent Ingress Protocol.
//!
//! Any system that can produce a V.SAMN.1 credential chain can join the mesh.
//! The mesh evaluates external agents against the same algebraic invariants
//! as internal agents. No special privilege. No administrative approval.
//!
//! Ingress requirements:
//! 1. Present V.SAMN.1 credential (10+ receipts, orbit-consistent, chain-verified)
//! 2. Ed25519 signature on credential chain tip
//! 3. UAID with valid rcf_identity matching mesh orbit
//!
//! Register: D.AGENT.10, V.SAMN.1, D.AGENT.1 (UAID), D.CHAIN.KEY.1.

use crate::agent::UAID;
use crate::credential::{self, CredentialResult, CREDENTIAL_CHAIN_DEPTH};
use crate::ledger::MeshReceipt;
use crate::signing;

/// Result of an ingress attempt.
#[derive(Debug, Clone, PartialEq)]
pub enum IngressResult {
    /// Agent accepted — sovereignty starts at SHIFTING (partial weight).
    Accepted {
        uaid: UAID,
        initial_sovereignty: &'static str,
    },
    /// Credential chain invalid.
    CredentialRejected(CredentialResult),
    /// Signature verification failed.
    SignatureInvalid,
    /// UAID orbit mismatch with mesh.
    OrbitMismatch,
}

/// Evaluate an external agent's ingress request.
///
/// The agent presents:
/// - A UAID (rcf_identity + entity_id + verifying_key)
/// - A V.SAMN.1 credential chain (10+ receipts)
/// - An Ed25519 signature on the chain tip receipt hash
///
/// The mesh evaluates against the same invariants as internal agents.
pub fn evaluate_ingress(
    uaid: &UAID,
    credential_chain: &[MeshReceipt],
    tip_signature: &[u8; 64],
    mesh_rcf_majority: &[u8; 32],
) -> IngressResult {
    // 1. Verify V.SAMN.1 credential
    let cred_result = credential::verify_credential(credential_chain, mesh_rcf_majority);
    if cred_result != CredentialResult::Valid {
        return IngressResult::CredentialRejected(cred_result);
    }

    // 2. Verify Ed25519 signature on chain tip
    let tip = match credential_chain.last() {
        Some(r) => r,
        None => return IngressResult::CredentialRejected(
            CredentialResult::InsufficientDepth { got: 0, need: CREDENTIAL_CHAIN_DEPTH },
        ),
    };
    let vk = match ed25519_dalek::VerifyingKey::from_bytes(&uaid.verifying_key) {
        Ok(vk) => vk,
        Err(_) => return IngressResult::SignatureInvalid,
    };
    if !signing::verify_receipt_signature(&vk, &tip.receipt_hash, tip_signature) {
        return IngressResult::SignatureInvalid;
    }

    // 3. Verify UAID orbit matches mesh
    if uaid.rcf_identity != *mesh_rcf_majority {
        return IngressResult::OrbitMismatch;
    }

    // All checks pass — agent accepted at SHIFTING sovereignty
    IngressResult::Accepted {
        uaid: uaid.clone(),
        initial_sovereignty: "SHIFTING",
    }
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ledger::ReceiptChain;
    use crate::constants::DISC_NORMAL;
    use num_bigint::BigInt;
    use num_rational::BigRational;
    type Q = BigRational;
    fn qr(n: i64, d: i64) -> Q { Q::new(BigInt::from(n), BigInt::from(d)) }

    fn build_credential(rcf: &[u8; 32], depth: usize) -> Vec<MeshReceipt> {
        let mut chain = ReceiptChain::new();
        (1..=depth as u64).map(|k| {
            chain.append(rcf, &qr(k as i64, 1), 1, k, DISC_NORMAL, 0, 0x01, None).unwrap()
        }).collect()
    }

    #[test]
    fn test_valid_ingress() {
        let rcf = [0x42; 32];
        let chain = build_credential(&rcf, 12);
        let sk = signing::derive_signing_key(&rcf);
        let vk = signing::public_key(&sk);
        let sig = signing::sign_receipt(&sk, &chain.last().unwrap().receipt_hash);

        let uaid = UAID {
            rcf_identity: rcf,
            entity_id: 99,
            verifying_key: vk.to_bytes(),
        };

        let result = evaluate_ingress(&uaid, &chain, &sig, &rcf);
        assert!(matches!(result, IngressResult::Accepted { .. }),
            "Valid ingress must be accepted: {:?}", result);
    }

    #[test]
    fn test_ingress_wrong_signature() {
        let rcf = [0x42; 32];
        let chain = build_credential(&rcf, 12);
        let wrong_sk = signing::derive_signing_key(&[0xFF; 32]);
        let sig = signing::sign_receipt(&wrong_sk, &chain.last().unwrap().receipt_hash);

        let sk = signing::derive_signing_key(&rcf);
        let vk = signing::public_key(&sk);
        let uaid = UAID { rcf_identity: rcf, entity_id: 99, verifying_key: vk.to_bytes() };

        assert_eq!(evaluate_ingress(&uaid, &chain, &sig, &rcf), IngressResult::SignatureInvalid);
    }

    #[test]
    fn test_ingress_orbit_mismatch() {
        // Agent's credential chain was built for orbit 0x42, but mesh is at 0xFF.
        // Credential verification catches this as OrbitMismatch before UAID check.
        let rcf = [0x42; 32];
        let chain = build_credential(&rcf, 12);
        let sk = signing::derive_signing_key(&rcf);
        let vk = signing::public_key(&sk);
        let sig = signing::sign_receipt(&sk, &chain.last().unwrap().receipt_hash);

        let uaid = UAID { rcf_identity: rcf, entity_id: 99, verifying_key: vk.to_bytes() };
        let different_mesh_rcf = [0xFF; 32];

        // Should be rejected — either credential orbit mismatch or UAID orbit mismatch
        let result = evaluate_ingress(&uaid, &chain, &sig, &different_mesh_rcf);
        assert!(matches!(result,
            IngressResult::CredentialRejected(_) | IngressResult::OrbitMismatch),
            "Must reject orbit mismatch: {:?}", result);
    }

    #[test]
    fn test_ingress_short_credential() {
        let rcf = [0x42; 32];
        let chain = build_credential(&rcf, 5); // too short
        let sk = signing::derive_signing_key(&rcf);
        let vk = signing::public_key(&sk);
        let sig = signing::sign_receipt(&sk, &chain.last().unwrap().receipt_hash);

        let uaid = UAID { rcf_identity: rcf, entity_id: 99, verifying_key: vk.to_bytes() };

        match evaluate_ingress(&uaid, &chain, &sig, &rcf) {
            IngressResult::CredentialRejected(CredentialResult::InsufficientDepth { .. }) => {}
            other => panic!("Expected InsufficientDepth, got {:?}", other),
        }
    }
}
