// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
// LEDGER INVARIANT (D.MODAL.1 at the persistence layer):
// Before ANY receipt is written to the ledger, ALL of the following must hold:
//
//   (1) t_k.is_positive()                  — CC.CON.4: only valid transitions
//   (2) delta_k.verify_conservation()      — conservation invariant preserved
//   (3) blake3_hash == blake3::hash(&canonical_preimage(...))  — encoding determinism
//   (4) parent_hash == last_hash[0..16]    — chain continuity (D.CHAIN.5)
//   (5) k_index > last_k_index             — monotonicity (D.EXEC.1)
//
// Violation of any condition: the receipt is NOT written. The K-step is NOT recorded.
// The node transitions to GATED sluice state and emits no receipt.
// This is not an error in the fault sense — it is the system working correctly.

//! Phase 2 Ledger — Append-only receipt chain with BLAKE3 hashing.
//!
//! Implements D.CHAIN.1-ENC-v3: 64-byte canonical preimage hashed with
//! unkeyed BLAKE3-256, plus unhashed metadata in the MeshReceipt struct.
//!
//! Register: D.CHAIN.1-ENC-v3, D.CHAIN.5, D.CHAIN.HASH.1, F.SAMN.3-CONT,
//!           F.SAMN.3-GAP, D.EXEC.COH.1.

use num_bigint::BigInt;
use num_rational::BigRational;
use num_traits::{Signed, ToPrimitive};

use crate::constants::{DISC_NORMAL, DISC_RESTART, DISC_ISOLATED, DISC_CORRUPTED};

type Q = BigRational;

/// Domain separation constant for Phase 2 receipts.
/// DOMAIN_RECEIPT_V3 = BLAKE3("SAIOS_RECEIPT_v3")
fn domain_receipt_v3() -> [u8; 32] {
    *blake3::hash(b"SAIOS_RECEIPT_v3").as_bytes()
}

/// Schema version byte for D.CHAIN.1-ENC-v3.
const SCHEMA_V3: u8 = 0x03;

// ─── Canonical Preimage (64 bytes) ─────────────────────────────────────

/// Build the 64-byte canonical preimage for BLAKE3 hashing.
///
/// This is the ONLY function that produces hashable content.
/// Every field is big-endian. No alternatives.
///
/// Register: D.CHAIN.1-ENC-v3, D.ENCODE.CANONICAL.1.
pub fn canonical_preimage(
    rcf_identity:  &[u8; 32],
    t_k_q1616:     u32,
    entity_id:       u32,        // uint24 — max 16,777,215
    k_index:       u64,
    parent_hash:   &[u8; 16],  // first 16 bytes of parent receipt hash
    disc_flag:     u8,
) -> [u8; 64] {
    let mut buf = [0u8; 64];
    buf[0..32].copy_from_slice(rcf_identity);
    buf[32..36].copy_from_slice(&t_k_q1616.to_be_bytes());
    buf[36..39].copy_from_slice(&entity_id.to_be_bytes()[1..4]); // uint24
    buf[39..47].copy_from_slice(&k_index.to_be_bytes());
    buf[47..63].copy_from_slice(parent_hash);
    buf[63] = disc_flag;
    buf
}

/// Compute the BLAKE3-256 receipt hash from a canonical preimage.
///
/// hash = BLAKE3(DOMAIN_RECEIPT_V3 || SCHEMA_V3 || preimage[64])
///
/// Register: D.CHAIN.HASH.1, D.CHAIN.1-ENC-v3.
pub fn receipt_hash(preimage: &[u8; 64]) -> [u8; 32] {
    let domain = domain_receipt_v3();
    let mut input = Vec::with_capacity(32 + 1 + 64);
    input.extend_from_slice(&domain);
    input.push(SCHEMA_V3);
    input.extend_from_slice(preimage);
    *blake3::hash(&input).as_bytes()
}

// ─── T_k encoding ──────────────────────────────────────────────────────

/// T_k → Q16.16 fixed-point u32. Half-even rounding. Saturates at u32::MAX.
/// Register: U.CHAIN.1.
pub fn t_k_to_q1616(t_k: &Q) -> u32 {
    let scale = Q::from_integer(BigInt::from(1u64 << 16));
    let scaled = t_k * &scale;
    let floor_v = scaled.floor();
    let frac = &scaled - &floor_v;
    let half = Q::new(BigInt::from(1), BigInt::from(2));
    let rounded = if frac == half {
        let f = floor_v.to_integer();
        let is_odd = &f % BigInt::from(2) != BigInt::from(0);
        if is_odd { f + BigInt::from(1) } else { f }
    } else if frac > half {
        floor_v.to_integer() + BigInt::from(1)
    } else {
        floor_v.to_integer()
    };
    rounded.to_u32().unwrap_or(u32::MAX)
}

// ─── MeshReceipt ───────────────────────────────────────────────────────

/// A Phase 2 mesh receipt: 64-byte hashed preimage + unhashed metadata.
///
/// The receipt_hash is computed from the canonical_preimage only.
/// Metadata fields are carried for peer verification but not hashed.
///
/// Register: D.CHAIN.1-ENC-v3.
#[derive(Debug, Clone, PartialEq)]
pub struct MeshReceipt {
    // ── Hashed fields (in canonical preimage) ──
    pub rcf_identity:   [u8; 32],
    pub t_k_q1616:      u32,
    pub entity_id:        u32,
    pub k_index:        u64,
    pub parent_hash:    [u8; 16],   // truncated parent receipt hash
    pub disc_flag:      u8,

    // ── Computed ──
    pub receipt_hash:   [u8; 32],   // BLAKE3 of canonical preimage

    // ── Unhashed metadata ──
    pub sigma_enc:      u32,
    pub sluice_state:   u8,
    pub gap_t_k_numer:  i64,
    pub gap_t_k_denom:  u64,
    pub t_k_numer:      i64,        // full-precision rational T_k
    pub t_k_denom:      u64,
    pub timestamp_ns:   u64,

    // ── D.CHRONO.1 — Chronometric telemetry (exact rational) ──
    // These form the 5D measurement vector for external validation.
    // Attached AFTER receipt construction via attach_telemetry().
    // Default: zeros (unattached). Callers that construct MeshReceipt
    // directly (wire parsers, tests) get default telemetry = unattached.
    pub telemetry: ChronoTelemetry,

    // ── D.THINK.RECEIPT.1 — Thought telemetry ──
    // Attached when a THINK command achieves understanding (jr=0).
    // Default: unattached (pair_count=0). Unhashed. Not in wire format.
    // Additive: existing receipts carry ThoughtTelemetry::unattached().
    pub thought: ThoughtTelemetry,

    // ── T.TRANSMUTE — Dimensional telemetry ──
    // Records the dimensional state at each K-step.
    // When a transmutation occurs, records old/new dimensions.
    // Default: unattached (n_dim=0). Unhashed. Not in wire format.
    pub dimensional: DimensionalTelemetry,
}

/// D.THINK.RECEIPT.1 — Thought telemetry attached when a THINK command
/// achieves understanding (joint_residual = 0).
///
/// Unhashed metadata — does not affect canonical preimage or receipt hash.
/// Default: unattached (pair_count = 0). Existing receipts carry this default.
/// This is additive: no wire format change, no chain break, no schema migration.
#[derive(Debug, Clone, PartialEq)]
pub struct ThoughtTelemetry {
    /// Joint residual before thought acceptance (raw observation distance).
    pub jr_before_numer: i64,
    pub jr_before_denom: u64,
    /// Joint residual after thought acceptance (= 0/1 when understood).
    pub jr_after_numer: i64,
    pub jr_after_denom: u64,
    /// α_genesis: coherence reduction ratio (understood = 1/1).
    pub alpha_genesis_numer: i64,
    pub alpha_genesis_denom: u64,
    /// Number of training pairs the rule generalizes across.
    pub pair_count: u32,
    /// Depth of the compound operator (number of composed thoughts).
    pub compound_depth: u32,
    /// BLAKE3 hash of the compound operator / discovered rule.
    pub compound_hash: [u8; 32],
}

impl ThoughtTelemetry {
    pub fn unattached() -> Self {
        Self {
            jr_before_numer: 0, jr_before_denom: 1,
            jr_after_numer: 0, jr_after_denom: 1,
            alpha_genesis_numer: 0, alpha_genesis_denom: 1,
            pair_count: 0,
            compound_depth: 0,
            compound_hash: [0u8; 32],
        }
    }
}

/// T.TRANSMUTE — Dimensional telemetry for transmutation events.
///
/// Records the dimensional state (n, m) at each K-step.
/// When a transmutation occurs: is_transmutation = true,
/// old_n/old_m record prior state, n_dim/m_dim record new state.
/// Unhashed metadata. Default: unattached (n_dim = 0).
#[derive(Debug, Clone, PartialEq)]
pub struct DimensionalTelemetry {
    /// State-space dimension n (number of nodes in relational field).
    pub n_dim: u32,
    /// Coordinate dimension m (depth of each relational entry Δ_ij ∈ Q^m).
    pub m_dim: u32,
    /// Whether this K-step was a transmutation (dimensional change).
    pub is_transmutation: bool,
    /// Previous n before transmutation (0 if not a transmutation).
    pub old_n: u32,
    /// Previous m before transmutation (0 if not a transmutation).
    pub old_m: u32,
    /// D.COHOMOLOGY.1: dimension of H^1 at this K-step.
    /// d - rank(AᵀA) where d = independent operator directions.
    /// 0 = all obstructions resolvable. >0 = independent obstructions
    /// requiring dimensional expansion. The receipt chain records
    /// the cohomology resolution sequence.
    pub cohomology_dim: u32,
}

impl DimensionalTelemetry {
    pub fn unattached() -> Self {
        Self { n_dim: 0, m_dim: 0, is_transmutation: false, old_n: 0, old_m: 0, cohomology_dim: 0 }
    }

    pub fn at_dimensions(n: u32, m: u32) -> Self {
        Self { n_dim: n, m_dim: m, is_transmutation: false, old_n: 0, old_m: 0, cohomology_dim: 0 }
    }

    pub fn transmutation(old_n: u32, old_m: u32, new_n: u32, new_m: u32) -> Self {
        Self { n_dim: new_n, m_dim: new_m, is_transmutation: true, old_n, old_m, cohomology_dim: 0 }
    }

    pub fn with_cohomology(mut self, dim: u32) -> Self {
        self.cohomology_dim = dim;
        self
    }
}

/// D.CHRONO.1 — The 5D chronometric measurement vector.
/// Attached to every receipt. Exact rational. Externally verifiable.
#[derive(Debug, Clone, PartialEq)]
pub struct ChronoTelemetry {
    pub coherence_numer: i64,
    pub coherence_denom: u64,
    pub alignment_numer: i64,
    pub alignment_denom: u64,
    pub omega_numer:     i64,
    pub omega_denom:     u64,
    pub conservation:    bool,
}

impl ChronoTelemetry {
    pub fn unattached() -> Self {
        Self {
            coherence_numer: 0, coherence_denom: 1,
            alignment_numer: 0, alignment_denom: 1,
            omega_numer: 0, omega_denom: 1,
            conservation: true,
        }
    }
}

impl MeshReceipt {
    /// Build a receipt from kernel output values.
    ///
    /// `last_receipt_hash`: the full 32-byte hash of the previous receipt.
    /// For genesis, use all zeros.
    pub fn build(
        rcf_identity:      &[u8; 32],
        t_k:               &Q,
        entity_id:           u32,
        k_index:           u64,
        last_receipt_hash: &[u8; 32],
        disc_flag:         u8,
        sigma_enc:         u32,
        sluice_state:      u8,
        gap_t_k:           Option<&Q>,
    ) -> Self {
        let t_k_q1616 = t_k_to_q1616(t_k);
        let mut parent_hash = [0u8; 16];
        parent_hash.copy_from_slice(&last_receipt_hash[0..16]);

        let preimage = canonical_preimage(
            rcf_identity, t_k_q1616, entity_id, k_index, &parent_hash, disc_flag,
        );
        let hash = receipt_hash(&preimage);

        let t_k_numer = t_k.numer().to_i64().unwrap_or(i64::MAX);
        let t_k_denom = t_k.denom().to_u64().unwrap_or(1);

        let (gap_numer, gap_denom) = match gap_t_k {
            Some(g) => (
                g.numer().to_i64().unwrap_or(0),
                g.denom().to_u64().unwrap_or(1),
            ),
            None => (0, 1),
        };

        let timestamp_ns = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0);

        Self {
            rcf_identity: *rcf_identity,
            t_k_q1616,
            entity_id,
            k_index,
            parent_hash,
            disc_flag,
            receipt_hash: hash,
            sigma_enc,
            sluice_state,
            gap_t_k_numer: gap_numer,
            gap_t_k_denom: gap_denom,
            t_k_numer,
            t_k_denom,
            timestamp_ns,
            telemetry: ChronoTelemetry::unattached(),
            thought: ThoughtTelemetry::unattached(),
            dimensional: DimensionalTelemetry::unattached(),
        }
    }

    /// D.CHRONO.1 — Attach chronometric telemetry to the receipt.
    /// Called after C7 evaluation with the full measurement coordinate.
    /// The receipt becomes a SIGNED CHRONOMETRIC FACT.
    pub fn attach_telemetry(&mut self, coherence: &Q, alignment: &Q, omega: &Q, conservation: bool) {
        use num_traits::ToPrimitive;
        self.telemetry = ChronoTelemetry {
            coherence_numer: coherence.numer().to_i64().unwrap_or(0),
            coherence_denom: coherence.denom().to_u64().unwrap_or(1),
            alignment_numer: alignment.numer().to_i64().unwrap_or(0),
            alignment_denom: alignment.denom().to_u64().unwrap_or(1),
            omega_numer: omega.numer().to_i64().unwrap_or(0),
            omega_denom: omega.denom().to_u64().unwrap_or(1),
            conservation,
        };
    }

    /// D.THINK.RECEIPT.1 — Attach thought telemetry to the receipt.
    /// Called when a THINK command achieves understanding (jr=0).
    pub fn attach_thought_telemetry(
        &mut self,
        jr_before: &Q,
        jr_after: &Q,
        alpha_genesis: &Q,
        pair_count: u32,
        compound_depth: u32,
        compound_hash: [u8; 32],
    ) {
        use num_traits::ToPrimitive;
        self.thought = ThoughtTelemetry {
            jr_before_numer: jr_before.numer().to_i64().unwrap_or(0),
            jr_before_denom: jr_before.denom().to_u64().unwrap_or(1),
            jr_after_numer: jr_after.numer().to_i64().unwrap_or(0),
            jr_after_denom: jr_after.denom().to_u64().unwrap_or(1),
            alpha_genesis_numer: alpha_genesis.numer().to_i64().unwrap_or(0),
            alpha_genesis_denom: alpha_genesis.denom().to_u64().unwrap_or(1),
            pair_count,
            compound_depth,
            compound_hash,
        };
    }

    /// Verify the receipt hash matches the canonical preimage.
    pub fn verify_hash(&self) -> bool {
        let preimage = canonical_preimage(
            &self.rcf_identity, self.t_k_q1616, self.entity_id,
            self.k_index, &self.parent_hash, self.disc_flag,
        );
        receipt_hash(&preimage) == self.receipt_hash
    }

    /// Verify chain continuity: parent_hash matches the given predecessor.
    pub fn verify_parent(&self, predecessor_hash: &[u8; 32]) -> bool {
        self.parent_hash == predecessor_hash[0..16]
    }
}

// ─── Ledger Error ──────────────────────────────────────────────────────

/// Errors that prevent a receipt from being appended to the ledger.
#[derive(Debug, Clone, PartialEq)]
pub enum LedgerError {
    /// T_k is not positive (CC.CON.4 violation).
    TkZero,
    /// Conservation (antisymmetry) invariant violated.
    ConservationViolated,
    /// K-index not monotonically increasing.
    KNotMonotonic { last: u64, attempted: u64 },
    /// Parent hash does not match chain tip.
    ChainBreak,
    /// Hash verification failed.
    HashMismatch,
    /// Invalid discontinuity flag value.
    InvalidDiscFlag(u8),
}

// ─── Receipt Chain ─────────────────────────────────────────────────────

/// An in-memory receipt chain with append-only semantics and chain verification.
///
/// For persistent storage, this pairs with SluiceLog (Phase 1) or a
/// database-backed store (Phase 2 production).
pub struct ReceiptChain {
    receipts: Vec<MeshReceipt>,
    last_hash: [u8; 32],
    last_k: Option<u64>,
}

impl ReceiptChain {
    /// Create a new empty chain. Genesis parent is all-zeros.
    pub fn new() -> Self {
        Self {
            receipts: Vec::new(),
            last_hash: [0u8; 32],
            last_k: None,
        }
    }

    /// Append a receipt to the chain.
    ///
    /// Enforces ALL ledger invariants:
    /// (1) T_k > 0 (CC.CON.4)
    /// (2) K monotonically increasing
    /// (3) Parent hash matches chain tip
    /// (4) Hash is correctly computed
    /// (5) Discontinuity flag is valid
    pub fn append(
        &mut self,
        rcf_identity:   &[u8; 32],
        t_k:            &Q,
        entity_id:        u32,
        k_index:        u64,
        disc_flag:      u8,
        sigma_enc:      u32,
        sluice_state:   u8,
        gap_t_k:        Option<&Q>,
    ) -> Result<MeshReceipt, LedgerError> {
        // Invariant (1): T_k > 0
        if !t_k.is_positive() {
            return Err(LedgerError::TkZero);
        }

        // Invariant (2): K monotonic
        if let Some(last) = self.last_k {
            if k_index <= last {
                return Err(LedgerError::KNotMonotonic { last, attempted: k_index });
            }
        }

        // Invariant (5): valid disc_flag
        if !matches!(disc_flag, DISC_NORMAL | DISC_RESTART | DISC_ISOLATED | DISC_CORRUPTED) {
            return Err(LedgerError::InvalidDiscFlag(disc_flag));
        }

        // Build receipt (invariant 3: parent_hash from chain tip)
        let receipt = MeshReceipt::build(
            rcf_identity, t_k, entity_id, k_index,
            &self.last_hash, disc_flag, sigma_enc, sluice_state, gap_t_k,
        );

        // Invariant (4): hash verification
        if !receipt.verify_hash() {
            return Err(LedgerError::HashMismatch);
        }

        // Commit
        self.last_hash = receipt.receipt_hash;
        self.last_k = Some(k_index);
        self.receipts.push(receipt.clone());
        Ok(receipt)
    }

    /// Verify the entire chain from genesis.
    pub fn verify_chain(&self) -> Result<(), (usize, LedgerError)> {
        let mut expected_parent = [0u8; 32];
        let mut last_k: Option<u64> = None;

        for (i, receipt) in self.receipts.iter().enumerate() {
            // Verify hash
            if !receipt.verify_hash() {
                return Err((i, LedgerError::HashMismatch));
            }
            // Verify parent
            if !receipt.verify_parent(&expected_parent) {
                return Err((i, LedgerError::ChainBreak));
            }
            // Verify K monotonic
            if let Some(prev_k) = last_k {
                if receipt.k_index <= prev_k {
                    return Err((i, LedgerError::KNotMonotonic {
                        last: prev_k,
                        attempted: receipt.k_index,
                    }));
                }
            }
            expected_parent = receipt.receipt_hash;
            last_k = Some(receipt.k_index);
        }
        Ok(())
    }

    /// Number of receipts in the chain.
    pub fn len(&self) -> usize {
        self.receipts.len()
    }

    /// Whether the chain is empty.
    pub fn is_empty(&self) -> bool {
        self.receipts.is_empty()
    }

    /// Get the latest receipt.
    pub fn latest(&self) -> Option<&MeshReceipt> {
        self.receipts.last()
    }

    /// Get the chain tip hash.
    pub fn tip_hash(&self) -> &[u8; 32] {
        &self.last_hash
    }
}

// ─── Discontinuity State Reset ─────────────────────────────────────────

/// Apply discontinuity reset rules to node state fields.
///
/// K continues (never resets — monotonic across all restarts).
/// Δ_k reloads from DB (unchanged here — caller handles persistence).
/// Σ (coherence history) resets on RESTART and ISOLATED.
/// Δ_bar resets to current Δ_k on RESTART/ISOLATED, full rebuild on CORRUPTED.
///
/// Register: F.SAMN.3-CONT.
pub struct DiscontinuityReset {
    pub clear_coherence_history: bool,
    pub reset_delta_bar_to_current: bool,
    pub reload_delta_from_anchor: bool,
}

impl DiscontinuityReset {
    pub fn for_flag(disc_flag: u8) -> Self {
        match disc_flag {
            DISC_RESTART | DISC_ISOLATED => Self {
                clear_coherence_history: true,
                reset_delta_bar_to_current: true,
                reload_delta_from_anchor: false,
            },
            DISC_CORRUPTED => Self {
                clear_coherence_history: true,
                reset_delta_bar_to_current: false,
                reload_delta_from_anchor: true,
            },
            _ => Self {
                clear_coherence_history: false,
                reset_delta_bar_to_current: false,
                reload_delta_from_anchor: false,
            },
        }
    }
}

// ─── T.2: Upgrade Receipt (D.IRS.UPGRADE.1) ──────────────────────────

/// T.2 — UpgradeReceipt: a receipted record of a system upgrade.
/// Interleaved with K-step receipts in the chain. Contains:
/// what changed, what the coherence impact was, who authorized it.
///
/// The ledger records not just what the system DID (K-steps)
/// but what the system IS (kernel version, module set, test count).
#[derive(Debug, Clone)]
pub struct UpgradeReceipt {
    /// BLAKE3 hash of upgrade content (modules_changed + version).
    pub receipt_id: [u8; 32],
    /// Last K-step receipt hash before this upgrade.
    pub parent_receipt: [u8; 32],
    /// Kernel version identifier (git hash or semver).
    pub kernel_version: String,
    /// Which source files changed.
    pub modules_changed: Vec<String>,
    /// Test count before the upgrade.
    pub test_count_before: u32,
    /// Test count after the upgrade.
    pub test_count_after: u32,
    /// Measured coherence impact after deployment (filled post-deploy).
    pub coherence_delta: Option<Q>,
    /// K-index when the upgrade was applied.
    pub k_at_upgrade: u64,
    /// MDC entropy at evaluation time (exact rational). None if not MDC-evaluated.
    pub mdc_entropy: Option<Q>,
    /// Authorization tier: 1 = auto, 2 = Principal review, 3 = Principal required.
    pub authorization_tier: u8,
}

impl UpgradeReceipt {
    /// Create a new UpgradeReceipt. The receipt_id is computed from content.
    pub fn new(
        parent_receipt: &[u8; 32],
        kernel_version: &str,
        modules_changed: Vec<String>,
        test_count_before: u32,
        test_count_after: u32,
        k_at_upgrade: u64,
    ) -> Self {
        // Compute receipt_id from upgrade content
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"SAIOS-UPGRADE-v1");
        hasher.update(kernel_version.as_bytes());
        for m in &modules_changed {
            hasher.update(m.as_bytes());
        }
        hasher.update(&test_count_before.to_be_bytes());
        hasher.update(&test_count_after.to_be_bytes());
        hasher.update(&k_at_upgrade.to_be_bytes());
        hasher.update(parent_receipt);
        let hash = hasher.finalize();

        Self {
            receipt_id: *hash.as_bytes(),
            parent_receipt: *parent_receipt,
            kernel_version: kernel_version.to_string(),
            modules_changed,
            test_count_before,
            test_count_after,
            coherence_delta: None,
            k_at_upgrade,
            mdc_entropy: None,
            authorization_tier: 0, // Set by MDC evaluation
        }
    }

    /// Set the authorization tier from MDC evaluation.
    pub fn set_authorization(&mut self, tier: u8, entropy: Option<Q>) {
        self.authorization_tier = tier;
        self.mdc_entropy = entropy;
    }

    /// Set the measured coherence delta after deployment.
    pub fn set_coherence_impact(&mut self, delta: Q) {
        self.coherence_delta = Some(delta);
    }
}

// ─── T.3: Register Receipt (D.REGISTER.1) ───────────────────────────

/// T.3 — RegisterReceipt: a receipted record of a register item being locked.
/// Interleaved with K-step and upgrade receipts in the chain.
///
/// The register receipt proves: at K=N, register item D.X.Y was locked
/// with content hash H. The chain contains the complete history of
/// what the system IS (upgrades), what the system DID (K-steps),
/// what the system UNDERSTOOD (thought receipts), and what the system
/// DEFINES (register receipts).
#[derive(Debug, Clone)]
pub struct RegisterReceipt {
    /// BLAKE3 hash of register content (matches RegisterItem::receipt_hash).
    pub receipt_id: [u8; 32],
    /// Last K-step receipt hash before this lock.
    pub parent_receipt: [u8; 32],
    /// Register item ID (e.g., "D.BUILD.COHERENCY.1").
    pub register_id: String,
    /// K-index when the item was locked.
    pub k_at_lock: u64,
    /// Which prior register item this supersedes (if any).
    pub supersedes: Option<String>,
    /// Size of the content in bytes.
    pub content_size: u32,
}

impl RegisterReceipt {
    /// Create a new RegisterReceipt from a locked RegisterItem.
    pub fn new(
        parent_receipt: &[u8; 32],
        register_id: &str,
        register_hash: &[u8; 32],
        k_at_lock: u64,
        supersedes: Option<&str>,
        content_size: u32,
    ) -> Self {
        Self {
            receipt_id: *register_hash,
            parent_receipt: *parent_receipt,
            register_id: register_id.to_string(),
            k_at_lock,
            supersedes: supersedes.map(|s| s.to_string()),
            content_size,
        }
    }
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn q(n: i64, d: i64) -> Q {
        Q::new(BigInt::from(n), BigInt::from(d))
    }

    #[test]
    fn test_canonical_preimage_deterministic() {
        let rcf = [0xAA; 32];
        let p1 = canonical_preimage(&rcf, 12345, 7, 42, &[0xBB; 16], DISC_NORMAL);
        let p2 = canonical_preimage(&rcf, 12345, 7, 42, &[0xBB; 16], DISC_NORMAL);
        assert_eq!(p1, p2, "Canonical preimage must be deterministic");
    }

    #[test]
    fn test_canonical_preimage_is_64_bytes() {
        let p = canonical_preimage(&[0; 32], 0, 0, 0, &[0; 16], 0);
        assert_eq!(p.len(), 64);
    }

    #[test]
    fn test_receipt_hash_deterministic() {
        let p = canonical_preimage(&[0x11; 32], 999, 1, 100, &[0x22; 16], DISC_RESTART);
        let h1 = receipt_hash(&p);
        let h2 = receipt_hash(&p);
        assert_eq!(h1, h2);
        assert!(h1.iter().any(|&b| b != 0), "Hash must not be all zeros");
    }

    #[test]
    fn test_receipt_hash_domain_separated() {
        let p = canonical_preimage(&[0; 32], 0, 0, 0, &[0; 16], 0);
        let with_domain = receipt_hash(&p);
        let without_domain = *blake3::hash(&p).as_bytes();
        assert_ne!(with_domain, without_domain, "Domain separation must change hash");
    }

    #[test]
    fn test_mesh_receipt_build_and_verify() {
        let rcf = [0x42; 32];
        let t_k = q(3, 7);
        let receipt = MeshReceipt::build(
            &rcf, &t_k, 1, 1, &[0u8; 32], DISC_NORMAL, 100, 0x01, None,
        );
        assert!(receipt.verify_hash());
        assert_eq!(receipt.k_index, 1);
        assert_eq!(receipt.disc_flag, DISC_NORMAL);
    }

    #[test]
    fn test_chain_append_enforces_tk_positive() {
        let mut chain = ReceiptChain::new();
        let result = chain.append(&[0; 32], &q(0, 1), 1, 1, DISC_NORMAL, 0, 0x01, None);
        assert_eq!(result, Err(LedgerError::TkZero));
    }

    #[test]
    fn test_chain_append_enforces_k_monotonic() {
        let mut chain = ReceiptChain::new();
        chain.append(&[0; 32], &q(1, 1), 1, 5, DISC_NORMAL, 0, 0x01, None).unwrap();
        let result = chain.append(&[0; 32], &q(1, 1), 1, 3, DISC_NORMAL, 0, 0x01, None);
        assert_eq!(result, Err(LedgerError::KNotMonotonic { last: 5, attempted: 3 }));
    }

    #[test]
    fn test_chain_append_enforces_k_strictly_increasing() {
        let mut chain = ReceiptChain::new();
        chain.append(&[0; 32], &q(1, 1), 1, 5, DISC_NORMAL, 0, 0x01, None).unwrap();
        let result = chain.append(&[0; 32], &q(1, 1), 1, 5, DISC_NORMAL, 0, 0x01, None);
        assert_eq!(result, Err(LedgerError::KNotMonotonic { last: 5, attempted: 5 }));
    }

    #[test]
    fn test_chain_parent_hash_links() {
        let mut chain = ReceiptChain::new();
        let r1 = chain.append(&[0x11; 32], &q(1, 1), 1, 1, DISC_NORMAL, 0, 0x01, None).unwrap();
        let r2 = chain.append(&[0x22; 32], &q(2, 1), 1, 2, DISC_NORMAL, 0, 0x01, None).unwrap();
        // r2's parent_hash should be first 16 bytes of r1's receipt_hash
        assert_eq!(&r2.parent_hash[..], &r1.receipt_hash[0..16]);
    }

    #[test]
    fn test_chain_verify_intact() {
        let mut chain = ReceiptChain::new();
        for k in 1..=10u64 {
            chain.append(&[k as u8; 32], &q(k as i64, 1), 1, k, DISC_NORMAL, 0, 0x01, None).unwrap();
        }
        assert!(chain.verify_chain().is_ok());
    }

    #[test]
    fn test_chain_verify_detects_mutation() {
        let mut chain = ReceiptChain::new();
        for k in 1..=5u64 {
            chain.append(&[k as u8; 32], &q(k as i64, 1), 1, k, DISC_NORMAL, 0, 0x01, None).unwrap();
        }
        // Mutate a middle receipt's hash
        chain.receipts[2].receipt_hash[0] ^= 0xFF;
        let result = chain.verify_chain();
        assert!(result.is_err(), "Chain verification must detect mutation");
    }

    #[test]
    fn test_discontinuity_receipt_has_gap() {
        let mut chain = ReceiptChain::new();
        let gap = q(47, 3);
        let r = chain.append(
            &[0; 32], &q(1, 1), 1, 1, DISC_RESTART, 0, 0x01, Some(&gap),
        ).unwrap();
        assert_eq!(r.disc_flag, DISC_RESTART);
        assert_eq!(r.gap_t_k_numer, 47);
        assert_eq!(r.gap_t_k_denom, 3);
    }

    #[test]
    fn test_discontinuity_reset_restart() {
        let reset = DiscontinuityReset::for_flag(DISC_RESTART);
        assert!(reset.clear_coherence_history);
        assert!(reset.reset_delta_bar_to_current);
        assert!(!reset.reload_delta_from_anchor);
    }

    #[test]
    fn test_discontinuity_reset_corrupted() {
        let reset = DiscontinuityReset::for_flag(DISC_CORRUPTED);
        assert!(reset.clear_coherence_history);
        assert!(!reset.reset_delta_bar_to_current);
        assert!(reset.reload_delta_from_anchor);
    }

    #[test]
    fn test_upgrade_receipt_roundtrip() {
        let ur = super::UpgradeReceipt::new(
            &[0xAA; 32], // parent receipt
            "v1.9.8-irs",
            vec!["irs.rs".to_string(), "mdc.rs".to_string()],
            226, 233,
            42,
        );
        assert_eq!(ur.test_count_before, 226);
        assert_eq!(ur.test_count_after, 233);
        assert_eq!(ur.modules_changed.len(), 2);
        assert!(!ur.receipt_id.iter().all(|&b| b == 0), "Receipt hash must be non-zero");
    }

    #[test]
    fn test_discontinuity_reset_normal_is_noop() {
        let reset = DiscontinuityReset::for_flag(DISC_NORMAL);
        assert!(!reset.clear_coherence_history);
        assert!(!reset.reset_delta_bar_to_current);
        assert!(!reset.reload_delta_from_anchor);
    }

    #[test]
    fn test_thought_telemetry_default_unattached() {
        let r = MeshReceipt::build(&[0; 32], &q(1, 1), 1, 1, &[0; 32], DISC_NORMAL, 0, 0x01, None);
        assert_eq!(r.thought, ThoughtTelemetry::unattached());
        assert_eq!(r.thought.pair_count, 0);
        assert_eq!(r.thought.compound_depth, 0);
        assert!(r.thought.compound_hash.iter().all(|&b| b == 0));
    }

    #[test]
    fn test_thought_telemetry_attach() {
        let mut r = MeshReceipt::build(&[0; 32], &q(1, 1), 1, 1, &[0; 32], DISC_NORMAL, 0, 0x01, None);
        let hash_before = r.receipt_hash;
        r.attach_thought_telemetry(
            &q(42, 1), &q(0, 1), &q(1, 1), 3, 2, [0xAA; 32],
        );
        // Thought telemetry is unhashed — receipt hash must not change
        assert_eq!(r.receipt_hash, hash_before);
        assert_eq!(r.thought.jr_before_numer, 42);
        assert_eq!(r.thought.jr_after_numer, 0);
        assert_eq!(r.thought.alpha_genesis_numer, 1);
        assert_eq!(r.thought.alpha_genesis_denom, 1);
        assert_eq!(r.thought.pair_count, 3);
        assert_eq!(r.thought.compound_depth, 2);
        assert_eq!(r.thought.compound_hash, [0xAA; 32]);
    }

    #[test]
    fn test_invalid_disc_flag_rejected() {
        let mut chain = ReceiptChain::new();
        let result = chain.append(&[0; 32], &q(1, 1), 1, 1, 0xFF, 0, 0x01, None);
        assert_eq!(result, Err(LedgerError::InvalidDiscFlag(0xFF)));
    }
}
