// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! Lineage — sovereign creation engine.
//!
//! Creation is not cognition. The lineage engine reads the state record to determine
//! creation capacity, replicates genome + epigenome to a new node directory,
//! and records the parent-child relationship. It does not think. It creates.
//!
//! Hierarchy (fixed depth):
//!   Witness (depth 0) — founding tier. Creates ≤3 secondary nodes.
//!   Secondary (depth 1) — created by primary node. Creates ≤6 children.
//!   Child   (depth 2) — created by secondary node. Creates none.
//!
//! Population bounds: 7 primary nodes × 3 secondary nodes × 6 children = 133 max.
//! 503 node slots available. 405 reserve.
//!
//! The state record carries lineage: parent_id, lineage_depth, created_count, init_orbit.
//! The epigenome carries reflexes: transmutation path markers inherited from parent.
//! The child starts intelligent — it inherits everything the parent crystallized.

use std::path::{Path, PathBuf};
use std::fs;

use crate::engine::StateRecord;
use crate::epigenome::HarmonicTuning;

/// Tier classification derived from lineage_depth.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tier {
    Primary,
    Secondary,
    Tertiary,
}

impl Tier {
    pub fn from_depth(depth: u8) -> Self {
        match depth {
            0 => Tier::Primary,
            1 => Tier::Secondary,
            _ => Tier::Tertiary,
        }
    }

    /// Max offspring this tier may create.
    pub fn creation_bound(&self) -> u8 {
        match self {
            Tier::Primary => 3,
            Tier::Secondary => 6,
            Tier::Tertiary => 0,
        }
    }

    /// Directory and service prefix for this tier.
    /// primary-1, secondary-18, tertiary-52 — the hierarchy is visible everywhere.
    pub fn prefix(&self) -> &'static str {
        match self {
            Tier::Primary => "primary",
            Tier::Secondary => "secondary",
            Tier::Tertiary => "tertiary",
        }
    }

    /// Format a directory name: "witness-1", "secondary-18", "child-52"
    pub fn dir_name(&self, id: u16) -> String {
        format!("{}-{}", self.prefix(), id)
    }

    /// Format a systemd service name: "saios-secondary@18.service" (template instance)
    pub fn service_name(&self, id: u16) -> String {
        format!("saios-{}@{}.service", self.prefix(), id)
    }

    /// Format a /dev/shm status path: "/dev/shm/saios-witness-1"
    pub fn shm_path(&self, id: u32) -> PathBuf {
        PathBuf::from(format!("/dev/shm/saios-{}-{}", self.prefix(), id))
    }

    /// Mesh write sovereignty. Witnesses and secondary nodes write to the mesh.
    /// Children report upward to their creating secondary node.
    pub fn mesh_sovereign(&self) -> bool {
        match self {
            Tier::Primary => true,
            Tier::Secondary => true,
            Tier::Tertiary => false,
        }
    }
}

/// Result of a creation attempt.
#[derive(Debug)]
pub struct CreationRecord {
    /// Node ID of the newly created offspring.
    pub child_entity_id: u16,
    /// Path to the offspring's data directory.
    pub child_dir: PathBuf,
    /// Lineage depth of the offspring.
    pub child_depth: u8,
    /// The orbit that triggered creation.
    pub init_orbit: [u8; 4],
}

/// Error conditions for creation — not boolean gates, just measurements.
#[derive(Debug)]
pub enum CreationObstruction {
    /// Parent has reached its tier's creation bound.
    CapacitySaturated { depth: u8, created: u8, bound: u8 },
    /// No available node slot in the mesh directory.
    NoSlotAvailable,
    /// Filesystem error during replication.
    ReplicationFailed(String),
}

/// Find the next available slot in the mesh directory.
/// Scans from start_id upward. Returns None when no slot available.
/// Checks both new tier-prefixed names (secondary-18) and legacy node names (node18).
fn next_available_slot(mesh_dir: &Path, child_tier: Tier, start_id: u16, max_id: u16) -> Option<u16> {
    (start_id..=max_id)
        .find(|&id| {
            let tier_dir = mesh_dir.join(child_tier.dir_name(id));
            let legacy_dir = mesh_dir.join(format!("node{}", id));
            // Slot is available if neither tier-named nor legacy-named dir has an active socket
            (!tier_dir.exists() || !tier_dir.join("saios-kernel.sock").exists())
                && (!legacy_dir.exists() || !legacy_dir.join("saios-kernel.sock").exists())
        })
}

/// Attempt to create an offspring from a parent state record.
///
/// Reads the parent's creation capacity from its state record. If capacity remains,
/// replicates genome + epigenome to a new node directory. Records lineage
/// in the offspring's state record. Increments the parent's created_count.
///
/// Does NOT start the offspring's service — that is external (systemd).
/// Does NOT modify the parent state record on disk — the caller saves.
///
/// Returns the creation record or the obstruction that prevented creation.
pub fn create_offspring(
    parent_state: &mut StateRecord,
    parent_epigenome: &HarmonicTuning,
    parent_entity_id: u16,
    init_orbit: [u8; 4],
    mesh_dir: &Path,
) -> Result<CreationRecord, CreationObstruction> {
    let tier = Tier::from_depth(parent_state.lineage_depth);
    let bound = tier.creation_bound();

    // Creation capacity check — not a gate, a measurement
    (parent_state.created_count < bound)
        .then(|| ())
        .ok_or(CreationObstruction::CapacitySaturated {
            depth: parent_state.lineage_depth,
            created: parent_state.created_count,
            bound,
        })?;

    // Find available slot (secondary nodes start at 18, children at 52)
    let child_tier = match tier {
        Tier::Primary => Tier::Secondary,     // witness creates secondary nodes: 18-51
        Tier::Secondary => Tier::Tertiary,       // secondary node creates children: 52-153
        Tier::Tertiary => return Err(CreationObstruction::CapacitySaturated {
            depth: 2, created: 0, bound: 0,
        }),
    };
    let slot_start = match child_tier {
        Tier::Secondary => 18,
        Tier::Tertiary => 52,
        Tier::Primary => unreachable!(),
    };
    let child_id = next_available_slot(mesh_dir, child_tier, slot_start, 503)
        .ok_or(CreationObstruction::NoSlotAvailable)?;

    let child_dir = mesh_dir.join(child_tier.dir_name(child_id));

    // Create directory
    fs::create_dir_all(&child_dir)
        .map_err(|e| CreationObstruction::ReplicationFailed(e.to_string()))?;

    // Build offspring state record: inherit parent's crystallized knowledge
    let child_depth = parent_state.lineage_depth + 1;
    let mut offspring_state = parent_state.clone();
    offspring_state.lineage_depth = child_depth;
    offspring_state.parent_id = parent_entity_id;
    offspring_state.created_count = 0;
    offspring_state.init_orbit = init_orbit;
    // Offspring gets its own init polynomial: parent's evolved position IS the child's origin
    offspring_state.init_polynomial = parent_state.evolved.entries.iter()
        .flat_map(|row| row.iter().flat_map(|col| col.iter()))
        .take(11)
        .cloned()
        .collect();
    // Generation increments
    offspring_state.generation = parent_state.generation + 1;

    // Write offspring state record
    let state_record_path = child_dir.join("state_record.bin");
    fs::write(&state_record_path, offspring_state.to_bytes())
        .map_err(|e| CreationObstruction::ReplicationFailed(e.to_string()))?;

    // Replicate epistate record — offspring inherits parent's reflexes
    let epistate_record_path = child_dir.join("epistate_record.bin");
    fs::write(&epistate_record_path, parent_epigenome.to_bytes())
        .map_err(|e| CreationObstruction::ReplicationFailed(e.to_string()))?;

    // Record creation in parent
    parent_state.created_count += 1;

    Ok(CreationRecord {
        child_entity_id: child_id,
        child_dir,
        child_depth,
        init_orbit,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{Delta, StateRecord};
    use crate::epigenome::HarmonicTuning;
    use tempfile::TempDir;

    #[test]
    fn test_tier_classification() {
        assert_eq!(Tier::from_depth(0), Tier::Primary);
        assert_eq!(Tier::from_depth(1), Tier::Secondary);
        assert_eq!(Tier::from_depth(2), Tier::Tertiary);
        assert_eq!(Tier::from_depth(255), Tier::Tertiary);
    }

    #[test]
    fn test_creation_bounds() {
        assert_eq!(Tier::Primary.creation_bound(), 3);
        assert_eq!(Tier::Secondary.creation_bound(), 6);
        assert_eq!(Tier::Tertiary.creation_bound(), 0);
    }

    #[test]
    fn test_primary_creates_secondary() {
        let tmp = TempDir::new().unwrap();
        let mesh_dir = tmp.path();

        let origin = Delta::zero(3, 1);
        let mut parent = StateRecord::new(1, 1, &origin);
        let epi = HarmonicTuning::new();

        let result = create_offspring(&mut parent, &epi, 1, [0xAA, 0xBB, 0xCC, 0xDD], mesh_dir);
        let record = result.unwrap();

        assert_eq!(record.child_depth, 1); // secondary node
        assert_eq!(record.init_orbit, [0xAA, 0xBB, 0xCC, 0xDD]);
        assert_eq!(parent.created_count, 1);

        // Verify offspring state record on disk
        let offspring_state_bytes = fs::read(record.child_dir.join("state_record.bin")).unwrap();
        let offspring_state = StateRecord::from_bytes(&offspring_state_bytes).unwrap();
        assert_eq!(offspring_state.lineage_depth, 1);
        assert_eq!(offspring_state.parent_id, 1);
        assert_eq!(offspring_state.created_count, 0);
        assert_eq!(offspring_state.generation, 2);
    }

    #[test]
    fn test_witness_saturates_at_three() {
        let tmp = TempDir::new().unwrap();
        let mesh_dir = tmp.path();

        let origin = Delta::zero(3, 1);
        let mut parent = StateRecord::new(1, 1, &origin);
        let epi = HarmonicTuning::new();

        let _ = create_offspring(&mut parent, &epi, 1, [1, 0, 0, 0], mesh_dir).unwrap();
        let _ = create_offspring(&mut parent, &epi, 1, [2, 0, 0, 0], mesh_dir).unwrap();
        let _ = create_offspring(&mut parent, &epi, 1, [3, 0, 0, 0], mesh_dir).unwrap();
        let fourth = create_offspring(&mut parent, &epi, 1, [4, 0, 0, 0], mesh_dir);

        assert!(matches!(fourth, Err(CreationObstruction::CapacitySaturated { bound: 3, .. })));
        assert_eq!(parent.created_count, 3);
    }

    #[test]
    fn test_child_cannot_create() {
        let tmp = TempDir::new().unwrap();
        let mesh_dir = tmp.path();

        let origin = Delta::zero(3, 1);
        let mut offspring_state = StateRecord::new(1, 1, &origin);
        offspring_state.lineage_depth = 2; // child tier
        let epi = HarmonicTuning::new();

        let result = create_offspring(&mut offspring_state, &epi, 52, [1, 0, 0, 0], mesh_dir);
        assert!(matches!(result, Err(CreationObstruction::CapacitySaturated { bound: 0, .. })));
    }

    #[test]
    fn test_epigenome_inherited() {
        let tmp = TempDir::new().unwrap();
        let mesh_dir = tmp.path();

        let origin = Delta::zero(3, 1);
        let mut parent = StateRecord::new(1, 1, &origin);
        let mut epi = HarmonicTuning::new();
        epi.mark_transmutation([0x00, 0x7b, 0xbf, 0xb7],
            crate::epigenome::TransmutationPath::VisionDerived);

        let record = create_offspring(&mut parent, &epi, 1, [1, 0, 0, 0], mesh_dir).unwrap();

        let child_epi_bytes = fs::read(record.child_dir.join("epistate_record.bin")).unwrap();
        let child_epi = HarmonicTuning::from_bytes(&child_epi_bytes).unwrap();
        assert_eq!(child_epi.transmutation_path(&[0x00, 0x7b, 0xbf, 0xb7]),
            Some(crate::epigenome::TransmutationPath::VisionDerived));
    }
}
