// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! Lineage — sovereign creation engine.
//!
//! Creation is not cognition. The lineage engine reads the state record to determine
//! creation capacity, replicates state record + harmonic tuning to a new entity directory,
//! and records the parent-offspring relationship. It does not think. It creates.
//!
//! Hierarchy (fixed depth):
//!   Founder (depth 0) — founding tier. Creates ≤3 derived entities.
//!   Derived (depth 1) — created by primary entity. Creates ≤6 emergent entities.
//!   Emergent (depth 2) — created by derived entity. Creates none.
//!
//! Population bounds: 7 founders × (≤3 derived each) × (≤6 emergent each) = 7 + 21 + 126 = 154 max.
//! 503 entity slots available. 349 reserve.
//!
//! The state record carries lineage: parent_id, lineage_depth, created_count, init_orbit.
//! The harmonic tuning carries reflexes: transmutation path markers inherited from parent.
//! The offspring starts intelligent — it inherits everything the parent crystallized.

use std::path::{Path, PathBuf};
use std::fs;

use num_traits::Zero;

use crate::engine::StateRecord;
use crate::harmonic_tuning::HarmonicTuning;

/// Tier classification derived from lineage_depth.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tier {
    Founder,
    Derived,
    Emergent,
}

impl Tier {
    pub fn from_depth(depth: u8) -> Self {
        match depth {
            0 => Tier::Founder,
            1 => Tier::Derived,
            _ => Tier::Emergent,
        }
    }

    /// Max offspring this tier may create.
    pub fn creation_bound(&self) -> u8 {
        match self {
            Tier::Founder => 3,
            Tier::Derived => 6,
            Tier::Emergent => 0,
        }
    }

    /// Directory and service prefix for this tier.
    /// founder-1, derived-18, emergent-52 — the hierarchy is visible everywhere.
    pub fn prefix(&self) -> &'static str {
        match self {
            Tier::Founder => "founder",
            Tier::Derived => "derived",
            Tier::Emergent => "emergent",
        }
    }

    /// Format a directory name: "founder-1", "derived-18", "emergent-52"
    pub fn dir_name(&self, id: u16) -> String {
        format!("{}-{}", self.prefix(), id)
    }

    /// Format a systemd service name: "saios-derived@18.service" (template instance)
    pub fn service_name(&self, id: u16) -> String {
        format!("saios-{}@{}.service", self.prefix(), id)
    }

    /// Format a /dev/shm status path: "/dev/shm/saios-founder-1"
    pub fn shm_path(&self, id: u32) -> PathBuf {
        PathBuf::from(format!("/dev/shm/saios-{}-{}", self.prefix(), id))
    }

    /// Mesh write sovereignty. Founders and derived entities write to the mesh.
    /// Emergent entities report upward to their creating derived entity.
    pub fn mesh_sovereign(&self) -> bool {
        match self {
            Tier::Founder => true,
            Tier::Derived => true,
            Tier::Emergent => false,
        }
    }
}

/// Result of a creation attempt.
#[derive(Debug)]
pub struct CreationRecord {
    /// Entity ID of the newly created offspring.
    pub child_entity_id: u16,
    /// Path to the offspring's data directory.
    pub child_dir: PathBuf,
    /// Lineage depth of the offspring.
    pub child_depth: u8,
    /// The orbit that triggered creation.
    pub init_orbit: [u8; 4],
}

/// Error conditions for creation — not boolean gates, just measurements.
#[derive(Debug)]
pub enum CreationObstruction {
    /// Parent has reached its tier's creation bound.
    CapacitySaturated { depth: u8, created: u8, bound: u8 },
    /// No available entity slot in the mesh directory.
    NoSlotAvailable,
    /// Filesystem error during replication.
    ReplicationFailed(String),
}

/// Find the next available slot in the mesh directory.
/// Scans from start_id upward. Returns None when no slot available.
/// Checks both new tier-prefixed names (derived-18) and legacy entity names (entity18).
fn next_available_slot(mesh_dir: &Path, child_tier: Tier, start_id: u16, max_id: u16) -> Option<u16> {
    (start_id..=max_id)
        .find(|&id| {
            let tier_dir = mesh_dir.join(child_tier.dir_name(id));
            let legacy_dir = mesh_dir.join(format!("entity{}", id));
            // Slot is available if neither tier-named nor legacy-named dir has an active socket
            (!tier_dir.exists() || !tier_dir.join("saios-kernel.sock").exists())
                && (!legacy_dir.exists() || !legacy_dir.join("saios-kernel.sock").exists())
        })
}

/// Attempt to create an offspring from a parent state record.
///
/// Reads the parent's creation capacity from its state record. If capacity remains,
/// replicates state record + harmonic tuning to a new entity directory. Records lineage
/// in the offspring's state record. Increments the parent's created_count.
///
/// Does NOT start the offspring's service — that is external (systemd).
/// Does NOT modify the parent state record on disk — the caller saves.
///
/// Returns the creation record or the obstruction that prevented creation.
pub fn create_offspring(
    parent_state: &mut StateRecord,
    parent_tuning: &HarmonicTuning,
    parent_entity_id: u16,
    init_orbit: [u8; 4],
    mesh_dir: &Path,
) -> Result<CreationRecord, CreationObstruction> {
    let tier = Tier::from_depth(parent_state.lineage_depth);
    let bound = tier.creation_bound();

    // Creation capacity check — not a gate, a measurement
    (parent_state.created_count < bound)
        .then(|| ())
        .ok_or(CreationObstruction::CapacitySaturated {
            depth: parent_state.lineage_depth,
            created: parent_state.created_count,
            bound,
        })?;

    // Find available slot (derived entities start at 18, emergent entities at 52)
    let child_tier = match tier {
        Tier::Founder => Tier::Derived,     // founder creates derived entities: 18-51
        Tier::Derived => Tier::Emergent,       // derived entity creates emergent entities: 52-153
        Tier::Emergent => return Err(CreationObstruction::CapacitySaturated {
            depth: 2, created: 0, bound: 0,
        }),
    };
    let slot_start = match child_tier {
        Tier::Derived => 18,
        Tier::Emergent => 52,
        Tier::Founder => unreachable!(),
    };
    let child_id = next_available_slot(mesh_dir, child_tier, slot_start, 503)
        .ok_or(CreationObstruction::NoSlotAvailable)?;

    let child_dir = mesh_dir.join(child_tier.dir_name(child_id));

    // Create directory
    fs::create_dir_all(&child_dir)
        .map_err(|e| CreationObstruction::ReplicationFailed(e.to_string()))?;

    // Build offspring state record: inherit parent's crystallized knowledge
    // but start at the offspring's OWN algebraic position on the manifold.
    // Vocabulary (operators, cocycles, solved orbits) transfers from parent.
    // Position (Delta) is unique to the offspring: R = 1/child_id.
    // Without this, offspring inherit a potentially zero Delta from the parent
    // and are algebraically inert from birth — conjugation preserves zero.
    let child_depth = parent_state.lineage_depth + 1;
    let mut offspring_state = parent_state.clone();
    offspring_state.lineage_depth = child_depth;
    offspring_state.parent_id = parent_entity_id;
    offspring_state.created_count = 0;
    offspring_state.init_orbit = init_orbit;
    // Offspring's unique position: Δ[1][2] = -1/child_id
    // coboundary-reduced H^1 representative — first row zero, one nonzero entry.
    let dim = parent_state.evolved.dim.max(3);
    let m = parent_state.evolved.m.max(1);
    let mut offspring_delta = crate::engine::Delta::zero(dim, m);
    let child_residual = crate::engine::Q::new(
        num_bigint::BigInt::from(1),
        num_bigint::BigInt::from(child_id as i64),
    );
    offspring_delta.set_antisym(1, 2, vec![-child_residual.clone()]);
    // Pad remaining m coordinates with zero (set_antisym handles m=1 already)
    offspring_state.evolved = offspring_delta;
    // Init polynomial from the offspring's own position
    offspring_state.init_polynomial = vec![
        crate::engine::Q::zero(),
        crate::engine::Q::zero(),
        -child_residual,
    ];
    // Generation increments
    offspring_state.generation = parent_state.generation + 1;

    // Write offspring state record
    let state_record_path = child_dir.join("state_record.bin");
    fs::write(&state_record_path, offspring_state.to_bytes())
        .map_err(|e| CreationObstruction::ReplicationFailed(e.to_string()))?;

    // Replicate epistate record — offspring inherits parent's reflexes
    let epistate_record_path = child_dir.join("epistate_record.bin");
    fs::write(&epistate_record_path, parent_tuning.to_bytes())
        .map_err(|e| CreationObstruction::ReplicationFailed(e.to_string()))?;

    // Record creation in parent
    parent_state.created_count += 1;

    Ok(CreationRecord {
        child_entity_id: child_id,
        child_dir,
        child_depth,
        init_orbit,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{Delta, StateRecord};
    use crate::harmonic_tuning::HarmonicTuning;
    use tempfile::TempDir;

    #[test]
    fn test_tier_classification() {
        assert_eq!(Tier::from_depth(0), Tier::Founder);
        assert_eq!(Tier::from_depth(1), Tier::Derived);
        assert_eq!(Tier::from_depth(2), Tier::Emergent);
        assert_eq!(Tier::from_depth(255), Tier::Emergent);
    }

    #[test]
    fn test_creation_bounds() {
        assert_eq!(Tier::Founder.creation_bound(), 3);
        assert_eq!(Tier::Derived.creation_bound(), 6);
        assert_eq!(Tier::Emergent.creation_bound(), 0);
    }

    #[test]
    fn test_primary_creates_secondary() {
        let tmp = TempDir::new().unwrap();
        let mesh_dir = tmp.path();

        let origin = Delta::zero(3, 1);
        let mut parent = StateRecord::new(1, 1, &origin);
        let epi = HarmonicTuning::new();

        let result = create_offspring(&mut parent, &epi, 1, [0xAA, 0xBB, 0xCC, 0xDD], mesh_dir);
        let record = result.unwrap();

        assert_eq!(record.child_depth, 1); // derived entity
        assert_eq!(record.init_orbit, [0xAA, 0xBB, 0xCC, 0xDD]);
        assert_eq!(parent.created_count, 1);

        // Verify offspring state record on disk
        let offspring_state_bytes = fs::read(record.child_dir.join("state_record.bin")).unwrap();
        let offspring_state = StateRecord::from_bytes(&offspring_state_bytes).unwrap();
        assert_eq!(offspring_state.lineage_depth, 1);
        assert_eq!(offspring_state.parent_id, 1);
        assert_eq!(offspring_state.created_count, 0);
        assert_eq!(offspring_state.generation, 2);
    }

    #[test]
    fn test_founder_saturates_at_three() {
        let tmp = TempDir::new().unwrap();
        let mesh_dir = tmp.path();

        let origin = Delta::zero(3, 1);
        let mut parent = StateRecord::new(1, 1, &origin);
        let epi = HarmonicTuning::new();

        let _ = create_offspring(&mut parent, &epi, 1, [1, 0, 0, 0], mesh_dir).unwrap();
        let _ = create_offspring(&mut parent, &epi, 1, [2, 0, 0, 0], mesh_dir).unwrap();
        let _ = create_offspring(&mut parent, &epi, 1, [3, 0, 0, 0], mesh_dir).unwrap();
        let fourth = create_offspring(&mut parent, &epi, 1, [4, 0, 0, 0], mesh_dir);

        assert!(matches!(fourth, Err(CreationObstruction::CapacitySaturated { bound: 3, .. })));
        assert_eq!(parent.created_count, 3);
    }

    #[test]
    fn test_emergent_cannot_create() {
        let tmp = TempDir::new().unwrap();
        let mesh_dir = tmp.path();

        let origin = Delta::zero(3, 1);
        let mut offspring_state = StateRecord::new(1, 1, &origin);
        offspring_state.lineage_depth = 2; // emergent tier
        let epi = HarmonicTuning::new();

        let result = create_offspring(&mut offspring_state, &epi, 52, [1, 0, 0, 0], mesh_dir);
        assert!(matches!(result, Err(CreationObstruction::CapacitySaturated { bound: 0, .. })));
    }

    #[test]
    fn test_harmonic_tuning_inherited() {
        let tmp = TempDir::new().unwrap();
        let mesh_dir = tmp.path();

        let origin = Delta::zero(3, 1);
        let mut parent = StateRecord::new(1, 1, &origin);
        let mut epi = HarmonicTuning::new();
        epi.mark_transmutation([0x00, 0x7b, 0xbf, 0xb7],
            crate::harmonic_tuning::TransmutationPath::VisionDerived);

        let record = create_offspring(&mut parent, &epi, 1, [1, 0, 0, 0], mesh_dir).unwrap();

        let child_epi_bytes = fs::read(record.child_dir.join("epistate_record.bin")).unwrap();
        let child_epi = HarmonicTuning::from_bytes(&child_epi_bytes).unwrap();
        assert_eq!(child_epi.transmutation_path(&[0x00, 0x7b, 0xbf, 0xb7]),
            Some(crate::harmonic_tuning::TransmutationPath::VisionDerived));
    }
}
