// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! D.MDC.1 — Multi-Dimensional Cameral Logic.
//!
//! Four-echelon governance over operator proposals. All echelons produce
//! exact [u8;32] orbit class identifiers from algebraic computation.
//! No echelon contains or calls a neural network.
//!
//! Echelons:
//!   Physics   — argmin_O C(Π_G(Δ_k + ε·e_O)). Gradient descent. (sampler.rs)
//!   Legal     — vetted parameter envelope from governance constants.
//!   Strategic — modal rcf_identity prefix from recent receipt chain.
//!   Security  — negative gradient of failure patterns from training records.
//!
//! Resolution: vector summation with exact rational weights summing to 1.
//! Entropy: H = 1 - (w_winner / w_total) — exact rational.
//! Stasis: when H ≥ threshold, sampler proposes identity, T_k=0, K holds.
//!
//! The LLM sits ABOVE this — reads results via Orbital Semantic Projection (OSP).
//! SAIOS computes. LLM reads. C2R bridges. They do not swap roles.
//!
//! Register: D.MDC.1, D.MDC.SEMANTIC.1, T.FOUND.4 (substrate independence).

use std::collections::HashMap;

use num_bigint::BigInt;
use num_traits::{One, Zero};

use crate::engine::{Delta, Q, coherence_functional, compute_rcf_hash};
use crate::gradient::compute_coherence_gradient;
use crate::training::TrainingRecord;

// ─── Echelon Weights ──────────────────────────────────────────────────

/// Exact rational echelon weights. Must sum to exactly 1.
/// No float enters the MDC computation at any point (T.FOUND.4).
#[derive(Debug, Clone)]
pub struct EchelonWeights {
    pub physics: Q,
    pub legal: Q,
    pub strategic: Q,
    pub security: Q,
}

#[derive(Debug, Clone, PartialEq)]
pub enum WeightError {
    DoesNotSumToOne(Q),
    ZeroDenominator,
}

impl EchelonWeights {
    /// Construct weights from rational pairs. Fails if sum != 1 exactly.
    pub fn new(p: (i64, u64), l: (i64, u64), s: (i64, u64), r: (i64, u64)) -> Result<Self, WeightError> {
        if p.1 == 0 || l.1 == 0 || s.1 == 0 || r.1 == 0 {
            return Err(WeightError::ZeroDenominator);
        }
        let w = Self {
            physics: Q::new(BigInt::from(p.0), BigInt::from(p.1)),
            legal: Q::new(BigInt::from(l.0), BigInt::from(l.1)),
            strategic: Q::new(BigInt::from(s.0), BigInt::from(s.1)),
            security: Q::new(BigInt::from(r.0), BigInt::from(r.1)),
        };
        let sum = &w.physics + &w.legal + &w.strategic + &w.security;
        if sum != Q::one() {
            return Err(WeightError::DoesNotSumToOne(sum));
        }
        Ok(w)
    }

    /// Default balanced weights — provably sum to 1: q(1,4)*4 = 1 exactly.
    pub fn balanced() -> Self {
        Self::new((1, 4), (1, 4), (1, 4), (1, 4)).unwrap()
    }

    /// Physics-heavy: 1/2 physics, 1/6 each for others. Sum = 1/2+1/6+1/6+1/6 = 1.
    pub fn physics_heavy() -> Self {
        Self::new((1, 2), (1, 6), (1, 6), (1, 6)).unwrap()
    }
}

// ─── Echelon Outputs ──────────────────────────────────────────────────

/// Output of a single echelon: a [u8;32] orbit class target + confidence.
#[derive(Debug, Clone)]
pub struct EchelonHint {
    /// Target orbit class (RCF hash prefix or full hash).
    pub orbit_target: [u8; 32],
    /// Confidence — exact rational in [0,1]. Higher = more certain.
    pub confidence: Q,
}

/// Combined output of all four echelons.
#[derive(Debug, Clone)]
pub struct MdcResult {
    pub physics_hint: EchelonHint,
    pub legal_hint: EchelonHint,
    pub strategic_hint: EchelonHint,
    pub security_hint: EchelonHint,
    /// Combined orbit target — weighted vote.
    pub combined_target: [u8; 32],
    /// Entropy: H = 1 - (w_winner / w_total). How much echelons agree.
    pub entropy: Q,
    /// Stasis triggered? If true, sampler proposes identity, T_k=0, K holds.
    pub stasis: bool,
    /// Which echelon won (highest weighted confidence toward combined target).
    pub winner: Echelon,
    /// Transmutation needed? Stasis = hold (temporary). Transmutation = expand
    /// (the current dimensional structure is exhausted, not just temporarily stuck).
    /// True when stasis AND coherence has been near-zero improvement for sustained period.
    pub transmutation_needed: bool,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Echelon {
    Physics,
    Legal,
    Strategic,
    Security,
}

// ─── Echelon Computations ─────────────────────────────────────────────

/// Physics echelon: argmin_O C(Π_G(Δ_k + ε·e_O)).
/// Uses the coherence gradient to find the orbit class with lowest C.
/// This IS the sampler's gradient hint — repackaged as an orbit target.
pub fn physics_echelon(delta: &Delta) -> EchelonHint {
    let grad = compute_coherence_gradient(delta);
    let orbit = compute_rcf_hash(delta);

    // Confidence measures gradient signal strength — how clearly the algebra
    // knows which direction to go. |best_gradient| / (1 + |best_gradient|).
    // Strong gradient (far from coherence) = high confidence = physics dominates.
    // Zero gradient (at coherence or flat) = zero confidence = physics yields.
    let abs_grad = if grad.best_gradient < Q::zero() {
        -grad.best_gradient.clone()
    } else {
        grad.best_gradient.clone()
    };
    let confidence = &abs_grad / &(&Q::one() + &abs_grad);

    EchelonHint { orbit_target: orbit, confidence }
}

/// Legal echelon: checks if current state is within the vetted parameter envelope.
/// The "envelope" is defined by governance constants — max coherence, min T_k, etc.
/// Returns the current orbit as target (legal says "stay in bounds") with confidence
/// based on how far inside the envelope the state is.
pub fn legal_echelon(delta: &Delta, max_coherence: &Q) -> EchelonHint {
    let c = coherence_functional(delta);
    let orbit = compute_rcf_hash(delta);

    // Confidence = 1 if C < max, decays as C approaches max
    let confidence = max_coherence.is_zero().then(Q::zero).unwrap_or_else(|| {
        let ratio = &c / max_coherence;
        (ratio < Q::one()).then(|| max_coherence - &c).unwrap_or(Q::zero()) / max_coherence
    });

    EchelonHint { orbit_target: orbit, confidence }
}

/// Legal echelon with Option — absence means no constraint.
/// None = genesis state, no measurement taken. The echelon abstains (zero confidence).
/// Some(max) = measured coherence envelope.
pub fn legal_echelon_opt(delta: &Delta, max_coherence: Option<&Q>) -> EchelonHint {
    match max_coherence {
        Some(max) => legal_echelon(delta, max),
        None => EchelonHint {
            orbit_target: compute_rcf_hash(delta),
            confidence: Q::zero(), // No measurement — echelon abstains
        },
    }
}

/// Strategic echelon: modal rcf_identity prefix from recent receipt chain.
/// Scans the last K_STRATEGIC receipts and returns the most common orbit class.
/// This anchors the system to its historical trajectory.
pub fn strategic_echelon(recent_rcf_hashes: &[[u8; 32]]) -> EchelonHint {
    if recent_rcf_hashes.is_empty() {
        return EchelonHint {
            orbit_target: [0; 32],
            confidence: Q::zero(),
        };
    }

    // Count 4-byte prefix frequencies (orbit class bucketing)
    let mut prefix_counts: HashMap<[u8; 4], (u32, [u8; 32])> = HashMap::new();
    for rcf in recent_rcf_hashes {
        let mut prefix = [0u8; 4];
        prefix.copy_from_slice(&rcf[..4]);
        let entry = prefix_counts.entry(prefix).or_insert((0, *rcf));
        entry.0 += 1;
    }

    // Modal orbit class
    let (count, (_, modal_rcf)) = prefix_counts.iter()
        .max_by_key(|(_, (c, _))| *c)
        .map(|(_, v)| (v.0, v))
        .unwrap_or((0, &(0, [0; 32])));

    // Confidence = modal_count / total
    let confidence = Q::new(
        BigInt::from(count as i64),
        BigInt::from(recent_rcf_hashes.len() as i64),
    );

    EchelonHint { orbit_target: *modal_rcf, confidence }
}

/// Security echelon: negative gradient of failure patterns.
/// Scans training records for orbit regions with high failure rates
/// and produces an orbit target that avoids those regions.
pub fn security_echelon(
    recent_records: &[TrainingRecord],
    current_rcf: &[u8; 32],
) -> EchelonHint {
    if recent_records.is_empty() {
        return EchelonHint {
            orbit_target: *current_rcf,
            confidence: Q::zero(),
        };
    }

    // Count failures by orbit prefix
    let mut prefix_failures: HashMap<[u8; 4], (u32, u32)> = HashMap::new(); // (fails, total)
    for rec in recent_records {
        let mut prefix = [0u8; 4];
        prefix.copy_from_slice(&rec.rcf_identity[..4]);
        let entry = prefix_failures.entry(prefix).or_insert((0, 0));
        entry.1 += 1;
        if !rec.c7_passed { entry.0 += 1; }
    }

    // Current orbit prefix
    let mut current_prefix = [0u8; 4];
    current_prefix.copy_from_slice(&current_rcf[..4]);

    // Confidence = 1 - (failure_rate_in_current_region)
    let (fails, total) = prefix_failures.get(&current_prefix).copied().unwrap_or((0, 1));
    let fail_rate = Q::new(BigInt::from(fails as i64), BigInt::from(total.max(1) as i64));
    let confidence = Q::one() - &fail_rate;

    EchelonHint {
        orbit_target: *current_rcf,
        confidence,
    }
}

// ─── MDC Resolution ───────────────────────────────────────────────────

/// Exact rational entropy: H = 1 - (w_winner / w_total).
/// No f64 conversion anywhere. Substrate-independent under T.FOUND.4.
pub fn mdc_entropy(winner_weight: &Q, total_weight: &Q) -> Q {
    if total_weight.is_zero() { return Q::one(); }
    Q::one() - (winner_weight / total_weight)
}

/// Stasis threshold — stored as exact rational. Default: 1/2.
pub fn stasis_triggered(entropy: &Q, threshold: &Q) -> bool {
    entropy >= threshold
}

/// MDC resolution: vector summation of four echelon hints with exact rational weights.
///
/// 1. Each echelon produces an orbit target + confidence.
/// 2. Effective weight = echelon_weight × confidence (exact rational).
/// 3. Winner = echelon with highest effective weight.
/// 4. Combined target = winner's orbit target (discrete vote, not interpolation).
/// 5. Entropy = 1 - (w_winner / w_total).
/// 6. Stasis if entropy ≥ threshold (echelons disagree too much).
pub fn mdc_resolve(
    weights: &EchelonWeights,
    physics: &EchelonHint,
    legal: &EchelonHint,
    strategic: &EchelonHint,
    security: &EchelonHint,
    stasis_threshold: &Q,
) -> MdcResult {
    // Effective weights: w_i * confidence_i
    let ew_physics = &weights.physics * &physics.confidence;
    let ew_legal = &weights.legal * &legal.confidence;
    let ew_strategic = &weights.strategic * &strategic.confidence;
    let ew_security = &weights.security * &security.confidence;

    let total = &ew_physics + &ew_legal + &ew_strategic + &ew_security;

    // Find winner
    let echelons = [
        (Echelon::Physics, &ew_physics, &physics.orbit_target),
        (Echelon::Legal, &ew_legal, &legal.orbit_target),
        (Echelon::Strategic, &ew_strategic, &strategic.orbit_target),
        (Echelon::Security, &ew_security, &security.orbit_target),
    ];

    let (winner_echelon, winner_weight, winner_target) = echelons.iter()
        .max_by(|a, b| a.1.cmp(b.1))
        .map(|(e, w, t)| (*e, (*w).clone(), **t))
        .unwrap_or((Echelon::Physics, Q::zero(), [0; 32]));

    // Entropy
    let entropy = mdc_entropy(&winner_weight, &total);

    // Stasis check
    let stasis = stasis_triggered(&entropy, stasis_threshold);

    // Transmutation detection: stasis alone means "hold temporarily."
    // Transmutation means "the current dimensional structure is exhausted."
    // Signal: stasis AND all echelons have low confidence (nothing works,
    // not just that they disagree). Low confidence across all = the algebra
    // cannot find any direction. This is the dimensional wall.
    let transmutation_needed = stasis && {
        let low_threshold = Q::new(BigInt::from(1), BigInt::from(10)); // 0.1
        physics.confidence < low_threshold
            && legal.confidence < low_threshold
            && strategic.confidence < low_threshold
            && security.confidence < low_threshold
    };

    MdcResult {
        physics_hint: physics.clone(),
        legal_hint: legal.clone(),
        strategic_hint: strategic.clone(),
        security_hint: security.clone(),
        combined_target: winner_target,
        entropy,
        stasis,
        winner: winner_echelon,
        transmutation_needed,
    }
}

// ─── T.3: ConfigSpaceOperator — Upgrades as Operators on Kernel Config ──

/// T.3.1 — An upgrade IS an operator on the kernel's configuration space.
/// Submitted to MDC echelons for evaluation BEFORE the binary is built.
#[derive(Debug, Clone)]
pub struct ConfigSpaceOperator {
    /// Files added, changed, or removed.
    pub modules_changed: Vec<String>,
    /// Test count change (positive = added tests, negative = removed).
    pub delta_tests: i32,
    /// Predicted coherence impact from pre-deploy analysis. Exact rational.
    pub predicted_coherence_impact: Q,
    /// Version tag for this upgrade.
    pub version_tag: String,
}

/// T.3.2 — Evaluate a ConfigSpaceOperator through the MDC echelons.
///
/// Physics: does test count increase? (more tests = more coherence coverage)
/// Legal: are changed modules in the register? (no unregistered changes)
/// Strategic: does version align with phase register? (trajectory coherence)
/// Security: are new modules adding attack surface? (dependency risk)
///
/// Returns MdcResult with echelon hints and entropy.
pub fn evaluate_upgrade(
    op: &ConfigSpaceOperator,
    registered_modules: &[&str],
    stasis_threshold: &Q,
) -> (MdcResult, u8) {
    // Physics echelon: confidence from test delta
    let physics_conf = if op.delta_tests > 0 {
        // More tests = higher confidence. Saturates quickly toward 1.
        // conf = 1 - 1/(1 + delta_tests) — approaches 1 as tests increase
        let dt = BigInt::from(op.delta_tests.min(1000) as i64);
        Q::one() - Q::new(BigInt::from(1), &dt + BigInt::from(1))
    } else if op.delta_tests == 0 {
        Q::new(BigInt::from(1), BigInt::from(2)) // neutral
    } else {
        Q::new(BigInt::from(1), BigInt::from(10)) // lost tests = low confidence
    };

    // Legal echelon: are all changed modules in the register?
    let unregistered: Vec<&String> = op.modules_changed.iter()
        .filter(|m| !registered_modules.iter().any(|r| m.contains(r)))
        .collect();
    let legal_conf = if unregistered.is_empty() {
        Q::new(BigInt::from(9), BigInt::from(10)) // all registered
    } else {
        Q::new(BigInt::from(1), BigInt::from(10)) // unregistered changes
    };

    // Strategic echelon: version tag alignment (simple heuristic)
    let strategic_conf = Q::new(BigInt::from(7), BigInt::from(10));

    // Security echelon: new files = potential new attack surface
    let new_modules = op.modules_changed.len();
    let security_conf = if new_modules <= 2 {
        Q::new(BigInt::from(9), BigInt::from(10))
    } else if new_modules <= 5 {
        Q::new(BigInt::from(7), BigInt::from(10))
    } else {
        Q::new(BigInt::from(5), BigInt::from(10))
    };

    let orbit = [0u8; 32]; // config space orbit — same for all echelons
    let physics = EchelonHint { orbit_target: orbit, confidence: physics_conf };
    let legal = EchelonHint { orbit_target: orbit, confidence: legal_conf };
    let strategic = EchelonHint { orbit_target: orbit, confidence: strategic_conf };
    let security = EchelonHint { orbit_target: orbit, confidence: security_conf };

    // Physics-heavy for upgrades: coherence impact is the primary signal
    let weights = EchelonWeights::physics_heavy();
    let result = mdc_resolve(&weights, &physics, &legal, &strategic, &security, stasis_threshold);

    // T.4.1 — Authorization tier from entropy
    let tier = if result.entropy <= Q::zero() {
        1 // unanimous — auto-authorize
    } else if result.entropy < Q::new(BigInt::from(1), BigInt::from(4)) {
        1 // strong agreement — auto-authorize
    } else if result.entropy < Q::new(BigInt::from(1), BigInt::from(2)) {
        2 // moderate — Principal review
    } else {
        3 // high disagreement — Principal required
    };

    (result, tier)
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::Delta;
    use crate::training::FailureCode;

    fn qr(n: i64, d: i64) -> Q { Q::new(BigInt::from(n), BigInt::from(d)) }

    fn incoherent_delta() -> Delta {
        let mut d = Delta::zero(3, 1);
        d.set_antisym(0, 1, vec![qr(2, 1)]);
        d.set_antisym(1, 2, vec![qr(3, 1)]);
        d.set_antisym(0, 2, vec![qr(7, 1)]);
        d
    }

    #[test]
    fn test_balanced_weights_sum_to_one() {
        let w = EchelonWeights::balanced();
        let sum = &w.physics + &w.legal + &w.strategic + &w.security;
        assert_eq!(sum, Q::one(), "Balanced weights must sum to exactly 1");
    }

    #[test]
    fn test_physics_heavy_weights_sum_to_one() {
        let w = EchelonWeights::physics_heavy();
        let sum = &w.physics + &w.legal + &w.strategic + &w.security;
        assert_eq!(sum, Q::one(), "Physics-heavy weights must sum to exactly 1");
    }

    #[test]
    fn test_invalid_weights_rejected() {
        let result = EchelonWeights::new((1, 3), (1, 3), (1, 3), (1, 3));
        assert!(result.is_err(), "Weights summing to 4/3 must be rejected");
    }

    #[test]
    fn test_zero_denominator_rejected() {
        let result = EchelonWeights::new((1, 0), (1, 4), (1, 4), (1, 4));
        assert!(result.is_err(), "Zero denominator must be rejected");
    }

    #[test]
    fn test_physics_echelon_produces_hint() {
        let d = incoherent_delta();
        let hint = physics_echelon(&d);
        assert!(hint.confidence > Q::zero(), "Incoherent state must have positive confidence");
        assert!(hint.confidence <= Q::one(), "Confidence must be ≤ 1");
    }

    #[test]
    fn test_legal_echelon_within_envelope() {
        let d = incoherent_delta();
        let max_c = qr(1000, 1); // Very large envelope
        let hint = legal_echelon(&d, &max_c);
        assert!(hint.confidence > Q::zero(), "Within envelope must have positive confidence");
    }

    #[test]
    fn test_legal_echelon_outside_envelope() {
        let d = incoherent_delta();
        let max_c = qr(1, 1000000); // Tiny envelope — C is way above
        let hint = legal_echelon(&d, &max_c);
        assert_eq!(hint.confidence, Q::zero(), "Outside envelope must have zero confidence");
    }

    #[test]
    fn test_strategic_echelon_modal() {
        let rcf_a = [0xAA; 32];
        let rcf_b = [0xBB; 32];
        let hashes = vec![rcf_a, rcf_a, rcf_a, rcf_b, rcf_b];
        let hint = strategic_echelon(&hashes);
        assert_eq!(&hint.orbit_target[..4], &[0xAA; 4], "Modal orbit should be 0xAA");
        assert_eq!(hint.confidence, qr(3, 5), "Confidence should be 3/5");
    }

    #[test]
    fn test_security_echelon_high_failure_region() {
        let mut records = Vec::new();
        for _ in 0..8 {
            records.push(TrainingRecord {
                k_index: 0, entity_id: 0, c7_passed: false,
                seed_class: crate::training::SeedClass::Directed,
                orbit_changed: false, sluice_state: 1,
                coherence_numer: 0, coherence_denom: 1,
                t_k_numer: 0, t_k_denom: 1,
                rcf_identity: [0xAA; 32],
                operator_entries: [(0, 1); 9],
                timestamp_ns: 0, failure_code: FailureCode::MagnitudeDrift,
            });
        }
        for _ in 0..2 {
            records.push(TrainingRecord {
                k_index: 0, entity_id: 0, c7_passed: true,
                seed_class: crate::training::SeedClass::Directed,
                orbit_changed: false, sluice_state: 1,
                coherence_numer: 0, coherence_denom: 1,
                t_k_numer: 0, t_k_denom: 1,
                rcf_identity: [0xAA; 32],
                operator_entries: [(0, 1); 9],
                timestamp_ns: 0, failure_code: FailureCode::None,
            });
        }
        let hint = security_echelon(&records, &[0xAA; 32]);
        // 8/10 failures → confidence = 1 - 8/10 = 2/10 = 1/5
        assert_eq!(hint.confidence, qr(1, 5));
    }

    #[test]
    fn test_mdc_entropy_exact() {
        // Winner weight = 1/4, total = 1 → H = 1 - 1/4 = 3/4
        let h = mdc_entropy(&qr(1, 4), &qr(1, 1));
        assert_eq!(h, qr(3, 4));
    }

    #[test]
    fn test_mdc_entropy_unanimous() {
        // Winner weight = 1, total = 1 → H = 0 (unanimous)
        let h = mdc_entropy(&qr(1, 1), &qr(1, 1));
        assert_eq!(h, Q::zero());
    }

    #[test]
    fn test_stasis_triggers_on_high_entropy() {
        let threshold = qr(1, 2);
        assert!(stasis_triggered(&qr(3, 4), &threshold)); // 0.75 > 0.5
        assert!(!stasis_triggered(&qr(1, 4), &threshold)); // 0.25 < 0.5
        assert!(stasis_triggered(&qr(1, 2), &threshold));  // 0.5 == 0.5 → stasis
    }

    #[test]
    fn test_mdc_resolve_balanced() {
        let weights = EchelonWeights::balanced();
        let physics = EchelonHint { orbit_target: [0xAA; 32], confidence: qr(9, 10) };
        let legal = EchelonHint { orbit_target: [0xBB; 32], confidence: qr(8, 10) };
        let strategic = EchelonHint { orbit_target: [0xAA; 32], confidence: qr(7, 10) };
        let security = EchelonHint { orbit_target: [0xCC; 32], confidence: qr(6, 10) };

        let result = mdc_resolve(&weights, &physics, &legal, &strategic, &security, &qr(1, 2));

        // Physics has highest effective weight: 1/4 * 9/10 = 9/40
        assert_eq!(result.winner, Echelon::Physics);
        assert_eq!(result.combined_target, [0xAA; 32]);
        // Entropy = 1 - (9/40)/(30/40) = 1 - 3/10 = 7/10. Stasis triggers because
        // no single echelon dominates enough. This is correct behavior.
        assert_eq!(result.entropy, qr(7, 10));
    }

    #[test]
    fn test_mdc_resolve_dominant_physics_no_stasis() {
        // Physics-heavy weights: physics dominates → low entropy → no stasis
        let weights = EchelonWeights::physics_heavy();
        let physics = EchelonHint { orbit_target: [0xAA; 32], confidence: qr(1, 1) }; // full confidence
        let legal = EchelonHint { orbit_target: [0xBB; 32], confidence: qr(1, 10) };
        let strategic = EchelonHint { orbit_target: [0xCC; 32], confidence: qr(1, 10) };
        let security = EchelonHint { orbit_target: [0xDD; 32], confidence: qr(1, 10) };

        let result = mdc_resolve(&weights, &physics, &legal, &strategic, &security, &qr(1, 2));
        assert_eq!(result.winner, Echelon::Physics);
        // Physics ew = 1/2 * 1 = 1/2. Others = 1/6 * 1/10 = 1/60 each. Total = 1/2 + 3/60 = 33/60.
        // H = 1 - (1/2)/(33/60) = 1 - 30/33 = 3/33 = 1/11 ≈ 0.09. Well below stasis.
        assert!(!result.stasis, "Dominant physics should not trigger stasis");
    }

    #[test]
    fn test_mdc_resolve_stasis_on_deadlock() {
        let weights = EchelonWeights::balanced();
        // All echelons disagree with similar confidence → high entropy → stasis
        let physics = EchelonHint { orbit_target: [0xAA; 32], confidence: qr(1, 4) };
        let legal = EchelonHint { orbit_target: [0xBB; 32], confidence: qr(1, 4) };
        let strategic = EchelonHint { orbit_target: [0xCC; 32], confidence: qr(1, 4) };
        let security = EchelonHint { orbit_target: [0xDD; 32], confidence: qr(1, 4) };

        let result = mdc_resolve(&weights, &physics, &legal, &strategic, &security, &qr(1, 2));
        // Each effective weight = 1/4 * 1/4 = 1/16. Total = 4/16 = 1/4.
        // Winner = any (all equal). H = 1 - (1/16)/(1/4) = 1 - 1/4 = 3/4.
        assert_eq!(result.entropy, qr(3, 4));
        assert!(result.stasis, "Deadlock should trigger stasis");
    }

    #[test]
    fn test_full_mdc_pipeline_with_real_state() {
        let d = incoherent_delta();
        let weights = EchelonWeights::balanced();
        let max_c = qr(1000, 1);
        let current_rcf = compute_rcf_hash(&d);

        let p = physics_echelon(&d);
        let l = legal_echelon(&d, &max_c);
        let s = strategic_echelon(&[current_rcf, current_rcf, current_rcf]);
        let r = security_echelon(&[], &current_rcf);

        let result = mdc_resolve(&weights, &p, &l, &s, &r, &qr(1, 2));

        // Must produce a valid result
        assert!(!result.entropy.is_zero() || result.winner == Echelon::Physics,
            "Must resolve to some echelon");
    }

    // ─── ConfigSpaceOperator tests ────────────────────────────────

    #[test]
    fn test_upgrade_all_registered_tier1() {
        let op = ConfigSpaceOperator {
            modules_changed: vec!["sampler.rs".to_string(), "gradient.rs".to_string()],
            delta_tests: 10,
            predicted_coherence_impact: Q::zero(),
            version_tag: "v1.9.8".to_string(),
        };
        let registered = &["sampler", "gradient", "mdc", "irs", "agent", "ledger", "coordinator", "matrix"];
        let (result, tier) = evaluate_upgrade(&op, registered, &qr(1, 2));
        // With physics-heavy weights and all echelons agreeing, entropy ≈ 0.48
        // This is Tier 2 (moderate agreement) — correct. Tier 1 requires near-unanimity.
        assert!(tier <= 2, "Registered upgrade with +tests should be Tier 1 or 2, got {}", tier);
        assert!(!result.stasis);
    }

    #[test]
    fn test_upgrade_unregistered_module_higher_tier() {
        let op = ConfigSpaceOperator {
            modules_changed: vec!["unknown_new_module.rs".to_string()],
            delta_tests: 0,
            predicted_coherence_impact: Q::zero(),
            version_tag: "v1.9.8".to_string(),
        };
        let registered = &["sampler", "gradient"];
        let (_result, tier) = evaluate_upgrade(&op, registered, &qr(1, 2));
        assert!(tier >= 2, "Unregistered module should require review, got tier {}", tier);
    }

    #[test]
    fn test_upgrade_lost_tests_low_confidence() {
        let op = ConfigSpaceOperator {
            modules_changed: vec!["engine.rs".to_string()],
            delta_tests: -5,
            predicted_coherence_impact: Q::zero(),
            version_tag: "v1.9.8".to_string(),
        };
        let registered = &["engine"];
        let (_, tier) = evaluate_upgrade(&op, registered, &qr(1, 2));
        assert!(tier >= 2, "Losing tests should require review");
    }
}
