// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! Ed25519 Receipt Signing — Phase 2.2.
//!
//! Key derivation: seed = Keccak256("SAIOS-ED25519-SEED-v1" || rcf_identity_at_origin).
//! Deterministic: same origin RCF always produces the same keypair.
//! No external key generation ceremony. No HSM required.
//!
//! Register: D.CHAIN.KEY.1.

use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use tiny_keccak::{Hasher, Keccak};

/// Derive an Ed25519 signing key from a origin RCF identity.
///
/// seed = Keccak256("SAIOS-ED25519-SEED-v1" || rcf_identity)
///
/// Deterministic: any entity with the same origin state produces
/// the same keypair. Register: D.CHAIN.KEY.1.
pub fn derive_signing_key(origin_rcf_identity: &[u8; 32]) -> SigningKey {
    let mut keccak = Keccak::v256();
    let mut seed = [0u8; 32];
    keccak.update(b"SAIOS-ED25519-SEED-v1");
    keccak.update(origin_rcf_identity);
    keccak.finalize(&mut seed);
    SigningKey::from_bytes(&seed)
}

/// Extract the public verification key from a signing key.
pub fn public_key(signing_key: &SigningKey) -> VerifyingKey {
    signing_key.verifying_key()
}

/// Sign a receipt hash (32 bytes) with the node's Ed25519 key.
/// Returns a 64-byte signature.
pub fn sign_receipt(signing_key: &SigningKey, receipt_hash: &[u8; 32]) -> [u8; 64] {
    let sig: Signature = signing_key.sign(receipt_hash);
    sig.to_bytes()
}

/// Verify a receipt signature against the signer's public key.
pub fn verify_receipt_signature(
    public_key: &VerifyingKey,
    receipt_hash: &[u8; 32],
    signature: &[u8; 64],
) -> bool {
    let sig = match Signature::from_bytes(signature) {
        s => s,
    };
    public_key.verify(receipt_hash, &sig).is_ok()
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_key_derivation_deterministic() {
        let rcf = [0x42; 32];
        let k1 = derive_signing_key(&rcf);
        let k2 = derive_signing_key(&rcf);
        assert_eq!(k1.to_bytes(), k2.to_bytes(),
            "Same origin RCF must produce same key");
    }

    #[test]
    fn test_different_rcf_different_keys() {
        let k1 = derive_signing_key(&[0x01; 32]);
        let k2 = derive_signing_key(&[0x02; 32]);
        assert_ne!(k1.to_bytes(), k2.to_bytes(),
            "Different RCF must produce different keys");
    }

    #[test]
    fn test_sign_and_verify() {
        let rcf = [0xAA; 32];
        let sk = derive_signing_key(&rcf);
        let pk = public_key(&sk);
        let receipt_hash = [0xBB; 32];
        let sig = sign_receipt(&sk, &receipt_hash);
        assert!(verify_receipt_signature(&pk, &receipt_hash, &sig),
            "Valid signature must verify");
    }

    #[test]
    fn test_wrong_key_rejects() {
        let sk1 = derive_signing_key(&[0x01; 32]);
        let sk2 = derive_signing_key(&[0x02; 32]);
        let pk2 = public_key(&sk2);
        let receipt_hash = [0xCC; 32];
        let sig = sign_receipt(&sk1, &receipt_hash);
        assert!(!verify_receipt_signature(&pk2, &receipt_hash, &sig),
            "Wrong key must reject");
    }

    #[test]
    fn test_tampered_hash_rejects() {
        let sk = derive_signing_key(&[0x42; 32]);
        let pk = public_key(&sk);
        let receipt_hash = [0xDD; 32];
        let sig = sign_receipt(&sk, &receipt_hash);
        let mut tampered = receipt_hash;
        tampered[0] ^= 0xFF;
        assert!(!verify_receipt_signature(&pk, &tampered, &sig),
            "Tampered hash must reject");
    }

    #[test]
    fn test_signature_is_64_bytes() {
        let sk = derive_signing_key(&[0x42; 32]);
        let sig = sign_receipt(&sk, &[0; 32]);
        assert_eq!(sig.len(), 64);
    }
}
