// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! Tier 1 MeshFabric Simulator — in-process 101-node algebraic stress test.
//!
//! Tests convergence dynamics with three fault modes:
//! - Drift: Δ entries perturbed by small rational offsets each tick
//! - KLag: node stops advancing K for N ticks then resumes
//! - OrbitFork: node's state diverges into a different conjugacy class
//!
//! All nodes boot from identical Δ_Anchor (uniform genesis).
//! A cyclic permutation operator produces T_k > 0 while preserving
//! the RCF conjugacy class exactly (orthogonal → ‖PΔPᵀ‖² = ‖Δ‖²).
//!
//! Register: D.MESH.CONFIG.1, T.FOUND.14.

use num_bigint::BigInt;
use num_rational::BigRational;
use num_traits::Zero;

use crate::engine::*;
use crate::consensus;
use crate::mesh;
use crate::operators;

type QR = BigRational;

fn qi(n: i64) -> QR { QR::from_integer(BigInt::from(n)) }
fn qr(n: i64, d: i64) -> QR { QR::new(BigInt::from(n), BigInt::from(d)) }

/// Build the canonical anchor: a fixed antisymmetric cocycle state.
/// Δ_01 = 1, Δ_12 = 1/2, Δ_02 = 3/2 (cocycle: 1 + 1/2 = 3/2).
fn canonical_anchor(dim: usize, m: usize) -> Delta {
    let mut delta = Delta::zero(dim, m);
    if dim >= 3 && m >= 1 {
        delta.set_antisym(0, 1, vec![qr(1, 1); m]);
        delta.set_antisym(1, 2, vec![qr(1, 2); m]);
        delta.set_antisym(0, 2, vec![qr(3, 2); m]);
    }
    delta
}

/// Build a shear operator A = I + s*E_{row,col}. det(A) = 1, infinite order over Q.
/// A⁻¹ = I - s*E_{row,col} (nilpotent correction: (sE)² = 0).
// ─── Types ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub enum FaultMode {
    Honest,
    Drift { epsilon: QR },
    KLag { resume_at_tick: u64 },
    OrbitFork,
}

pub struct NodeSim {
    pub entity_id: u32,
    pub state: WitnessState,
    pub kernel: SaiosKernel,
    pub fault: FaultMode,
    pub rcf_hash: [u8; 32],
    pub advanced_last_tick: bool,
}

#[derive(Debug, Clone)]
pub struct TickSnapshot {
    pub tick: u64,
    pub k_per_node: Vec<u64>,
    pub fault_gamma_avg: QR,
    pub honest_gamma_max: QR,
    pub nodes_advanced: usize,
    pub sigma_mesh: QR,
    pub hard_resync_triggered: bool,
}

#[derive(Debug)]
pub struct CoherenceReport {
    pub ticks_run: u64,
    pub honest_k_spread: u64,
    pub convergence_achieved: bool,
    pub fault_entity_id: u32,
    pub fault_mode: String,
    pub ticks_until_detected: Option<u64>,
    pub gamma_trajectory: Vec<QR>,
    pub honest_gamma_trajectory: Vec<QR>,
    pub nodes_advanced_trajectory: Vec<usize>,
    pub sigma_mesh_trajectory: Vec<QR>,
}

// ─── MeshFabric ────────────────────────────────────────────────────────

pub struct MeshFabric {
    pub nodes: Vec<NodeSim>,
    pub tick: u64,
    pub history: Vec<TickSnapshot>,
    pub node_count: usize,
}

impl MeshFabric {
    pub fn new(n: usize) -> Self {
        let dim = 3;
        let m = 1;
        let anchor = canonical_anchor(dim, m);
        let ops = operators::production_operators_3x3();

        let rcf_hash = compute_rcf_hash(&anchor);
        let nodes: Vec<NodeSim> = (0..n as u32)
            .map(|id| {
                let state = WitnessState {
                    entity_id: id, k_index: 0,
                    sluice_state: SluiceState::Locked,
                    latest_sigma_enc: 0,
                    delta_k: anchor.clone(),
                    delta_bar: anchor.clone(),
                    trajectory: Trajectory::new(),
                    t_k_latest: QR::zero(),
                };
                // Production params: w_max = 1/3, ζ = 1/10
                NodeSim {
                    entity_id: id, state,
                    kernel: SaiosKernel::new_default(ops.clone()),
                    fault: FaultMode::Honest,
                    rcf_hash,
                    advanced_last_tick: false,
                }
            })
            .collect();

        MeshFabric { node_count: n, nodes, tick: 0, history: Vec::new() }
    }

    pub fn inject_fault(&mut self, entity_id: u32, fault: FaultMode) {
        self.nodes[entity_id as usize].fault = fault;
    }

    pub fn tick(&mut self) {
        // ── Step 1: Apply faults ──────────────────────────────────────
        for node in &mut self.nodes {
            match &node.fault {
                FaultMode::Drift { epsilon } => {
                    let c = node.state.delta_k.entries[0][1][0].clone();
                    node.state.delta_k.entries[0][1][0] = &c + epsilon;
                    node.state.delta_k.entries[1][0][0] = -(&c + epsilon);
                }
                FaultMode::KLag { resume_at_tick } => {
                    if self.tick < *resume_at_tick {
                        node.state.delta_bar = node.state.delta_k.clone();
                    }
                }
                FaultMode::OrbitFork => {
                    node.state.delta_k.entries[0][1][0] += &qr(1, 1_000_000);
                    node.state.delta_k.entries[1][0][0] -= &qr(1, 1_000_000);
                }
                FaultMode::Honest => {}
            }
        }

        // ── Step 2: Each node executes K-step ─────────────────────────
        for node in &mut self.nodes {
            match node.kernel.execute_k_step(&mut node.state) {
                Ok(_) => { node.advanced_last_tick = true; }
                Err(SaiosError::C4TkZero) => { node.advanced_last_tick = false; }
                Err(_) => {
                    node.advanced_last_tick = false;
                    node.state.sluice_state = SluiceState::Gated;
                }
            }
            node.rcf_hash = compute_rcf_hash(&node.state.delta_k);
        }

        // ── Step 3: Compute metrics ───────────────────────────────────
        let fault_idx = self.nodes.iter()
            .position(|n| !matches!(n.fault, FaultMode::Honest))
            .unwrap_or(0);

        let fault_rcf = self.nodes[fault_idx].rcf_hash;
        let mut fault_gamma_sum = QR::zero();
        let mut fault_count = 0u32;
        for (j, node) in self.nodes.iter().enumerate() {
            if j == fault_idx { continue; }
            if matches!(node.fault, FaultMode::Honest) {
                fault_gamma_sum = fault_gamma_sum + mesh::gamma_sq_proxy(&fault_rcf, &node.rcf_hash);
                fault_count += 1;
            }
        }
        let fault_gamma_avg = if fault_count > 0 {
            fault_gamma_sum / qi(fault_count as i64)
        } else { QR::zero() };

        // Max Γ² among honest pairs
        let honest_idxs: Vec<usize> = self.nodes.iter().enumerate()
            .filter(|(_, n)| matches!(n.fault, FaultMode::Honest))
            .map(|(i, _)| i).collect();
        let mut honest_gamma_max = QR::zero();
        for i in 0..honest_idxs.len() {
            for j in (i + 1)..honest_idxs.len() {
                let g = mesh::gamma_sq_proxy(
                    &self.nodes[honest_idxs[i]].rcf_hash,
                    &self.nodes[honest_idxs[j]].rcf_hash,
                );
                if g > honest_gamma_max { honest_gamma_max = g; }
            }
        }

        let nodes_advanced = self.nodes.iter().filter(|n| n.advanced_last_tick).count();
        let k_per_node: Vec<u64> = self.nodes.iter().map(|n| n.state.k_index as u64).collect();

        // ── Σ_mesh via consensus::sigma_mesh (CC.SAMN.3) ──────────────
        let params = SaiosParams::default_register();
        let peer_states_for_0: Vec<mesh::PeerState> = self.nodes.iter()
            .filter(|n| n.entity_id != 0)
            .map(|n| mesh::PeerState {
                entity_id: n.entity_id,
                k_latest: n.state.k_index as u64,
                rcf_identity: n.rcf_hash,
                t_k_q1616: 0,
                sigma_enc: n.state.latest_sigma_enc,
                last_seen_k: self.tick,
                disc_status: 0,
            })
            .collect();
        let sigma_mesh_val = consensus::sigma_mesh(
            self.nodes[0].state.latest_sigma_enc,
            &peer_states_for_0,
            self.nodes[0].state.k_index as u64,
            &self.nodes[0].rcf_hash,
            &params.alpha_p, &params.alpha_gamma, &params.alpha_k,
            &params.tau_lag, &params.epsilon_sluice,
        );

        let hard_resync_triggered = if let Some(prev) = self.history.last() {
            consensus::sigma_drift_triggers_resync(
                &sigma_mesh_val, &prev.sigma_mesh, &params.tau_sigma,
            )
        } else {
            false
        };

        self.history.push(TickSnapshot {
            tick: self.tick, k_per_node, fault_gamma_avg, honest_gamma_max,
            nodes_advanced, sigma_mesh: sigma_mesh_val, hard_resync_triggered,
        });
        self.tick += 1;
    }

    pub fn report(&self) -> CoherenceReport {
        let fault_idx = self.nodes.iter()
            .position(|n| !matches!(n.fault, FaultMode::Honest))
            .unwrap_or(0);
        let fault_node = &self.nodes[fault_idx];
        let fault_mode = match &fault_node.fault {
            FaultMode::Honest => "honest".into(),
            FaultMode::Drift { epsilon } => format!("drift(ε={})", epsilon),
            FaultMode::KLag { resume_at_tick } => format!("klag(resume={})", resume_at_tick),
            FaultMode::OrbitFork => "orbit_fork".into(),
        };

        let honest_ks: Vec<u64> = self.nodes.iter()
            .filter(|n| matches!(n.fault, FaultMode::Honest))
            .map(|n| n.state.k_index as u64).collect();
        let honest_k_spread = if honest_ks.is_empty() { 0 } else {
            honest_ks.iter().max().unwrap() - honest_ks.iter().min().unwrap()
        };

        let gamma_trajectory: Vec<QR> = self.history.iter()
            .map(|s| s.fault_gamma_avg.clone()).collect();
        let honest_gamma_trajectory: Vec<QR> = self.history.iter()
            .map(|s| s.honest_gamma_max.clone()).collect();
        let nodes_advanced_trajectory: Vec<usize> = self.history.iter()
            .map(|s| s.nodes_advanced).collect();
        let sigma_mesh_trajectory: Vec<QR> = self.history.iter()
            .map(|s| s.sigma_mesh.clone()).collect();

        let ticks_until_detected = gamma_trajectory.iter().enumerate()
            .position(|(_, g)| g > &qr(1, 100))
            .map(|p| p as u64);

        CoherenceReport {
            ticks_run: self.tick, honest_k_spread,
            convergence_achieved: honest_k_spread <= 1,
            fault_entity_id: fault_node.entity_id, fault_mode,
            ticks_until_detected, gamma_trajectory, honest_gamma_trajectory,
            nodes_advanced_trajectory, sigma_mesh_trajectory,
        }
    }

    pub fn print_report(&self) {
        let r = self.report();
        eprintln!("=== MESH COHERENCE REPORT ===");
        eprintln!("Ticks:              {}", r.ticks_run);
        eprintln!("Honest K spread:    {}", r.honest_k_spread);
        eprintln!("Convergence:        {}", r.convergence_achieved);
        eprintln!("Fault node:         {} ({})", r.fault_entity_id, r.fault_mode);
        eprintln!("Detected at tick:   {:?}", r.ticks_until_detected);
        eprintln!("\n--- Nodes advancing per tick ---");
        for (i, n) in r.nodes_advanced_trajectory.iter().enumerate().take(30) {
            eprintln!("  tick {:3}: {} nodes advanced K", i, n);
        }
        eprintln!("\n--- Γ_fault² ---");
        for (i, g) in r.gamma_trajectory.iter().enumerate().take(30) {
            let v = g.numer().to_string().parse::<f64>().unwrap_or(0.0)
                / g.denom().to_string().parse::<f64>().unwrap_or(1.0);
            eprintln!("  tick {:3}: {:.8}", i, v);
        }
        eprintln!("\n--- Γ_honest_max² ---");
        for (i, g) in r.honest_gamma_trajectory.iter().enumerate().take(30) {
            let v = g.numer().to_string().parse::<f64>().unwrap_or(0.0)
                / g.denom().to_string().parse::<f64>().unwrap_or(1.0);
            eprintln!("  tick {:3}: {:.8}", i, v);
        }
    }
}

// ─── Solo Drift Boundary Map ───────────────────────────────────────────

/// Map RCF boundaries for a drifting node. Returns the tick numbers where
/// the RCF hash changes (invariant factor boundary crossings).
pub fn solo_drift_boundary_map(epsilon: &QR, max_ticks: u64) -> Vec<u64> {
    let mut delta = canonical_anchor(3, 1);
    let mut rcf_prev = compute_rcf_hash(&delta);
    let mut boundaries = Vec::new();

    for tick in 0..max_ticks {
        let c = delta.entries[0][1][0].clone();
        delta.entries[0][1][0] = &c + epsilon;
        delta.entries[1][0][0] = -(&c + epsilon);
        let rcf_now = compute_rcf_hash(&delta);
        if rcf_now != rcf_prev {
            boundaries.push(tick);
            rcf_prev = rcf_now;
        }
    }
    boundaries
}

// ─── Reentry Support ───────────────────────────────────────────────────

/// K-cool: minimum ticks after sluicing before reentry attempt.
pub const K_COOL: u64 = 10;

impl MeshFabric {
    /// Check if a previously-sluiced node can reenter.
    pub fn attempt_reentry(&mut self, entity_id: u32, sluiced_at_tick: u64) -> bool {
        if self.tick < sluiced_at_tick + K_COOL {
            return false;
        }
        let anchor_rcf = compute_rcf_hash(&canonical_anchor(3, 1));
        let node = &mut self.nodes[entity_id as usize];
        if node.rcf_hash == anchor_rcf {
            node.state.sluice_state = SluiceState::Shifting;
            node.fault = FaultMode::Honest;
            true
        } else {
            false
        }
    }
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_solo_magnitude_ratio_calibration() {
        // Measure per-step magnitude ratio from the master equation directly.
        // Uses a kernel with epsilon_mag_relative = 1000 (effectively disabled)
        // to let K advance, then measures the actual ratios.
        let dim = 3; let m = 1;
        let anchor = canonical_anchor(dim, m);
        let ops = operators::production_operators_3x3();
        let mut params = SaiosParams::default_register();
        params.epsilon_mag_relative = qr(1000, 1); // effectively disabled
        let kernel = SaiosKernel::new(params, ops);
        let mut state = WitnessState {
            entity_id: 0, k_index: 0, sluice_state: SluiceState::Locked,
            latest_sigma_enc: 0, delta_k: anchor.clone(), delta_bar: anchor,
            trajectory: Trajectory::new(), t_k_latest: QR::zero(),
        };
        let mut max_ratio = QR::zero();
        let mut advances = 0u64;
        for tick in 0..100u64 {
            let mag_before = phi_norm_sq_delta(&state.delta_k);
            match kernel.execute_k_step(&mut state) {
                Ok(_) => {
                    advances += 1;
                    let mag_after = phi_norm_sq_delta(&state.delta_k);
                    if !mag_before.is_zero() {
                        let diff = if mag_after >= mag_before {
                            &mag_after - &mag_before
                        } else {
                            &mag_before - &mag_after
                        };
                        let ratio = &diff / &mag_before;
                        let approx = ratio.numer().to_string().parse::<f64>().unwrap_or(0.0)
                            / ratio.denom().to_string().parse::<f64>().unwrap_or(1.0);
                        if tick < 20 {
                            eprintln!("  tick {:3}: ratio = {:.8}", tick, approx);
                        }
                        if ratio > max_ratio { max_ratio = ratio.clone(); }
                    }
                }
                Err(_) => {}
            }
        }
        let max_approx = max_ratio.numer().to_string().parse::<f64>().unwrap_or(0.0)
            / max_ratio.denom().to_string().parse::<f64>().unwrap_or(1.0);
        eprintln!("Advances: {}/100", advances);
        eprintln!("Max ratio: {:.8}", max_approx);
        eprintln!("Recommended: max * 1.2 = {:.8}", max_approx * 1.2);
        // The max ratio determines the correct epsilon_mag_relative
        assert!(advances > 0, "No K advances even with disabled magnitude check");
    }

    #[test]
    fn test_solo_drift_boundary_map_coarse() {
        let b = solo_drift_boundary_map(&qr(1, 100), 200);
        assert!(!b.is_empty(), "No RCF boundaries at ε=1/100");
        eprintln!("ε=1/100 boundaries (first 20): {:?}", &b[..b.len().min(20)]);
    }

    #[test]
    fn test_solo_drift_boundary_map_production() {
        // Production-realistic drift: ε = 1/10000
        let b = solo_drift_boundary_map(&qr(1, 10000), 200);
        assert!(!b.is_empty(), "No RCF boundaries at ε=1/10000 in 200 ticks");
        let first = b[0];
        eprintln!("ε=1/10000: first boundary at tick {}", first);
        assert!(first < 200, "First boundary must be within 200 ticks");
        if b.len() >= 2 {
            let gap = b[1] - b[0];
            eprintln!("ε=1/10000: gap between first two boundaries: {} ticks", gap);
        }
    }

    // ── GATE 1: Baseline ──────────────────────────────────────────────
    #[test]
    fn test_gate1_baseline() {
        let mut fabric = MeshFabric::new(11);
        for _ in 0..50 { fabric.tick(); }
        let r = fabric.report();
        for (i, g) in r.honest_gamma_trajectory.iter().enumerate() {
            assert_eq!(*g, QR::zero(), "Γ_honest ≠ 0 at tick {}", i);
        }
        assert_eq!(r.honest_k_spread, 0);
        let total: usize = r.nodes_advanced_trajectory.iter().sum();
        assert!(total > 0, "No K advances in 50 ticks");
        eprintln!("Baseline: {} node-advances in 50 ticks", total);
    }

    // ── GATE 2: Drift (inject at tick 10, observe accumulation) ───────
    #[test]
    fn test_gate2_drift() {
        let epsilon = qr(1, 100);
        let inject = 10u64;
        let mut fabric = MeshFabric::new(11);
        for t in 0..100 {
            if t == inject { fabric.inject_fault(5, FaultMode::Drift { epsilon: epsilon.clone() }); }
            fabric.tick();
        }
        let r = fabric.report();
        for g in r.gamma_trajectory.iter().take(inject as usize) {
            assert_eq!(*g, QR::zero(), "Pre-inject Γ ≠ 0");
        }
        assert!(r.ticks_until_detected.is_some(), "Drift not detected");
        assert!(r.convergence_achieved, "Honest diverged");
        eprintln!("Drift detected at tick {:?}", r.ticks_until_detected);
    }

    // ── GATE 3: Orbit fork ────────────────────────────────────────────
    #[test]
    fn test_gate3_orbit_fork() {
        let mut fabric = MeshFabric::new(11);
        for t in 0..40 {
            if t == 5 { fabric.inject_fault(0, FaultMode::OrbitFork); }
            fabric.tick();
        }
        let r = fabric.report();
        for g in r.gamma_trajectory.iter().take(5) {
            assert_eq!(*g, QR::zero(), "Pre-fork Γ ≠ 0");
        }
        assert!(r.ticks_until_detected.is_some(), "Fork not detected");
        assert!(r.convergence_achieved, "Honest diverged");
    }

    // ── GATE 4: K-lag ─────────────────────────────────────────────────
    #[test]
    fn test_gate4_klag() {
        let mut fabric = MeshFabric::new(11);
        fabric.inject_fault(3, FaultMode::KLag { resume_at_tick: 30 });
        for _ in 0..60 { fabric.tick(); }
        let r = fabric.report();
        assert!(r.convergence_achieved, "Honest diverged despite K-lag peer");
    }

    // ── GATE 5: Self-detection ────────────────────────────────────────
    #[test]
    fn test_gate5_self_detection() {
        let mut fabric = MeshFabric::new(11);
        fabric.inject_fault(5, FaultMode::OrbitFork);
        for _ in 0..20 { fabric.tick(); }
        let n5 = &fabric.nodes[5];
        assert!(n5.state.sluice_state == SluiceState::Gated || !n5.advanced_last_tick,
            "Forked node must self-detect");
    }

    // ── GATE 6: Reentry ───────────────────────────────────────────────
    #[test]
    fn test_gate6_reentry() {
        let mut fabric = MeshFabric::new(11);
        fabric.inject_fault(5, FaultMode::OrbitFork);
        for _ in 0..15 { fabric.tick(); }
        // Fix node: clear fault, reset to anchor
        fabric.nodes[5].fault = FaultMode::Honest;
        fabric.nodes[5].state.delta_k = canonical_anchor(3, 1);
        fabric.nodes[5].state.delta_bar = canonical_anchor(3, 1);
        fabric.nodes[5].rcf_hash = compute_rcf_hash(&canonical_anchor(3, 1));
        assert!(fabric.attempt_reentry(5, 5), "Reentry with matching RCF must succeed");
        assert_eq!(fabric.nodes[5].state.sluice_state, SluiceState::Shifting);
    }

    // ── 101-node baseline ─────────────────────────────────────────────
    #[test]
    fn test_101_baseline() {
        let mut fabric = MeshFabric::new(101);
        fabric.tick(); fabric.tick();
        let r = fabric.report();
        for g in &r.honest_gamma_trajectory {
            assert_eq!(*g, QR::zero(), "101-node honest Γ ≠ 0");
        }
    }
}
