// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! Sluice Log — Append-Only Log (AOL) for kernel state persistence.
//!
//! The sluice log is the kernel's authoritative state record. Each entry
//! contains a K-index, RCF hash, receipt signature, and sluice state.
//!
//! Ownership model:
//! - The Rust kernel holds an exclusive `flock` on `sluice.bin`.
//! - The Python UI reads a mirrored `state.json` exported by the kernel.
//! - No external process may write to the sluice log.
//!
//! File format (sluice.bin):
//! ```text
//! [HEADER: 32 bytes]
//!   magic:    "SAIOS_SL" (8 bytes)
//!   version:  u32 BE (4 bytes)
//!   entity_id:  u32 BE (4 bytes)
//!   anchor:   [u8; 16] (first 16 bytes of DELTA_ANCHOR_HASH)
//!
//! [ENTRY: 112 bytes each]
//!   k_index:       u64 BE (8 bytes)
//!   rcf_hash:      [u8; 32]
//!   receipt_hash:  [u8; 32]
//!   sluice_state:  u8
//!   sigma_enc:     u32 BE (4 bytes)
//!   t_k_numer:     i64 BE (8 bytes)
//!   t_k_denom:     u64 BE (8 bytes)
//!   timestamp_ns:  u64 BE (8 bytes)
//!   _reserved:     [u8; 11]
//! ```
//!
//! Register: D.SAIOS.1, D.CHAIN.1.

use std::fs::{File, OpenOptions};
use std::io::{self, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};

use fs2::FileExt;
use num_rational::BigRational;
use num_traits::ToPrimitive;

use crate::constants::delta_anchor_hash;

type Q = BigRational;

const MAGIC: &[u8; 8] = b"SAIOS_SL";
const VERSION: u32 = 1;
const HEADER_SIZE: usize = 32;
const ENTRY_SIZE: usize = 112;

/// A single sluice log entry.
#[derive(Debug, Clone)]
pub struct SluiceEntry {
    pub k_index: u64,
    pub rcf_hash: [u8; 32],
    pub receipt_hash: [u8; 32],
    pub sluice_state: u8,
    pub sigma_enc: u32,
    pub t_k_numer: i64,
    pub t_k_denom: u64,
    pub timestamp_ns: u64,
}

impl SluiceEntry {
    /// Serialize entry to 112-byte wire format.
    pub fn to_bytes(&self) -> [u8; ENTRY_SIZE] {
        let mut buf = [0u8; ENTRY_SIZE];
        buf[0..8].copy_from_slice(&self.k_index.to_be_bytes());
        buf[8..40].copy_from_slice(&self.rcf_hash);
        buf[40..72].copy_from_slice(&self.receipt_hash);
        buf[72] = self.sluice_state;
        buf[73..77].copy_from_slice(&self.sigma_enc.to_be_bytes());
        buf[77..85].copy_from_slice(&self.t_k_numer.to_be_bytes());
        buf[85..93].copy_from_slice(&self.t_k_denom.to_be_bytes());
        buf[93..101].copy_from_slice(&self.timestamp_ns.to_be_bytes());
        // bytes 101..112 reserved (zeros)
        buf
    }

    /// Deserialize entry from 112-byte wire format.
    pub fn from_bytes(buf: &[u8; ENTRY_SIZE]) -> Self {
        Self {
            k_index: u64::from_be_bytes(buf[0..8].try_into().unwrap()),
            rcf_hash: buf[8..40].try_into().unwrap(),
            receipt_hash: buf[40..72].try_into().unwrap(),
            sluice_state: buf[72],
            sigma_enc: u32::from_be_bytes(buf[73..77].try_into().unwrap()),
            t_k_numer: i64::from_be_bytes(buf[77..85].try_into().unwrap()),
            t_k_denom: u64::from_be_bytes(buf[85..93].try_into().unwrap()),
            timestamp_ns: u64::from_be_bytes(buf[93..101].try_into().unwrap()),
        }
    }

    /// Create an entry from kernel output values.
    pub fn from_k_step(
        k_index: u64,
        rcf_hash: [u8; 32],
        receipt_hash: [u8; 32],
        sluice_state: u8,
        sigma_enc: u32,
        t_k: &Q,
    ) -> Self {
        let t_k_numer = t_k.numer().to_i64().unwrap_or(i64::MAX);
        let t_k_denom = t_k.denom().to_u64().unwrap_or(1);
        let timestamp_ns = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0);
        Self {
            k_index,
            rcf_hash,
            receipt_hash,
            sluice_state,
            sigma_enc,
            t_k_numer,
            t_k_denom,
            timestamp_ns,
        }
    }
}

/// The Sluice Log — append-only binary log with exclusive file lock.
pub struct SluiceLog {
    file: File,
    path: PathBuf,
    entity_id: u32,
    entry_count: u64,
}

impl SluiceLog {
    /// Open or create the sluice log at `path`.
    ///
    /// Acquires an exclusive advisory lock (flock). If the file exists,
    /// validates the header. If not, writes a fresh header.
    pub fn open(path: &Path, entity_id: u32) -> io::Result<Self> {
        let exists = path.exists();
        let mut file = OpenOptions::new()
            .read(true)
            .write(true)
            .create(true)
            .truncate(false)
            .open(path)?;

        // Acquire exclusive lock (safe, via fs2)
        file.try_lock_exclusive().map_err(|_| {
            io::Error::new(
                io::ErrorKind::WouldBlock,
                "sluice.bin is locked by another kernel instance",
            )
        })?;

        if exists && file.metadata()?.len() >= HEADER_SIZE as u64 {
            // Validate existing header
            let mut header = [0u8; HEADER_SIZE];
            file.read_exact(&mut header)?;
            if &header[0..8] != MAGIC {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "sluice.bin: invalid magic bytes",
                ));
            }
            let file_version = u32::from_be_bytes(header[8..12].try_into().unwrap());
            if file_version != VERSION {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("sluice.bin: version mismatch (got {file_version}, expected {VERSION})"),
                ));
            }
            let file_entity_id = u32::from_be_bytes(header[12..16].try_into().unwrap());
            if file_entity_id != entity_id {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("sluice.bin: entity_id mismatch (got {file_entity_id}, expected {entity_id})"),
                ));
            }
            let data_len = file.metadata()?.len() as usize - HEADER_SIZE;
            let entry_count = (data_len / ENTRY_SIZE) as u64;

            Ok(Self {
                file,
                path: path.to_path_buf(),
                entity_id,
                entry_count,
            })
        } else {
            // Write fresh header
            let mut header = [0u8; HEADER_SIZE];
            header[0..8].copy_from_slice(MAGIC);
            header[8..12].copy_from_slice(&VERSION.to_be_bytes());
            header[12..16].copy_from_slice(&entity_id.to_be_bytes());
            let anchor = delta_anchor_hash();
            header[16..32].copy_from_slice(&anchor[0..16]);

            file.seek(SeekFrom::Start(0))?;
            file.write_all(&header)?;
            file.sync_all()?;

            Ok(Self {
                file,
                path: path.to_path_buf(),
                entity_id,
                entry_count: 0,
            })
        }
    }

    /// Append an entry to the log. Enforces monotonic K-index.
    pub fn append(&mut self, entry: &SluiceEntry) -> io::Result<()> {
        // Verify monotonic K-index
        if self.entry_count > 0 {
            let last = self.read_entry(self.entry_count - 1)?;
            if entry.k_index <= last.k_index {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!(
                        "K-index not monotonic: {} <= {}",
                        entry.k_index, last.k_index
                    ),
                ));
            }
        }

        let offset = HEADER_SIZE as u64 + self.entry_count * ENTRY_SIZE as u64;
        self.file.seek(SeekFrom::Start(offset))?;
        self.file.write_all(&entry.to_bytes())?;
        self.file.sync_all()?;
        self.entry_count += 1;
        Ok(())
    }

    /// Read entry at index (0-based).
    pub fn read_entry(&mut self, index: u64) -> io::Result<SluiceEntry> {
        if index >= self.entry_count {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                format!("entry index {index} out of range (count={})", self.entry_count),
            ));
        }
        let offset = HEADER_SIZE as u64 + index * ENTRY_SIZE as u64;
        self.file.seek(SeekFrom::Start(offset))?;
        let mut buf = [0u8; ENTRY_SIZE];
        self.file.read_exact(&mut buf)?;
        Ok(SluiceEntry::from_bytes(&buf))
    }

    /// Read the latest entry (highest K-index).
    pub fn latest(&mut self) -> io::Result<Option<SluiceEntry>> {
        if self.entry_count == 0 {
            return Ok(None);
        }
        self.read_entry(self.entry_count - 1).map(Some)
    }

    /// Total number of entries in the log.
    pub fn len(&self) -> u64 {
        self.entry_count
    }

    /// Whether the log is empty.
    pub fn is_empty(&self) -> bool {
        self.entry_count == 0
    }

    /// Export current state as JSON for the Python UI (read-only mirror).
    ///
    /// Writes to `state.json` alongside the sluice log.
    pub fn export_state_json(&mut self) -> io::Result<()> {
        let state_path = self.path.with_file_name("state.json");
        let latest = self.latest()?;

        let json = if let Some(entry) = latest {
            format!(
                concat!(
                    "{{\n",
                    "  \"schema\": \"saios-kernel-state/v1\",\n",
                    "  \"entity_id\": {},\n",
                    "  \"k_index\": {},\n",
                    "  \"sluice_state\": {},\n",
                    "  \"rcf_hash\": \"0x{}\",\n",
                    "  \"receipt_hash\": \"0x{}\",\n",
                    "  \"sigma_enc\": {},\n",
                    "  \"t_k\": \"{}/{}\",\n",
                    "  \"entry_count\": {},\n",
                    "  \"boot_status\": \"operational\",\n",
                    "  \"authority\": \"SAIOS-AUTHORITY-v1\"\n",
                    "}}\n"
                ),
                self.entity_id,
                entry.k_index,
                entry.sluice_state,
                entry.rcf_hash.iter().map(|b| format!("{b:02x}")).collect::<String>(),
                entry.receipt_hash.iter().map(|b| format!("{b:02x}")).collect::<String>(),
                entry.sigma_enc,
                entry.t_k_numer,
                entry.t_k_denom,
                self.entry_count,
            )
        } else {
            format!(
                concat!(
                    "{{\n",
                    "  \"schema\": \"saios-kernel-state/v1\",\n",
                    "  \"entity_id\": {},\n",
                    "  \"k_index\": null,\n",
                    "  \"sluice_state\": null,\n",
                    "  \"rcf_hash\": null,\n",
                    "  \"receipt_hash\": null,\n",
                    "  \"sigma_enc\": null,\n",
                    "  \"t_k\": null,\n",
                    "  \"entry_count\": 0,\n",
                    "  \"boot_status\": \"booting\",\n",
                    "  \"authority\": \"SAIOS-AUTHORITY-v1\"\n",
                    "}}\n"
                ),
                self.entity_id,
            )
        };

        std::fs::write(state_path, json)?;
        Ok(())
    }
}

// ─── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use num_bigint::BigInt;
    use num_traits::One;

    fn temp_sluice_path() -> PathBuf {
        let dir = std::env::temp_dir().join("saios-test-sluice");
        fs::create_dir_all(&dir).unwrap();
        dir.join(format!(
            "sluice-{}.bin",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ))
    }

    #[test]
    fn test_create_and_reopen() {
        let path = temp_sluice_path();
        {
            let log = SluiceLog::open(&path, 1).unwrap();
            assert_eq!(log.len(), 0);
            assert!(log.is_empty());
        }
        // Reopen
        {
            let log = SluiceLog::open(&path, 1).unwrap();
            assert_eq!(log.len(), 0);
        }
        fs::remove_file(&path).ok();
    }

    #[test]
    fn test_append_and_read() {
        let path = temp_sluice_path();
        {
            let mut log = SluiceLog::open(&path, 42).unwrap();
            let t_k = Q::new(BigInt::from(3), BigInt::from(7));
            let entry = SluiceEntry::from_k_step(
                1,
                [0xAA; 32],
                [0xBB; 32],
                0x01, // LOCKED
                12345,
                &t_k,
            );
            log.append(&entry).unwrap();
            assert_eq!(log.len(), 1);

            let read = log.read_entry(0).unwrap();
            assert_eq!(read.k_index, 1);
            assert_eq!(read.rcf_hash, [0xAA; 32]);
            assert_eq!(read.receipt_hash, [0xBB; 32]);
            assert_eq!(read.sluice_state, 0x01);
            assert_eq!(read.sigma_enc, 12345);
            assert_eq!(read.t_k_numer, 3);
            assert_eq!(read.t_k_denom, 7);
        }
        fs::remove_file(&path).ok();
    }

    #[test]
    fn test_monotonic_enforcement() {
        let path = temp_sluice_path();
        let mut log = SluiceLog::open(&path, 1).unwrap();
        let t = Q::one();

        let e1 = SluiceEntry::from_k_step(5, [0; 32], [0; 32], 1, 0, &t);
        log.append(&e1).unwrap();

        // Same K-index should fail
        let e2 = SluiceEntry::from_k_step(5, [0; 32], [0; 32], 1, 0, &t);
        assert!(log.append(&e2).is_err());

        // Lower K-index should fail
        let e3 = SluiceEntry::from_k_step(3, [0; 32], [0; 32], 1, 0, &t);
        assert!(log.append(&e3).is_err());

        // Higher K-index should succeed
        let e4 = SluiceEntry::from_k_step(6, [0; 32], [0; 32], 1, 0, &t);
        assert!(log.append(&e4).is_ok());

        assert_eq!(log.len(), 2);
        fs::remove_file(&path).ok();
    }

    #[test]
    fn test_entry_round_trip() {
        let entry = SluiceEntry {
            k_index: 0xDEADBEEF_CAFEBABE,
            rcf_hash: [42; 32],
            receipt_hash: [99; 32],
            sluice_state: 0x03,
            sigma_enc: 0x12345678,
            t_k_numer: -123456789,
            t_k_denom: 987654321,
            timestamp_ns: 1234567890123456789,
        };
        let bytes = entry.to_bytes();
        let decoded = SluiceEntry::from_bytes(&bytes);
        assert_eq!(decoded.k_index, entry.k_index);
        assert_eq!(decoded.rcf_hash, entry.rcf_hash);
        assert_eq!(decoded.receipt_hash, entry.receipt_hash);
        assert_eq!(decoded.sluice_state, entry.sluice_state);
        assert_eq!(decoded.sigma_enc, entry.sigma_enc);
        assert_eq!(decoded.t_k_numer, entry.t_k_numer);
        assert_eq!(decoded.t_k_denom, entry.t_k_denom);
        assert_eq!(decoded.timestamp_ns, entry.timestamp_ns);
    }

    #[test]
    fn test_export_state_json() {
        let path = temp_sluice_path();
        let mut log = SluiceLog::open(&path, 7).unwrap();
        let t = Q::new(BigInt::from(1), BigInt::from(2));
        let entry = SluiceEntry::from_k_step(1, [0x11; 32], [0x22; 32], 0x01, 100, &t);
        log.append(&entry).unwrap();
        log.export_state_json().unwrap();

        let json_path = path.with_file_name("state.json");
        assert!(json_path.exists());
        let content = fs::read_to_string(&json_path).unwrap();
        assert!(content.contains("\"k_index\": 1"));
        assert!(content.contains("\"boot_status\": \"operational\""));
        assert!(content.contains("\"authority\": \"SAIOS-AUTHORITY-v1\""));

        fs::remove_file(&path).ok();
        fs::remove_file(&json_path).ok();
    }

    #[test]
    fn test_entity_id_mismatch_rejected() {
        let path = temp_sluice_path();
        {
            let _log = SluiceLog::open(&path, 1).unwrap();
        }
        // Reopen with different entity_id should fail
        let result = SluiceLog::open(&path, 999);
        assert!(result.is_err());
        fs::remove_file(&path).ok();
    }
}
