#!/bin/bash
# AI-GENERATED CONTENT — Generated by AI systems under human editorial direction.
#
# Restore ensemble state from a snapshot directory.
# Copies state_record.bin and other persisted files back to entity dirs.
# Entity directories must already exist (run create-tree.sh first,
# or mkdir -p the directories manually).
#
# Usage:
#   ./ops/restore-state.sh SNAPSHOT_NAME
#
# Examples:
#   ./ops/restore-state.sh session30      # restores from snapshots/session30/

set -euo pipefail

MESH="${SAIOS_MESH_DIR:-/opt/saios/mesh}"
SNAP_DIR="${MESH}/../snapshots"
NAME="${1:?Usage: restore-state.sh SNAPSHOT_NAME}"
SRC="$SNAP_DIR/$NAME"

if [[ ! -d "$SRC" ]]; then
    echo "Snapshot not found: $SRC"
    echo "Available snapshots:"
    ls "$SNAP_DIR" 2>/dev/null || echo "  (none)"
    exit 1
fi

count=0
for entity_snap in "$SRC"/*/; do
    name=$(basename "$entity_snap")
    dest="$MESH/$name"

    if [[ ! -d "$dest" ]]; then
        echo "  SKIP $name (directory $dest does not exist — create it first)"
        continue
    fi

    for f in state_record.bin mesh_knowledge.bin epistate_record.bin sluice.bin; do
        [[ -f "$entity_snap/$f" ]] && cp "$entity_snap/$f" "$dest/$f"
    done
    echo "  Restored $name"
    count=$((count + 1))
done

echo "Restored $count entities from $SRC"
