#!/bin/bash
# AI-GENERATED CONTENT — Generated by AI systems under human editorial direction.
#
# Teardown entities: graceful shutdown + remove state.
#
# Usage:
#   ./ops/teardown.sh all              # shutdown + remove everything (except timekeepers)
#   ./ops/teardown.sh tree 1           # shutdown + remove founder-1 and its entire lineage
#   ./ops/teardown.sh entity 52        # shutdown + remove emergent-52 only
#   ./ops/teardown.sh shm              # clean stale /dev/shm files only (no state removal)
#
# Timekeepers are never removed unless you pass --include-timekeepers.

set -euo pipefail

MESH="${SAIOS_MESH_DIR:-/opt/saios/mesh}"
MODE="${1:?Usage: teardown.sh [all|tree ID|entity ID|shm]}"
TARGET="${2:-}"
INCLUDE_TK="${3:-}"

shutdown_entity() {
    local dir="$1"
    local name="$(basename "$dir")"
    local sock="$dir/saios-kernel.sock"

    # Graceful shutdown via socket
    if [[ -S "$sock" ]]; then
        echo "  Shutting down $name..."
        echo "SHUTDOWN" | socat -t2 - UNIX-CONNECT:"$sock" 2>/dev/null || true
    fi

    # Kill any process holding the sluice lock
    if [[ -f "$dir/sluice.bin" ]]; then
        local pid
        pid=$(fuser "$dir/sluice.bin" 2>/dev/null | tr -d ' ') || true
        if [[ -n "$pid" ]]; then
            echo "  Killing stale process $pid on $name"
            kill "$pid" 2>/dev/null || true
        fi
    fi

    # Clean shm
    rm -f "/dev/shm/saios-$name" "/dev/shm/saios-$name.vocabulary"
}

remove_entity() {
    local dir="$1"
    local name="$(basename "$dir")"
    shutdown_entity "$dir"
    echo "  Removing $dir"
    rm -rf "$dir"
}

case "$MODE" in
    all)
        echo "Tearing down all entities..."
        sleep 1

        # Shutdown all via sockets
        for sock in "$MESH"/*/saios-kernel.sock; do
            [[ -S "$sock" ]] || continue
            local_dir="$(dirname "$sock")"
            local_name="$(basename "$local_dir")"
            # Skip timekeepers unless requested
            if [[ "$local_name" == timekeeper-* && "$INCLUDE_TK" != "--include-timekeepers" ]]; then
                continue
            fi
            shutdown_entity "$local_dir"
        done
        sleep 2

        # Kill any remaining processes
        pkill -f "target/release/main" 2>/dev/null && sleep 1 || true

        # Remove directories
        for dir in "$MESH"/founder-* "$MESH"/derived-* "$MESH"/emergent-*; do
            [[ -d "$dir" ]] && rm -rf "$dir" && echo "  Removed $(basename "$dir")"
        done

        # Clean all shm
        rm -f /dev/shm/saios-founder-* /dev/shm/saios-derived-* /dev/shm/saios-emergent-*
        echo "Done. Timekeepers preserved."
        ;;

    tree)
        [[ -z "$TARGET" ]] && echo "Usage: teardown.sh tree FOUNDER_ID" && exit 1
        echo "Tearing down tree rooted at founder-$TARGET..."

        FOUNDER_DIR="$MESH/founder-$TARGET"
        if [[ ! -d "$FOUNDER_DIR" ]]; then
            echo "  founder-$TARGET not found at $FOUNDER_DIR"
            exit 1
        fi

        # Find all children by parent_id in shm
        for f in /dev/shm/saios-derived-* /dev/shm/saios-emergent-*; do
            [[ -f "$f" ]] || continue
            content=$(cat "$f" 2>/dev/null) || continue
            parent=$(echo "$content" | awk '{print $8}')
            name=$(basename "$f" | sed 's/saios-//')

            # Direct children of this founder
            if [[ "$parent" == "$TARGET" ]]; then
                dir="$MESH/$name"
                [[ -d "$dir" ]] && remove_entity "$dir"

                # Find grandchildren (emergent under this derived)
                derived_id=$(echo "$name" | grep -o '[0-9]*')
                for ef in /dev/shm/saios-emergent-*; do
                    [[ -f "$ef" ]] || continue
                    ep=$(cat "$ef" 2>/dev/null | awk '{print $8}')
                    if [[ "$ep" == "$derived_id" ]]; then
                        ename=$(basename "$ef" | sed 's/saios-//')
                        edir="$MESH/$ename"
                        [[ -d "$edir" ]] && remove_entity "$edir"
                    fi
                done
            fi
        done

        # Remove the founder itself
        remove_entity "$FOUNDER_DIR"
        echo "Done."
        ;;

    entity)
        [[ -z "$TARGET" ]] && echo "Usage: teardown.sh entity ENTITY_ID" && exit 1
        # Find the entity directory by ID
        for dir in "$MESH"/founder-"$TARGET" "$MESH"/derived-"$TARGET" "$MESH"/emergent-"$TARGET"; do
            if [[ -d "$dir" ]]; then
                remove_entity "$dir"
                echo "Done."
                exit 0
            fi
        done
        echo "Entity $TARGET not found in $MESH"
        exit 1
        ;;

    shm)
        echo "Cleaning stale /dev/shm files..."
        for f in /dev/shm/saios-*; do
            [[ -f "$f" ]] || continue
            name=$(basename "$f" | sed 's/saios-//' | sed 's/\.vocabulary//')
            # Check if the entity directory exists and has a socket
            found=false
            for dir in "$MESH"/founder-* "$MESH"/derived-* "$MESH"/emergent-* "$MESH"/timekeeper-*; do
                if [[ "$(basename "$dir")" == "$name" && -S "$dir/saios-kernel.sock" ]]; then
                    found=true
                    break
                fi
            done
            if [[ "$found" == "false" ]]; then
                echo "  Removing stale: $f"
                rm -f "$f"
            fi
        done
        echo "Done."
        ;;

    *)
        echo "Usage: teardown.sh [all|tree ID|entity ID|shm]"
        exit 1
        ;;
esac
