// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! D.SENSE.TOUCH.1 — Adjacency structure: what the system FEELS.
//!
//! Touch orbits the observation at mesoscopic radius — the spatial texture,
//! local coherence, and discrete objects discovered by flood fill.
//!
//! Three levels of measurement:
//! 1. Global cohesion χ = same / (same + diff) — the average field.
//! 2. Per-cell χ_i = same_neighbors_i / total_neighbors_i — local order parameter.
//!    Bulk (χ_i = 1), surface state (0 < χ_i < 1), point defect (χ_i = 0).
//! 3. CohesionClusters — connected components as quasiparticles with bbox,
//!    internal cohesion, and mass distribution.
//!
//! Touch does not compete with other senses. It compounds.

use num_bigint::BigInt;
use num_traits::{Zero, One};
use crate::engine::Q;

/// A connected region of same-value cells — a discrete algebraic object.
///
/// Not a "shape" — a connected subset discovered by measuring local invariance.
/// The flood fill groups cells by value adjacency. Each cluster carries its
/// spatial localization (bbox), structural integrity (internal_cohesion),
/// mass distribution (cell_indices), and torsion anchoring (stabilizer_order).
#[derive(Debug, Clone)]
pub struct CohesionCluster {
    /// Which cells belong to this cluster.
    pub cell_indices: Vec<usize>,
    /// The value shared by all cells in this cluster.
    pub value: i64,
    /// Internal cohesion: fraction of this cluster's adjacencies that are same-value.
    /// χ = 1 means rigid (every neighbor of every interior cell matches).
    /// χ < 1 means the cluster has boundary cells touching other values.
    pub internal_cohesion: Q,
    /// Bounding box: (min_row, min_col, max_row, max_col).
    pub bbox: (usize, usize, usize, usize),
    /// Stabilizer order: how many symmetry operations fix ALL cells in this cluster.
    /// High = the cluster sits on a symmetry axis (anchored).
    /// 0 = no symmetry computed yet (set by attach_stabilizers).
    pub stabilizer_order: usize,
    /// β_0: number of connected components (always 1 for a single cluster).
    pub betti_0: usize,
    /// β_1: number of holes enclosed by this cluster.
    /// Computed via flood fill: non-cluster cells completely surrounded
    /// by cluster cells form enclosed regions. Each is a hole.
    /// An "O" shape has β_1 = 1. A filled square has β_1 = 0.
    /// An "8" shape has β_1 = 2. This is the first homology.
    pub betti_1: usize,
    /// Interior cells: non-cluster cells enclosed by this cluster's boundary.
    /// Pre-computed during betti_1 flood-fill. The engine fills these directly
    /// without re-running topology detection.
    pub interior_cells: Vec<usize>,
}

/// Adjacency structure — what the system FEELS in the observation.
/// Which values touch which, and how — the spatial texture.
///
/// Per-cell χ_i is a local order parameter: bulk (χ_i=1), boundary (0<χ_i<1),
/// point defect (χ_i=0). The global cohesion is the average field.
/// Clusters are the quasiparticles discovered by flood fill.
#[derive(Debug, Clone)]
pub struct AdjacencyStructure {
    /// Number of same-value adjacencies (cell neighbors with matching values).
    pub same_adjacencies: usize,
    /// Number of different-value adjacencies.
    pub diff_adjacencies: usize,
    /// Cohesion ratio: same / (same + diff). High = clustered. Low = fragmented.
    pub cohesion: Q,
    /// Number of connected components (regions of same value).
    pub component_count: usize,
    /// Per-cell local cohesion χ_i = same_neighbors / total_neighbors.
    /// χ_i = 1: bulk (interior of object). χ_i = 0: point defect (isolated).
    /// 0 < χ_i < 1: surface state (boundary).
    pub per_cell_cohesion: Vec<Q>,
    /// Per-cell stabilizer order: how many exact symmetry operations fix this cell.
    /// Includes identity (minimum = 1 when symmetry is computed).
    /// 0 = symmetry not yet attached. High = cell sits on symmetry axis.
    pub per_cell_stabilizer: Vec<usize>,
    /// Connected components as algebraic objects.
    pub clusters: Vec<CohesionCluster>,
}

/// Compute the adjacency structure — what the system FEELS.
///
/// Three levels of measurement:
/// 1. Global cohesion χ = same / (same + diff) — the average field.
/// 2. Per-cell χ_i = same_neighbors_i / total_neighbors_i — local order parameter.
///    Bulk (χ_i = 1), surface state (0 < χ_i < 1), point defect (χ_i = 0).
/// 3. CohesionClusters — connected components as quasiparticles with bbox,
///    internal cohesion, and mass distribution.
pub fn compute_adjacency_structure(values: &[i64], rows: usize, cols: usize) -> AdjacencyStructure {
    let n = values.len();
    if n == 0 || rows == 0 || cols == 0 || rows * cols != n {
        return AdjacencyStructure {
            same_adjacencies: 0, diff_adjacencies: 0,
            cohesion: Q::zero(), component_count: 0,
            per_cell_cohesion: vec![],
            per_cell_stabilizer: vec![],
            clusters: vec![],
        };
    }

    // ── Pass 1: Global and per-cell adjacency counts ──
    let mut same = 0usize;
    let mut diff = 0usize;
    let mut cell_same = vec![0u32; n];
    let mut cell_total = vec![0u32; n];

    for r in 0..rows {
        for c in 0..cols {
            let idx = r * cols + c;
            if idx >= n { continue; }
            // Check all 4 neighbors for per-cell χ_i
            let neighbors: [(usize, usize); 4] = [
                (r.wrapping_sub(1), c), (r + 1, c),
                (r, c.wrapping_sub(1)), (r, c + 1),
            ];
            for &(nr, nc) in &neighbors {
                if nr < rows && nc < cols {
                    let ni = nr * cols + nc;
                    if ni < n {
                        cell_total[idx] += 1;
                        if values[idx] == values[ni] {
                            cell_same[idx] += 1;
                        }
                    }
                }
            }
            // Global counts (right + down only to avoid double-counting)
            if c + 1 < cols {
                let right = r * cols + (c + 1);
                if right < n {
                    if values[idx] == values[right] { same += 1; } else { diff += 1; }
                }
            }
            if r + 1 < rows {
                let down = (r + 1) * cols + c;
                if down < n {
                    if values[idx] == values[down] { same += 1; } else { diff += 1; }
                }
            }
        }
    }

    let total_adj = same + diff;
    let cohesion = if total_adj > 0 {
        Q::new(BigInt::from(same as i64), BigInt::from(total_adj as i64))
    } else { Q::zero() };

    // ── Per-cell χ_i ──
    let per_cell_cohesion: Vec<Q> = (0..n).map(|i| {
        if cell_total[i] > 0 {
            Q::new(BigInt::from(cell_same[i] as i64), BigInt::from(cell_total[i] as i64))
        } else {
            Q::zero()
        }
    }).collect();

    // ── Pass 2: Flood fill → CohesionClusters ──
    let mut visited = vec![false; n];
    let mut clusters: Vec<CohesionCluster> = Vec::new();

    for start in 0..n {
        if visited[start] { continue; }
        visited[start] = true;
        let target = values[start];
        let mut cell_indices = vec![start];
        let mut stack = vec![start];

        while let Some(pos) = stack.pop() {
            let r = pos / cols;
            let c = pos % cols;
            for &(nr, nc) in &[(r.wrapping_sub(1), c), (r + 1, c), (r, c.wrapping_sub(1)), (r, c + 1)] {
                if nr < rows && nc < cols {
                    let ni = nr * cols + nc;
                    if ni < n && !visited[ni] && values[ni] == target {
                        visited[ni] = true;
                        stack.push(ni);
                        cell_indices.push(ni);
                    }
                }
            }
        }

        // Bounding box
        let mut min_r = rows;
        let mut max_r = 0;
        let mut min_c = cols;
        let mut max_c = 0;
        for &idx in &cell_indices {
            let r = idx / cols;
            let c = idx % cols;
            if r < min_r { min_r = r; }
            if r > max_r { max_r = r; }
            if c < min_c { min_c = c; }
            if c > max_c { max_c = c; }
        }

        // Internal cohesion: fraction of this cluster's neighbor-pairs that are same-value.
        // A cluster's adjacency = all edges from cluster cells to any neighbor.
        // Internal = edges where neighbor is also in cluster (same value AND connected).
        let mut cluster_same = 0u64;
        let mut cluster_total = 0u64;
        for &idx in &cell_indices {
            cluster_same += cell_same[idx] as u64;
            cluster_total += cell_total[idx] as u64;
        }
        let internal_cohesion = if cluster_total > 0 {
            Q::new(BigInt::from(cluster_same as i64), BigInt::from(cluster_total as i64))
        } else {
            Q::zero()
        };

        // β_1: count holes enclosed by this cluster.
        // A hole = connected component of non-cluster cells that doesn't
        // touch the grid boundary. Flood fill from boundary non-cluster cells;
        // unreached non-cluster cells inside the bbox are enclosed.
        let (betti_1, interior_cells) = if rows * cols != n || n == 0 { (0, vec![]) } else {
            let mut in_cluster = vec![false; n];
            for &idx in &cell_indices { if idx < n { in_cluster[idx] = true; } }

            // Flood fill from grid boundary through non-cluster cells
            let mut exterior = vec![false; n];
            let mut fill_stack: Vec<usize> = Vec::new();
            for r in 0..rows {
                for c in 0..cols {
                    if r == 0 || r == rows - 1 || c == 0 || c == cols - 1 {
                        let idx = r * cols + c;
                        if !in_cluster[idx] && !exterior[idx] {
                            exterior[idx] = true;
                            fill_stack.push(idx);
                        }
                    }
                }
            }
            while let Some(idx) = fill_stack.pop() {
                let r = idx / cols;
                let c = idx % cols;
                for (dr, dc) in &[(-1i32,0),(1,0),(0,-1),(0,1)] {
                    let nr = r as i32 + dr;
                    let nc = c as i32 + dc;
                    if nr >= 0 && nr < rows as i32 && nc >= 0 && nc < cols as i32 {
                        let ni = nr as usize * cols + nc as usize;
                        if !in_cluster[ni] && !exterior[ni] {
                            exterior[ni] = true;
                            fill_stack.push(ni);
                        }
                    }
                }
            }

            // Collect enclosed cells and count enclosed components (holes)
            let mut hole_visited = vec![false; n];
            let mut holes = 0usize;
            let mut enclosed: Vec<usize> = Vec::new();
            for r in min_r..=max_r {
                for c in min_c..=max_c {
                    let idx = r * cols + c;
                    if !in_cluster[idx] && !exterior[idx] && !hole_visited[idx] {
                        holes += 1;
                        let mut hs: Vec<usize> = vec![idx];
                        hole_visited[idx] = true;
                        enclosed.push(idx);
                        while let Some(hi) = hs.pop() {
                            let hr = hi / cols;
                            let hc = hi % cols;
                            for (dr, dc) in &[(-1i32,0),(1,0),(0,-1),(0,1)] {
                                let nr = hr as i32 + dr;
                                let nc = hc as i32 + dc;
                                if nr >= 0 && nr < rows as i32 && nc >= 0 && nc < cols as i32 {
                                    let ni = nr as usize * cols + nc as usize;
                                    if !in_cluster[ni] && !exterior[ni] && !hole_visited[ni] {
                                        hole_visited[ni] = true;
                                        hs.push(ni);
                                        enclosed.push(ni);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            (holes, enclosed)
        };

        clusters.push(CohesionCluster {
            cell_indices,
            value: target,
            internal_cohesion,
            bbox: (min_r, min_c, max_r, max_c),
            stabilizer_order: 0,
            betti_0: 1, // single connected component by construction
            betti_1,
            interior_cells,
        });
    }

    let component_count = clusters.len();
    AdjacencyStructure {
        same_adjacencies: same, diff_adjacencies: diff,
        cohesion, component_count,
        per_cell_cohesion,
        per_cell_stabilizer: vec![0; n], // attached after symmetry is computed
        clusters,
    }
}

/// Attach per-cell stabilizer orders from the symmetry group.
///
/// For each cell, the stabilizer is the subgroup of G that fixes it:
/// Stab(i) = { g ∈ G : g(i) = i }. The order |Stab(i)| tells the system
/// how anchored cell i is in the symmetry structure.
///
/// - On a symmetry axis: high stabilizer (fixed by reflection, rotation, etc.)
/// - Off-axis: low stabilizer (only identity fixes it)
/// - Cluster stabilizer: min stabilizer across all cells (the weakest link)
///
/// The permutation matrix for each symmetry element directly encodes
/// which cells are fixed: cell i is fixed by element g iff g.matrix[i][i] = 1.
pub fn attach_stabilizers(touch: &mut AdjacencyStructure, symmetry: &super::vision::SymmetryGroup) {
    let n = touch.per_cell_cohesion.len();
    if n == 0 { return; }

    // Count exact symmetries that fix each cell.
    // Identity always fixes every cell — start at 1.
    let mut stabilizer = vec![1usize; n];

    for elem in &symmetry.elements {
        if !elem.invariance_residual.is_zero() { continue; } // only exact symmetries
        // A permutation matrix has exactly one 1 per row.
        // Cell i is fixed iff the 1 in row i is at column i (diagonal).
        for i in 0..n.min(elem.operator.matrix.len()) {
            if i < elem.operator.matrix[i].len() && elem.operator.matrix[i][i] == Q::one() {
                stabilizer[i] += 1;
            }
        }
    }

    touch.per_cell_stabilizer = stabilizer;

    // Cluster stabilizer: how many symmetries fix ALL cells in the cluster.
    // This is |∩ Stab(i) for i in cluster| — the intersection of per-cell stabilizers.
    // Minimum per-cell stabilizer is a conservative bound.
    for cluster in &mut touch.clusters {
        cluster.stabilizer_order = cluster.cell_indices.iter()
            .map(|&i| touch.per_cell_stabilizer.get(i).copied().unwrap_or(0))
            .min()
            .unwrap_or(0);
    }
}

/// Centroid of a cluster — center of mass in grid coordinates.
pub fn cluster_centroid(cluster: &CohesionCluster, cols: usize) -> (usize, usize) {
    if cluster.cell_indices.is_empty() || cols == 0 {
        return (0, 0);
    }
    let sum_r: usize = cluster.cell_indices.iter().map(|&i| i / cols).sum();
    let sum_c: usize = cluster.cell_indices.iter().map(|&i| i % cols).sum();
    let n = cluster.cell_indices.len();
    (sum_r / n, sum_c / n)
}
