// AI-GENERATED CONTENT — This source code was generated by AI systems under
// human editorial direction. It was not written by the researcher.
// See /opt/saios/DISCLAIMER.md for full context.
//
//! D.SENSE.VISION.1 — Symmetry group: what the system SEES.
//!
//! Vision orbits the observation at global radius — the invariance structure,
//! the torsion spectrum, the transmutation gradient. Vision sees what HELD
//! and what BROKE across the transformation.
//!
//! Vision does not compete with other senses. It compounds.
//! The symmetry group feeds into SensoryCongruence, Comprehension,
//! and the escalation pipeline.
//!
//! Vision must see the TRANSFORMATION (input→output), not the INPUT's
//! symmetry alone. compute_symmetry_group measures one grid's invariance.
//! see_transformation (VIII.4 purged) was the transliminal bridge.
//! That bridge now lives in peel_manifold through T = Δ_target - Δ_source.

use num_bigint::BigInt;
use num_traits::{Zero, One};
use crate::engine::{Q, Operator};

/// A symmetry element — one invariance of the observation.
#[derive(Debug, Clone)]
pub struct SymmetryElement {
    /// The operator that leaves the Delta invariant: A·Δ·A⁻¹ ≈ Δ.
    pub operator: Operator,
    /// Torsion order: smallest p where A^p = I. p=2 reflection, p=4 rotation90.
    pub torsion_order: usize,
    /// How close to invariance: ‖A·Δ·A⁻¹ - Δ‖². Zero = exact symmetry.
    pub invariance_residual: Q,
    /// Transmutation residual: R(φ) = ‖φ(source) - target‖.
    /// Measures how well this symmetry element relates source to target.
    /// Zero = the grid has transmuted through exactly this symmetry.
    /// The entity perceives the transmutation, it does not execute it.
    pub transmutation_residual: Q,
}

/// The symmetry group of an observation — what the system SEES.
#[derive(Debug, Clone)]
pub struct SymmetryGroup {
    /// Detected symmetry elements, sorted by invariance residual.
    pub elements: Vec<SymmetryElement>,
    /// Total number of exact symmetries found (|G| where residual = 0).
    pub order: usize,
    /// D.VISION.1: Rotation gradient — how close is the closest torsion-4 element
    /// to exact invariance? 1 = exact rotation. 0 = no rotational structure.
    /// Replaces boolean has_rotation with continuous measurement.
    pub rotation: Q,
    /// D.VISION.1: Reflection gradient — how close is the closest torsion-2 element
    /// to exact invariance? 1 = exact reflection. 0 = no reflective structure.
    /// Replaces boolean has_reflection with continuous measurement.
    pub reflection: Q,
    /// D.PERIODICITY.1: Orbital closure gradient — the degree to which the
    /// observation's torsion structure approaches periodic closure.
    /// 1 = exact periodicity (closed orbit, torsion order achieved exactly).
    /// (0,1) = quasiperiodic (approaching closure, rational approximation).
    /// 0 = aperiodic (no detectable orbital closure).
    /// Not a boolean gate. The gradient from aperiodic through quasiperiodic
    /// to periodic IS the observation's position on the closure spectrum.
    pub orbital_closure: Q,
    /// The torsion spectrum: how many elements of each order.
    pub torsion_spectrum: Vec<(usize, usize)>, // (order, count)
    /// Transmutation gradient: how close is the best symmetry element
    /// to exactly relating source→target? 1 = exact transmutation perceived.
    /// 0 = no symmetry element explains the source→target relationship.
    pub transmutation: Q,
    /// The torsion order of the best transmutation element (lowest R(φ)).
    pub transmutation_order: usize,
}

/// Compute the symmetry group of a grid observation.
///
/// Tests candidate operators (permutations, reflections, rotations)
/// against the Delta and keeps those that leave it invariant.
/// The symmetry group tells the system WHAT the observation looks like —
/// not by naming patterns, but by measuring invariance.
pub fn compute_symmetry_group(values: &[i64], rows: usize, cols: usize) -> SymmetryGroup {
    let n = values.len();
    if n == 0 || rows == 0 || cols == 0 || rows * cols != n {
        return SymmetryGroup {
            elements: vec![], order: 0, rotation: Q::zero(),
            reflection: Q::zero(), orbital_closure: Q::zero(),
            torsion_spectrum: vec![],
            transmutation: Q::zero(), transmutation_order: 0,
        };
    }

    let mut elements: Vec<SymmetryElement> = Vec::new();

    // Generate candidate symmetry operators from grid geometry.
    // Each candidate is a permutation of cell indices.
    let mut candidates: Vec<(Vec<usize>, &str)> = Vec::new();

    // Horizontal reflection: (r, c) → (r, cols-1-c)
    if cols > 1 {
        let perm: Vec<usize> = (0..n).map(|i| {
            let r = i / cols;
            let c = i % cols;
            r * cols + (cols - 1 - c)
        }).collect();
        candidates.push((perm, "h_reflect"));
    }

    // Vertical reflection: (r, c) → (rows-1-r, c)
    if rows > 1 {
        let perm: Vec<usize> = (0..n).map(|i| {
            let r = i / cols;
            let c = i % cols;
            (rows - 1 - r) * cols + c
        }).collect();
        candidates.push((perm, "v_reflect"));
    }

    // 180° rotation: (r, c) → (rows-1-r, cols-1-c)
    if rows > 1 && cols > 1 {
        let perm: Vec<usize> = (0..n).map(|i| {
            let r = i / cols;
            let c = i % cols;
            (rows - 1 - r) * cols + (cols - 1 - c)
        }).collect();
        candidates.push((perm, "rot180"));
    }

    // 90° rotation (only if square grid)
    if rows == cols && rows > 1 {
        let perm: Vec<usize> = (0..n).map(|i| {
            let r = i / cols;
            let c = i % cols;
            c * cols + (rows - 1 - r)
        }).collect();
        candidates.push((perm, "rot90"));
    }

    // Transpose / diagonal reflection: (r, c) → (c, r). Square grids only.
    // Completes the D4 group: {e, r90, r180, r270, h, v, d, d'}.
    if rows == cols && rows > 1 {
        let perm: Vec<usize> = (0..n).map(|i| {
            let r = i / cols;
            let c = i % cols;
            c * rows + r
        }).collect();
        candidates.push((perm, "transpose"));

        // Anti-diagonal reflection: (r, c) → (cols-1-c, rows-1-r)
        let perm2: Vec<usize> = (0..n).map(|i| {
            let r = i / cols;
            let c = i % cols;
            (cols - 1 - c) * rows + (rows - 1 - r)
        }).collect();
        candidates.push((perm2, "anti_transpose"));
    }

    // Row shift (translational periodicity): shift all rows down by 1
    if rows > 1 {
        let perm: Vec<usize> = (0..n).map(|i| {
            let r = i / cols;
            let c = i % cols;
            ((r + 1) % rows) * cols + c
        }).collect();
        candidates.push((perm, "row_shift"));
    }

    // Column shift: shift all columns right by 1
    if cols > 1 {
        let perm: Vec<usize> = (0..n).map(|i| {
            let r = i / cols;
            let c = i % cols;
            r * cols + ((c + 1) % cols)
        }).collect();
        candidates.push((perm, "col_shift"));
    }

    // Test each candidate: does permuting the values leave the grid invariant?
    for (perm, _name) in &candidates {
        let mut residual: u64 = 0;
        for i in 0..n {
            residual += (values[i] - values[perm[i]]).unsigned_abs();
        }

        // Build the operator matrix from the permutation
        let mut mat = vec![vec![Q::zero(); n]; n];
        let mut inv = vec![vec![Q::zero(); n]; n];
        for i in 0..n {
            mat[i][perm[i]] = Q::one();
            inv[perm[i]][i] = Q::one();
        }

        // Compute torsion order: apply permutation repeatedly until identity
        let mut order = 1usize;
        let mut current = perm.clone();
        while order <= n {
            let is_identity = current.iter().enumerate().all(|(i, &j)| i == j);
            if is_identity { break; }
            let next: Vec<usize> = (0..n).map(|i| perm[current[i]]).collect();
            current = next;
            order += 1;
        }

        let residual_q = Q::new(BigInt::from(residual as i64), BigInt::from(1));

        elements.push(SymmetryElement {
            operator: Operator {
                id: elements.len(),
                matrix: mat,
                matrix_inv: inv,
                det_sign_positive: true,
            },
            torsion_order: order,
            invariance_residual: residual_q,
            transmutation_residual: Q::new(BigInt::from(i64::MAX), BigInt::from(1)), // unmeasured
        });
    }

    // Sort by invariance residual — exact symmetries first
    elements.sort_by(|a, b| a.invariance_residual.cmp(&b.invariance_residual));

    // Classify
    let exact_symmetries: Vec<&SymmetryElement> = elements.iter()
        .filter(|e| e.invariance_residual.is_zero())
        .collect();

    // D.VISION.1: Gradient measurements replacing boolean gates.
    // For each symmetry type, find the element with the closest invariance
    // and measure its quality as 1 - (residual / max_residual).
    let max_residual = elements.iter()
        .map(|e| &e.invariance_residual)
        .max()
        .cloned()
        .unwrap_or(Q::one());

    let symmetry_quality = |torsion_filter: &dyn Fn(usize) -> bool| -> Q {
        let matching: Vec<&SymmetryElement> = elements.iter()
            .filter(|e| torsion_filter(e.torsion_order))
            .collect();
        if matching.is_empty() { return Q::zero(); }
        // Best match = lowest residual among matching elements
        let best = matching.iter()
            .min_by(|a, b| a.invariance_residual.cmp(&b.invariance_residual))
            .unwrap();
        if max_residual.is_zero() {
            Q::one() // all exact
        } else if best.invariance_residual.is_zero() {
            Q::one() // this element is exact
        } else {
            // Gradient: 1 - best_residual / max_residual
            let ratio = Q::new(
                best.invariance_residual.numer() * max_residual.denom(),
                best.invariance_residual.denom() * max_residual.numer().clone(),
            );
            let one = Q::one();
            if ratio >= one { Q::zero() } else { &one - &ratio }
        }
    };

    let rotation = symmetry_quality(&|t| t == 4);
    let reflection = symmetry_quality(&|t| t == 2);

    // D.PERIODICITY.1: Orbital closure — the gradient from aperiodic to periodic.
    // Measures the best periodicity quality across all translational elements
    // (torsion orders > 2 and < n, which represent spatial repetition).
    // Quasiperiodic observations score between 0 and 1 — they approach closure
    // without achieving it exactly.
    let orbital_closure = symmetry_quality(&|t| t > 2 && t < n);

    // Torsion spectrum: includes ALL elements, not just exact ones.
    // The spectrum captures the full set of torsion orders with their
    // multiplicities — both exact and approximate symmetries contribute.
    // Torsion spectrum: project the symmetry hypercube onto the torsion axis.
    // Sort by group ordering, then group consecutive — exact multiplicity.
    // No boolean search. No find. The sort IS the structure.
    let mut orders: Vec<usize> = exact_symmetries.iter().map(|e| e.torsion_order).collect();
    orders.sort();
    let torsion_spectrum: Vec<(usize, usize)> = {
        let mut spec: Vec<(usize, usize)> = Vec::new();
        for &o in &orders {
            match spec.last_mut() {
                Some((prev, count)) if *prev == o => { *count += 1; }
                _ => spec.push((o, 1)),
            }
        }
        spec
    };

    SymmetryGroup {
        order: exact_symmetries.len(),
        elements,
        rotation,
        reflection,
        orbital_closure,
        torsion_spectrum,
        transmutation: Q::zero(),     // measured later with target
        transmutation_order: 0,
    }
}

/// Genomically weighted transmutation measurement.
///
/// R_g(φ) = ‖W_k · (φ(source) - target)‖
///
/// Each cell's contribution to the residual is weighted by the state record's
/// harmonic curvature at that position. The Householder metric W_k is
/// derived from the harmonic spectrum: cells at positions that resonate
/// with the state record's spatial harmonics contribute MORE to the residual.
/// Cells that fall outside the state record's aperture contribute LESS.
///
/// Result: a spatial-centric state record amplifies spatial discrepancies.
/// A value-centric state record amplifies value discrepancies. Each entity
/// perceives the SAME grid through a DIFFERENT curvature.
///
/// harmonics[0] = value weight, harmonics[1] = row weight, harmonics[2] = col weight.
/// The per-cell weight is derived from position: w(r,c) = |h1·r + h2·c| / (rows+cols).
/// When harmonics are empty, all weights = 1 (pre-genomic sight).
pub fn measure_transmutation(
    sym: &mut SymmetryGroup,
    source: &[i64],
    target: &[i64],
    _rows: usize,
    cols: usize,
    harmonics: &[crate::engine::Q],
) {
    if source.len() != target.len() || sym.elements.is_empty() { return; }
    let n = source.len();

    // Genomic aperture weight per cell.
    //
    // w(i) = N + |h0_n * cell_diff| + |h1_n * r| + |h2_n * c|
    //
    // where N = rows*cols (normalizer ensuring no cell is invisible),
    // h0_n/h1_n/h2_n are harmonic numerators (denominator scales the sum).
    // This produces a smooth gradient: spatial-centric state records (high h1,h2)
    // amplify cells at large r,c. Value-centric state records (high h0) amplify
    // cells with large value deltas uniformly. No saturation, no binary split.
    //
    // The denominator product ensures the weight stays in integer space
    // while preserving the RATIO between harmonics.
    let h0_d: i64 = harmonics.get(0).map(|q| q.denom().try_into().unwrap_or(1i64)).unwrap_or(1).max(1);
    let h1_n: i64 = harmonics.get(1).map(|q| q.numer().try_into().unwrap_or(1i64)).unwrap_or(1);
    let h1_d: i64 = harmonics.get(1).map(|q| q.denom().try_into().unwrap_or(1i64)).unwrap_or(1).max(1);
    let h2_n: i64 = harmonics.get(2).map(|q| q.numer().try_into().unwrap_or(1i64)).unwrap_or(1);
    let h2_d: i64 = harmonics.get(2).map(|q| q.denom().try_into().unwrap_or(1i64)).unwrap_or(1).max(1);
    // Common denominator for integer arithmetic
    let denom = (h0_d * h1_d * h2_d) as u64;
    // Base = denom (not n*denom). Each cell contributes base weight 1.
    // Spatial term adds on top — at high (r,c), spatial dominates base.
    // This makes the aperture spatially selective: the state record's harmonic
    // direction creates genuine asymmetry between symmetry elements.
    let base = denom;

    let cell_weight = |idx: usize| -> u64 {
        if harmonics.is_empty() { return 1; }
        let r = (idx / cols) as i64;
        let c = (idx % cols) as i64;
        // Each harmonic scaled to common denominator
        let w_spatial = (h1_n * r * (h0_d * h2_d) as i64).unsigned_abs()
                      + (h2_n * c * (h0_d * h1_d) as i64).unsigned_abs();
        base + w_spatial
    };

    for elem in &mut sym.elements {
        let mut best_r = u64::MAX;

        for mat in [&elem.operator.matrix, &elem.operator.matrix_inv] {
            let mut r: u64 = 0;
            for i in 0..n {
                let j = if i < mat.len() {
                    mat[i].iter().enumerate()
                        .find(|(_, v)| !v.is_zero())
                        .map(|(col, _)| col)
                        .unwrap_or(i)
                } else { i };
                if j < n {
                    // Genomically weighted residual per cell
                    let cell_diff = (source[j] as i64 - target[i] as i64).unsigned_abs();
                    r += cell_diff * cell_weight(i);
                }
            }
            best_r = best_r.min(r);
        }
        elem.transmutation_residual = Q::new(BigInt::from(best_r as i64), BigInt::from(1));
    }

    // Compute transmutation gradient: quality of the best element
    let max_r = sym.elements.iter()
        .map(|e| &e.transmutation_residual)
        .max()
        .cloned()
        .unwrap_or(Q::one());

    let best_elem = sym.elements.iter()
        .min_by(|a, b| a.transmutation_residual.cmp(&b.transmutation_residual));

    if let Some(best) = best_elem {
        sym.transmutation_order = best.torsion_order;
        if max_r.is_zero() {
            sym.transmutation = Q::one();
        } else if best.transmutation_residual.is_zero() {
            sym.transmutation = Q::one();
        } else {
            let ratio = Q::new(
                best.transmutation_residual.numer() * max_r.denom(),
                best.transmutation_residual.denom() * max_r.numer().clone(),
            );
            let one = Q::one();
            sym.transmutation = if ratio >= one { Q::zero() } else { &one - &ratio };
        }
    }
}

/// Legacy: derive from input symmetry group.
pub fn derive_from_symmetry(
    symmetry: &SymmetryGroup,
    input: &[i64],
    output: &[i64],
) -> Option<(Vec<usize>, u64, usize)> {
    if input.len() != output.len() || symmetry.elements.is_empty() {
        return None;
    }
    let n = input.len();
    let mut best: Option<(Vec<usize>, u64, usize)> = None;
    for elem in &symmetry.elements {
        let mut perm = vec![0usize; n];
        let mut is_permutation = true;
        for i in 0..n.min(elem.operator.matrix.len()) {
            let mut found = false;
            for j in 0..n.min(elem.operator.matrix[i].len()) {
                if elem.operator.matrix[i][j] == Q::one() {
                    perm[i] = j; found = true; break;
                }
            }
            if !found { is_permutation = false; break; }
        }
        if !is_permutation { continue; }
        let permuted: Vec<i64> = (0..n).map(|i| input[perm[i]]).collect();
        let residual: u64 = permuted.iter().zip(output.iter())
            .map(|(p, o)| (p - o).unsigned_abs()).sum();
        match &best {
            None => best = Some((perm, residual, elem.torsion_order)),
            Some((_, best_r, _)) if residual < *best_r => best = Some((perm, residual, elem.torsion_order)),
            _ => {}
        }
    }
    best.filter(|(_, r, _)| *r < n as u64 * 10)
}

/// D.VISION.TRANSLIMINAL.1 — See the transformation.
///
/// Vision looks at input AND output together. Generates candidate spatial
/// alignments (identity, reflections, rotations, translations) — NOT from
/// the input's symmetry group, but from the grid geometry itself. For each
/// alignment σ, computes the induced value map f where output[i] = f(input[σ(i)]).
/// Cross-validates (σ, f) across ALL practice pairs.
///
/// Identity is tested first — most transformations change values in place.
/// Non-identity alignments compose spatial + value into one transmutation.
///
/// Returns: (permutation, value_rule, residual) for the best composition
/// that generalizes across all practice pairs. None if nothing achieves jr=0.
/// VIII.4: see_transformation — Vision sense.
///
/// Previously composed spatial permutations with HashMap value factoring.
/// The spatial candidates (reflections, rotations, translations) were valid
/// orbital measurements. The value factoring was the dimensional collapse.
///
/// Now: returns None. The same spatial + value composition happens through
/// peel_manifold in escalation, where T = Δ_target - Δ_source captures
/// both spatial and value transformations in the n² relational structure.
/// Vision's measurement role is preserved in compute_symmetry_group.
pub fn see_transformation(
    _train_pairs: &[(Vec<i64>, Vec<i64>)],
    _rows: usize, _cols: usize,
) -> Option<(Vec<usize>, crate::thinking::FactoredRule, u64)> {
    None
}

/// Compute the symmetry quotient between input and output.
///
/// The quotient G_in / G_out tells the system which symmetries were
/// DEPARTED through the transformation. The departed symmetries ARE the rule.
///
/// Returns: (input_symmetry, output_symmetry, departed_symmetries, preserved_symmetries)
pub fn symmetry_quotient(
    input: &[i64], output: &[i64], rows: usize, cols: usize,
) -> (SymmetryGroup, SymmetryGroup, usize, usize) {
    let g_in = compute_symmetry_group(input, rows, cols);
    let g_out = compute_symmetry_group(output, rows, cols);

    // Symmetries preserved = present in both input and output
    // Symmetries departed = present in input but not output
    let preserved = g_in.torsion_spectrum.iter()
        .filter(|(order, _)| g_out.torsion_spectrum.iter().any(|(o, _)| o == order))
        .map(|(_, count)| count)
        .sum::<usize>();
    let departed = g_in.order.saturating_sub(preserved);

    (g_in, g_out, departed, preserved)
}
